### ISSUE TITLE
speed?

### ISSUE THREAD

**Issue by edwinosky** [albertobsd/keyhunt#10]
![image](https://user-images.githubusercontent.com/26192834/108460193-c5adb800-723d-11eb-9a29-4bdf9d806726.png)

Hello, thank you very much for your software, I am trying to run it correctly but I don't know if I am doing it right because the speed I see I think is very low, I am using an inter core i3 900F,

**Comment by dem10** [comment]
flag -m bsgs

**Comment by albertobsd** [comment]
Yes that is the problem you are using it without the flag -m bsgs, the default behaivor search for address and no for publickeys.

Address mode is  the slower method of keyhunt
