### ISSUE TITLE
why is that ?

### ISSUE THREAD

**Issue by Noname400** [albertobsd/keyhunt#100]
why is that ?
keyhunt-msvc.exe -m bsgs -f 1.txt -r 100000000000000000000000000000000000000000000000000000000000: E00000000000000000000000000000000000000000000000000000000000 -R -q -k 20 -t 2
in file 1.txt 4 lines
Total 492580739481600 keys in 150 seconds: 3283871596544 keys / s
in the file out.txt 2,000,000 lines
Total 0 keys in 150 seconds: 0 keys / s

why is that ?

**Comment by Noname400** [comment]
how many keys can there be in the file?

**Comment by albertobsd** [comment]
The speed in bsgs  mode is divided between the number of publickey.
2 publickey give you half of the speed of one single publickey.
4 publickey give you a quarter of the speed of one single publickey.
And so on...

Maybe you can test first some 1000 publickeys or 10 K publikeys just to know your final speed.

You can add all the publickey that you want but you need to wait for the speed, it only is update when all the publickeys pass through one cycle of the bsgs process.
