### ISSUE TITLE
[Makefile:15: default] Error 1

### ISSUE THREAD

**Issue by tareksibay** [albertobsd/keyhunt#101]
**i had this error**

tarek@Tarek-PC:~/keyhunt$ make
gcc -O3 -c bloom/bloom.c -o bloom.o
g++ -O3 -c sha256/sha256.c -o sha256.o
gcc -O3 -c base58/base58.c -o base58.o
gcc -O3 -c rmd160/rmd160.c -o rmd160.o
gcc -O3 -c sha3/sha3.c -o sha3.o
gcc -O3 -c xxhash/xxhash.c -o xxhash.o
g++ -O3 -c util.c -o util.o
g++ -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -c secp256k1/Int.cpp -o Int.o
g++ -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -c secp256k1/Point.cpp -o Point.o
g++ -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -c secp256k1/SECP256K1.cpp -o SECP256K1.o
g++ -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -c secp256k1/IntMod.cpp -o IntMod.o
g++ -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -c secp256k1/Random.cpp -o Random.o
g++ -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -c secp256k1/IntGroup.cpp -o IntGroup.o
g++ -o keyhunt keyhunt.c base58.o rmd160.o sha256.o bloom.o xxhash.o util.o Int.o  Point.o SECP256K1.o  IntMod.o  Random.o IntGroup.o -lgmp -lm -lpthread
/usr/bin/ld: cannot open output file keyhunt: Is a directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:15: default] Error 1

**Comment by albertobsd** [comment]
Two things that i notice.

Actually you are in the keyhunt directory:

> tarek@Tarek-PC:~/keyhunt$ make

> g++ -o keyhunt keyhunt.c base58.o rmd160.o sha256.o bloom.o xxhash.o util.o Int.o Point.o SECP256K1.o IntMod.o Random.o IntGroup.o -lgmp -lm -lpthread
> /usr/bin/ld: cannot open output file keyhunt: Is a directory

The error says that already exist some folder called keyhunt inside of the keyhunt directory.

Maybe you clone again the github repository inside of the keyhunt directory

to solve this error you need to delete te second subdiretory:

```
rm -rf keyhunt
```

And then use the comand make again:

```
make clean && make
```

**Comment by tareksibay** [comment]
Great It's work

Thanks alberto
