### ISSUE TITLE
Why so much difference in speed ?

### ISSUE THREAD

**Issue by greg2paris** [albertobsd/keyhunt#102]
Hello, I wanted to thank you for your great program.
I successfuly runned it on Ubuntu but failed on windows.
I have a question, why their is so much difference in spead when you search for ripmed160?
When you search for pubk you can get awesome speed 1Tera k/s.
But when you search for ripmed160 hash, the speed drop to around 800k/s.
Is their a way to make this as fast as the pubk search?

**Comment by albertobsd** [comment]
There is no way to increase the spees of modes rmd160 or address unless you do hardware improvements on your computer.

The main difference is that the BSGS mode use math tricks to get that speed if you want to know about that please read: https://andrea.corbellini.name/2015/06/08/elliptic-curve-cryptography-breaking-security-and-a-comparison-with-rsa/

**Comment by greg2paris** [comment]
Thank you for your answwer I will read this now.
Well done for this  awesome performance on pub key generation btw.
