### ISSUE TITLE
Random search

### ISSUE THREAD

**Issue by Cruz121** [albertobsd/keyhunt#104]
Is it possible to implement a random search for each thread? That is, generate a random search point for each thread, and not for all as it is currently implemented.

**Comment by albertobsd** [comment]
Sorry @Cruz121 i'm not sure of what are you trying to say

> search for **each thread**? 
> That is, generate a random search point for **each thread**
> and not **for all** 

If you read https://github.com/albertobsd/keyhunt/issues/72 you will see that each thread generates a base point of start key and iterate from that point to the ( base point + N) after finish that range, it select another random range.

Maybe i don't understand what you say, can you describe some example? like the https://github.com/albertobsd/keyhunt/issues/72

regards!
