### ISSUE TITLE
Progress is not displayed

### ISSUE THREAD

**Issue by Werdstron** [albertobsd/keyhunt#11]
Hello. When searching for thousands of keys, it does not show the progress and speed. [Screenshot here](https://ibb.co/MggFftN)

**Comment by brick-37** [comment]
Its like when you hunt for multiple keys at the same time, there is no status output and it stall after xx amount of keys.

Output:

--- CUT ---
localhost:~/keyhunt# ./keyhunt -m bsgs -f wallets.txt -R -t 4 -s 30
[+] Version 0.1.20210112 BSGS
[+] Setting mode BSGS
[+] Setting random mode.
[+] Setting 4 threads
[+] Stats output every 30 seconds
[+] Opening file allwalletsuncompressed.txt
[+] Added 3 points from file
[+] Setting N up to 17592186044416.
[+] Init bloom filter for 4194304 elements : 7.00 MB
[+] Allocating 128.00 MB for aMP Points
[+] Precalculating 4194304 aMP points
[+] Allocating 160.00 MB for bP Points
[+] precalculating 4194304 bP points
[+] Sorting 4194304 elements
[+] Thread 0: f541d6500e780f52f8e729c3122b5d7942fc923971eb6332577f6b3f58c00fc8
[+] Thread 1: f5a80c7b1f86dbf8d1e618ee8aeda0732a54d594cf09990d90e30fb68fa11d23
[+] Thread 2: f63f3d7c2baa3d3cf67cc08c6f4cc1c53492fe756e333c525444f2de134a3650
[+] Thread 3: e75b06d3ed9e4a73c739eacf467b00b72eca3c3e928bcfbd0cd0dad5b0121b63
[+] Thread 3: dc10fd01f5b6df14986ee0a5b3080934bf3266de8b131bc75cb5033e42a6bfe4
[+] Thread 1: d68a5a35081ee32a65d4ea6d8ca4b4dcf7a5288493b1f80bccf71c844adc8a89
[+] Thread 2: f6c4168900502a62ed73ccddf59daf4da7b8667ca8791cdaf71f7a198d14bbcb
[+] Thread 0: dd6a33834a5225d17fb4e0cf959a953d5d5a3d92ea297db397c7449af18b9b6c
Total 70368744177664 keys in 750 seconds: 93824992236 keys/s
Total 70368744177664 keys in 780 seconds: 90216338689 keys/s
Total 70368744177664 keys in 810 seconds: 86874992811 keys/s
--- CUT ---

**Comment by albertobsd** [comment]
Hi thanks for use my code.

The speed only is updated when the each thread finish one cycle, if you load 1112 Publickeys it will take a long time in complete one single cycle, please test with less publickeys to know the speed of your hardware.

Please read this topics:

https://github.com/albertobsd/keyhunt/issues/5
https://github.com/albertobsd/keyhunt/issues/6

best regards!

**Comment by brick-37** [comment]
Hello,

This is only with "Added 3 points from file" its more that it stops the Total count, why is that?

br
