### ISSUE TITLE
param -k and -n ?

### ISSUE THREAD

**Issue by Noname400** [albertobsd/keyhunt#110]
Am I using it correctly?
-k 4096 -n 0x400000000000
how to use 256gb memory?

**Comment by demonluca** [comment]
Hi Alberto what -k and -n would I use for 16gb and also would I use -S to save it for further operations. Thanks Demon

**Comment by albertobsd** [comment]
That is on the readme.

https://github.com/albertobsd/keyhunt#what-values-use-according-to-my-current-ram

Is some dont work please report it again

**Comment by sssergy** [comment]
![image](https://github.com/albertobsd/keyhunt/assets/26333870/87df561d-12d3-469e-b407-730e3704c5ce)
Hello Alberto.
I can offer my old server for testing.
Intel(R) Xeon(R) CPU E5-2697 v2 x2 and 756GB RAM
If this is necessary, please let me know. I will grant access.
There is another server on AMD EPIC 7V12 with 500GB of RAM
![image](https://github.com/albertobsd/keyhunt/assets/26333870/2f0d1f6e-f45e-4819-bfbd-23599edd8f54)


> That is on the readme.
> 
> https://github.com/albertobsd/keyhunt#what-values-use-according-to-my-current-ram
> 
> Is some dont work please report it again
