### ISSUE TITLE
Speed has decreased

### ISSUE THREAD

**Issue by Gusev39rus** [albertobsd/keyhunt#111]
Hi!
In the latest beta version 0.2.211012 in BGSG mode, the speed decreased exactly 2 times compared to version 0.2.211007. The command line is the same.

**Comment by Gusev39rus** [comment]
It's strange, but I don't see such a speed difference right now. But I recreated the Bloom filter in the old and new versions.
I'll check it tomorrow on a more powerful computer.

Thanks.

`$ ./keyhunt -m bsgs -t 4 -f tests/120.txt -n 1125899906842624 -s 10 -S -k 52 -r 800000000000000000000000000000:819999999999999999999999999999 -B random
[+] Version 0.2.211007 Chocolate ¡Beta!, developed by AlbertoBSD
[+] Threads : 4
[+] Stats output every 10 seconds
[+] K factor 52
[+] Mode BSGS random
[+] Opening file tests/120.txt
[+] Added 1 points from file
[+] Range 
[+] -- from : 0x800000000000000000000000000000
[+] -- to   : 0x819999999999999999999999999999
[+] N = 0x3ffffc8000000
[+] Bloom filter for 1744830464 elements : 5981.00 MB
[+] Bloom filter for 87241524 elements : 299.05 MB
[+] Allocating 1331.00 MB for 87241524 bP Points
[+] Reading bloom filter from file keyhunt_bsgs_0_1744830464.blm .. Done!
[+] Reading bloom filter from file keyhunt_bsgs_1_87241524.blm .. Done!
[+] Reading bP Table from file keyhunt_bsgs_2_87241524.tbl .. Done!
[+] Total 115967593633808384 keys in 10 seconds: ~11 Pkeys/s (11596759363380838 
[+] Total 235312884169572352 keys in 20 seconds: ~11 Pkeys/s (11765644208478617 
[+] Total 352406376770699264 keys in 30 seconds: ~11 Pkeys/s (11746879225689975 
[+] Total 472877566273781760 keys in 40 seconds: ~11 Pkeys/s (11821939156844544 
[+] Total 592222856809545728 keys in 50 seconds: ~11 Pkeys/s (11844457136190914 
[+] Total 711568147345309696 keys in 60 seconds: ~11 Pkeys/s (11859469122421828 
^C] Thread 0x804464b4082eb857a7178b6d84b3ad `

`$ ./keyhunt -m bsgs -t 4 -f tests/120.txt -n 1125899906842624 -s 10 -S -k 52 -r 800000000000000000000000000000:819999999999999999999999999999 -B random
[+] Version 0.2.211012 Chocolate ¡Beta!, developed by AlbertoBSD
[+] Threads : 4
[+] Stats output every 10 seconds
[+] K factor 52
[+] Mode BSGS random
[+] Opening file tests/120.txt
[+] Added 1 points from file
[+] Range 
[+] -- from : 0x800000000000000000000000000000
[+] -- to   : 0x819999999999999999999999999999
[+] N = 0x3ffffc8000000
[+] Bloom filter for 1744830464 elements : 5981.00 MB
[+] Bloom filter for 87241524 elements : 299.05 MB
[+] Allocating 1331.00 MB for 87241524 bP Points
[+] Reading bloom filter from file keyhunt_bsgs_3_1744830464.blm .. Done!
[+] Reading bloom filter from file keyhunt_bsgs_1_87241524.blm .. Done!
[+] Reading bP Table from file keyhunt_bsgs_2_87241524.tbl .. Done!
[+] Total 108086300862578688 keys in 10 seconds: ~10 Pkeys/s (10808630086257868 
[+] Total 216172601725157376 keys in 20 seconds: ~10 Pkeys/s (10808630086257868 
[+] Total 324258902587736064 keys in 30 seconds: ~10 Pkeys/s (10808630086257868 
[+] Total 433471102417633280 keys in 40 seconds: ~10 Pkeys/s (10836777560440832 
[+] Total 542683302247530496 keys in 50 seconds: ~10 Pkeys/s (10853666044950609 
[+] Total 651895502077427712 keys in 60 seconds: ~10 Pkeys/s (10864925034623795 
^C] Thread 0x813ed8bb220280f1de2ae67e4643b3  `

**Comment by fankoo** [comment]
here are the speed compare with JLP bsgs. All are single thread.

BSGS v1.2
BabyStep:0x1000000 (2^24.00)
Start:60000000000000
Stop :80000000000000
Keys :1
Number of CPU thread: 1
BabyStep Thread 0: 0x1 -> 0x1000000
[2.46 MKey/s][Cnt 2^24.00][06s][787.1MB]
Sort Thread 0: 00000000 -> 02000000
[60.80 MSort/s][Cnt 2^25.00][00s][787.1MB]
Warning, range is not a multiple of nbThread*1024
GiantStep Thread 0: 60000000000000
[3.57 MKey/s][Cnt 2^27.42][50s][787.1MB]
Key# 0 Pub:  0x0385A30D8413AF4F8F9E6312400F2D194FE14F02E719B24C3F83BF1FD233A8F963
       Priv: 0x6ABE1F9B67E114

Done: Total time 58s



time ./keyhunt -m bsgs -t 1 -f tests/55.txt -r 60000000000000:80000000000000 -n 0x1000000000000 -s 0
[+] Version 0.2.211012 Chocolate ¡Beta!, developed by AlbertoBSD
[+] Thread : 1
[+] Turn off stats output
[+] Mode BSGS secuential
[+] Opening file tests/55.txt
[+] Added 1 points from file
[+] Range
[+] -- from : 0x60000000000000
[+] -- to   : 0x80000000000000
[+] N = 0x1000000000000
[+] Bloom filter for 16777216 elements : 57.00 MB
[+] Bloom filter for 838861 elements : 2.88 MB
[+] Allocating 12.00 MB for 838861 bP Points
[+] processing 16777216/16777216 bP points : 100%
[+] Sorting 838861 elements... Done!
[+] Thread Key found privkey 6abe1f9b67e114
[+] Publickey 0385a30d8413af4f8f9e6312400f2d194fe14f02e719b24c3f83bf1fd233a8f963
All points were found

real    2m0.006s
user    1m59.191s
sys     0m0.070s

I use same number baby steps(2^24) to test.
It is about 2x slower than JLP BSGS.

**Comment by albertobsd** [comment]
> Off-topic question: Alberto, do I need to recreate the bloom filter if I changed the search range and the base public key? (parameters k n unchanged)

No, you don't need to change the files, it is independent of the publickey, just if you change the n or k values the files are going to be created if you have the -S option

**Comment by kpot87** [comment]
I can say to @albertobsd that on version012 I have speed around 800pkeys from 018 till now speed increases to 1,8Ekeys

**Comment by nightwalker89** [comment]
@albertobsd  

Same command but my output is a bit different. Could you explain this diff?, are there any change in speed ? Thank you 

> time ./keyhunt -m bsgs -t 1 -f tests/55.txt -r 60000000000000:80000000000000 -n 0x1000000000000 -s 0 -q -S -k 10
> [+] Version 0.2.211012 Chocolate ¡Beta!, developed by AlbertoBSD
> [+] Thread : 1
> [+] Turn off stats output
> [+] Quiet thread output
> [+] K factor 10
> [+] Mode BSGS secuential
> [+] Opening file tests/55.txt
> [+] Added 1 points from file
> [+] Range
> [+] -- from : 0x60000000000000
> [+] -- to   : 0x80000000000000
> [+] N = 0xfffffa000000
> [+] Bloom filter for 167772160 elements : 575.00 MB
> [+] Bloom filter for 8388608 elements : 28.76 MB
> [+] Allocating 128.00 MB for 8388608 bP Points
> [+] Reading bloom filter from file keyhunt_bsgs_3_167772160.blm .. Done!
> [+] Reading bloom filter from file keyhunt_bsgs_1_8388608.blm .. Done!
> [+] Reading bP Table from file keyhunt_bsgs_2_8388608.tbl .. Done!
> [+] Thread Key found privkey 6abe1f9b67e114
> [+] Publickey 0385a30d8413af4f8f9e6312400f2d194fe14f02e719b24c3f83bf1fd233a8f963
> All points were found
> 
> real    0m10.609s
> user    0m10.389s
> sys     0m0.220s

My output:
**Allocating is 2.00 MB** 

[+] Version 0.2.211117 SSE Trick or treat ¡Beta!, developed by AlbertoBSD
[+] Thread : 1
[+] Turn off stats output
[+] Quiet thread output
[+] K factor 10
[+] Mode BSGS secuential
[+] Opening file tests/55pub.txt
[+] Added 1 points from file
[+] Range
[+] -- from : 0x60000000000000
[+] -- to   : 0x80000000000000
[+] N = 0xfffffa000000
[+] Bloom filter for 167772160 elements : 575.10 MB
[+] Bloom filter for 5242880 elements : 17.97 MB
[+] Bloom filter for 163840 elements : 0.88 MB
**[+] Allocating 2.00 MB for 163840 bP Points**
[+] processing 167772160/167772160 bP points : 100%
[+] Making checkums .. ... done
[+] Sorting 163840 elements... Done!
[+] Writing bloom filter to file keyhunt_bsgs_4_167772160.blm .... Done!
[+] Writing bloom filter to file keyhunt_bsgs_6_5242880.blm .... Done!
[+] Writing bP Table to file keyhunt_bsgs_2_163840.tbl .. Done!
[+] Writing bloom filter to file keyhunt_bsgs_7_163840.blm .... Done!
[+] Thread Key found privkey 6abe1f9b67e114
[+] Publickey 0385a30d8413af4f8f9e6312400f2d194fe14f02e719b24c3f83bf1fd233a8f963
All points were found

real    2m0.252s
user    3m51.257s
sys     0m0.878s

**Comment by albertobsd** [comment]
Can you run the same again? The last version remade some files so if you notice the b Points were processed again.

>[+] processing 167772160/167772160 bP points : 100%

If youn run the command again it will take less time

**Comment by nightwalker89** [comment]
The different is  **Allocating 2.00 MB for 163840 bP Points** (Version 0.2.211117) vs **Allocating 128.00 MB for 8388608 bP Points** (0.2.211012)
2M vs 128M.
Is this important?
I have pull and build from newest version:  **Version 0.2.211117**

**Comment by albertobsd** [comment]
The number of bP points only change if you change the k or n values. The new newest version use less memory

**Comment by albertobsd** [comment]
The new version use less memory
