### ISSUE TITLE
Random mode -R

### ISSUE THREAD

**Issue by tahasasa123** [albertobsd/keyhunt#113]
Hello, the Random mode -R supposed to just keep generating random points and not generate a random point each thread..
if you can change the -R random mode to keep just jumping and generating randomly it'll be really helpful to try to solve that #64 puzzle.
Thank you so much!

**Comment by albertobsd** [comment]
> if you can change the -R random mode to keep just jumping and generating randomly it'll be really helpful to try to solve that #64 puzzle. 

It is what actually the `-R` options do.
