### ISSUE TITLE
Sequential search

### ISSUE THREAD

**Issue by sssergy** [albertobsd/keyhunt#115]
Alberto, good afternoon.
Sequential search question.
Can you filter out characters that are repeated 2-3 times?
Yes, I understand that the speed will drop significantly, but iterating over repeated characters takes most of the work.
Sorry, I'm writing with a translator.

**Comment by albertobsd** [comment]
This is for addrees mode?
Or what kind of characters did you mean?

Please feel free to add a visual example of what you want it will be more helpful

**Comment by sssergy** [comment]
This can be used in any mode.
On such small ranges, it is almost impossible to find more than three repeating characters, and even then this is a rarity. It makes no sense to sort out combinations of type; FFFFFFFFF?, 800000000, AAABBBCCCDDD etc.

**Comment by sssergy** [comment]
There are many password generators with this functionality, some of the code can be taken from there.

**Comment by BrabusNight85** [comment]
AAA

**Comment by sssergy** [comment]
> Ok, thanks i will try to implement this :)

https://chat.openai.com/share/88fcc48e-b189-4935-a383-dcbd934a8d6a
