### ISSUE TITLE
why is it not loading?

### ISSUE THREAD

**Issue by Noname400** [albertobsd/keyhunt#116]
![image](https://user-images.githubusercontent.com/74019756/137611859-2657c8f2-d0ba-421d-8508-c28f6ffda799.png)

keyhunt012 -m bsgs -f 120.txt -b 120 -k 80 -S -q -t 3

**Comment by sssergy** [comment]
Так только в виндовс, в линукс работает нормально.

**Comment by Noname400** [comment]
Это плохо. Надо решать

**Comment by sssergy** [comment]
It is this version that is use
![Screenshot_1](https://user-images.githubusercontent.com/26333870/137627865-22e114d1-efe7-4ac3-8a13-9fc0a0c0f65e.png)
d.

**Comment by sssergy** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/26333870/137628111-c7fe3c25-7185-4c04-b5ec-264f9f7ff147.png)
And there is no difference whatever you write in the launch parameters.

**Comment by albertobsd** [comment]
Maybe there some internals differences between windows version and my version i will check it

**Comment by albertobsd** [comment]
Please use WSL environment, i will work for the native windows version later.
