### ISSUE TITLE
can we Faster this code With Gpu

### ISSUE THREAD

**Issue by websonder** [albertobsd/keyhunt#12]
can we Faster this code With Gpu

**Comment by dem10** [comment]
In the 120 range, you need to check 664.613.997.892.457.936.451.903.530.140.172.287 keys. The speed of one stream is about 1.000.000.000.000 keys per second. Even if the video card is 100 times faster, this will not help much.Calculate how much time you need if you check the range from start to finish. Here luck and search in random are more important.

**Comment by websonder** [comment]
Okay Understand

**Comment by albertobsd** [comment]
@dem10 thanks for reply, good anwser.

@websonder yes of course with GPU it will be more faster obvious. But still is not enough speed, if you want use GPU use kangaroo, is like 1000 faster that my keyhunt tool, this only with some many Highend video cards. Think in this : the person who solve the puzzle 115 use some 100 or 200 Video cards to solve the 115 in some week, the 120 puzzle is some 32 times bigger than the 115
