### ISSUE TITLE
single key mode from file

### ISSUE THREAD

**Issue by nft30001** [albertobsd/keyhunt#121]
Hi @albertobsd always thanks for your awesome work.

can you please implement single mode for file.

like if there are 100000 keys in input file and we set 64 range to scan for 100000 keys so program should pick 1 key first and scan whole range for first key if not found program switch to second one and scan whole range and so on. Thanks in advance

**Comment by dem10** [comment]
Why do you need to switch keys? Range #64 is very huge to search by address or  ripemd160. It will take you decades to make 1 pass.

**Comment by dem10** [comment]
> Hi @albertobsd always thanks for your awesome work.
> 
> can you please implement single mode for file.
> 
> like if there are 100000 keys in input file and we set 64 range to scan for 100000 keys so program should pick 1 key first and scan whole range for first key if not found program switch to second one and scan whole range and so on. Thanks in advance

Why do you need to switch keys?'m sure that there is only one address in the 64 range with the balance being empty.

**Comment by kpot87** [comment]
@sssergy поиграйся с -k

**Comment by kpot87** [comment]
Now I can create as much as possible points. Just one bug left is first 5% at start used just one core and on last version it’s stops on 99% of creating bloom. Now I start to regenerated a new filter of 295Gb ram, let’s see what will be

**Comment by sssergy** [comment]
k 8192 stupid 99%
k 16384 stupid 49%
Considering that the first 5% takes the longest for the bloom filter, it's not very pleasant to know that the time is wasted.

**Comment by albertobsd** [comment]
> k 8192 freezes 99% k 16384 freezes 49% Considering that the first 5% takes the longest for the bloom filter, it's not very pleasant to know that the time is wasted.

Sorry to heard that :(

yes the bug is also reported by zielar on https://github.com/albertobsd/keyhunt/issues/139

I wil put some effort to solve this ASAP but please be patient.

Regards!

**Comment by albertobsd** [comment]
This should be solved but if someone found some parameters that don't work please let me now

**Comment by albertobsd** [comment]
> Hi @albertobsd always thanks for your awesome work.
> 
> can you please implement single mode for file.
> 
> like if there are 100000 keys in input file and we set 64 range to scan for 100000 keys so program should pick 1 key first and scan whole range for first key if not found program switch to second one and scan whole range and so on. Thanks in advance

I am about o finish a BSGS server that will do that on demand. I will le you know when it is finished

**Comment by albertobsd** [comment]
test if you want:

https://github.com/albertobsd/keyhunt/blob/main/BSGSD.md

**Comment by sssergy** [comment]
> test if you want:
> 
> https://github.com/albertobsd/keyhunt/blob/main/BSGSD.md

Does Bloom filter reload every time? After every request?

**Comment by albertobsd** [comment]
No, bloom and data are only reload every time tha you restart program, so if you don't restart this server version the data never will be reloaded.

So every request is processed almost inmediatly.
