### ISSUE TITLE
multikey search

### ISSUE THREAD

**Issue by makabress** [albertobsd/keyhunt#13]
hi
excelent work

i just want ask it's a multi key search simultaneously or it will search by order in the list one by one??

thank you

**Comment by albertobsd** [comment]
yes in mode bsgs the program search in a Range of N items, in order from the publickeylist one by one, that is because the math 
Operations behind the speed are per public key.

Regards!

**Comment by makabress** [comment]
Is it the same when use mode xpoint or address mode?

**Comment by iceland2k14** [comment]
No. 
In xpoint mode or address mode, all of them are checked simultaneously.

**Comment by makabress** [comment]
Nice thank you

**Comment by albertobsd** [comment]
Thanks for reply @iceland2k14 I will update the readme to clarify this
