### ISSUE TITLE
losing ram usage gradually over time

### ISSUE THREAD

**Issue by nft30001** [albertobsd/keyhunt#133]
Guys , not sure if this is bug or not but i thing this is more serious than all. one of my testing rig is running new keyhunt version but i found some strange issue not sure if that was present in old version or not.

issue is ~ lets say when all program load finished i was occupying 10328MB ram. i noticed over time keyhunt ram usage was decreased to 9820.4MB. i stopped program and calculate key on distance which program should reach in one day during sequential search mode. but strangely today my program passed that one point and didn't get that point. now i feel some issue is maybe there.

i am going to run test again by creating new files with -S option and will run it again for one day and will report back.

if this is true that program is losing ram usage over time and missing hits than this is more serious than all. very serious as we will never reach the goal and all hash power is going in waste.

**Comment by albertobsd** [comment]
> It is understood that the value of the passed keys is indicated by the program incorrectly.
why did you say that? Please open a new issue for it.

**Comment by albertobsd** [comment]
I just made a test with 128 GB of RAM and I notice that the amount of RES memory went from 120 to 107 but the amount of  SWAP usage increment from some 7 GB to 30 GB, maybe that is the behavior that you notice, is your swap begin used ?

![image](https://user-images.githubusercontent.com/17832765/139594096-b6a6584b-12e7-49ed-915c-34cb24b8a4fc.png)

**Comment by nft30001** [comment]
@albertobsd  sorry i didn't have time to test it further but will find time to test it and will report you back

**Comment by nft30001** [comment]
no issue recorded ~ everything is stable and even over time gradually program was losing some ram but still no impact on functionality

**Comment by albertobsd** [comment]
Yeah, is nice to heard that.
