### ISSUE TITLE
режим rmd160

### ISSUE THREAD

**Issue by Vladimir855** [albertobsd/keyhunt#134]
Подскажите как  найти индекс для выполнения математической операции HIT!! PrivKey: 8009c16fb9  покажите пример?

**Comment by albertobsd** [comment]
Did you guys want a video about the key subtraction ?

Regards!

**Comment by kpot87** [comment]
Yes, @albertobsd from previous video I couldn’t understand why you do - 1, for what?

**Comment by albertobsd** [comment]
Is because we don't know if the privatekey is Even or Odd.

I just publish this thread https://github.com/albertobsd/keyhunt/discussions/136

**Comment by Vladimir855** [comment]
режим rmd160 не позволяет искать по личному адресу - это как понимать? в этом режиме не будет искать по списку хэшей?

**Comment by dem10** [comment]
> режим rmd160 не позволяет искать по личному адресу - это как ? в этом режиме не будет искать по списку хэшей?
> 
> обязательно ставить -l compress ? если поставлю -l uncompress или вообще ничего, будет идти поиск?

я знаю потому что не знаю о том что знаю когда пойму.вы сами не понимаете о чем спрашиваете.

**Comment by sokary2004** [comment]
rmd160 ===> More than 160 million wallets. The program gives an error

**Comment by albertobsd** [comment]
> rmd160 mode ===> More than 160 million wallets. The program gives an error

What error, please send a screenshot.

Regards!
