### ISSUE TITLE
-C

### ISSUE THREAD

**Issue by demonluca** [albertobsd/keyhunt#140]
Hi Alberto thanks for the update 

-C option is coming up with invalid option?
 I’m using -m minikeys mode any advice on how to use it please

**Comment by albertobsd** [comment]
Oo thanks for notify this issue, yes i was doing that part of code but I did not finished it.

Sorry for the inconvenient i will update the code soon with that change.

Regards!

**Comment by demonluca** [comment]
Could you explain how to use the mode in more detail  when updated when you have time please.

Like is -C connected to a txt file? Do you still use -m minikeys and is it possible to search in range (S) minikey format?

Thanks Demon

**Comment by albertobsd** [comment]
I will change the way of the generation of the minikeys actually is some random/deterministic way.

But after the changes it will be sequentially the idea with `-C` is that use some range in minikey format like `S111111111111111111111:Szzzzzzzzzzzzzzzzzzzzz` that will be the default range, so if you want to brute specific some specific range of a minikey you can use:

`-C SG64GZqySYwBm9Kx111111:SG64GZqySYwBm9Kxzzzzzz`

Also you will be able to change the the base58 alphabet

`-8 123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz`  default 
`-8 S23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz` or something else that you like.

**Comment by demonluca** [comment]
Thanks for explaining looking forward to the update

**Comment by albertobsd** [comment]
Last commit https://github.com/albertobsd/keyhunt/commit/338184301c155ba2d07bb6259f05f88543ca0a53 have the new Minikeys generation, check the readme there is a good example for that.
