### ISSUE TITLE
No way displays the range

### ISSUE THREAD

**Issue by Knopius** [albertobsd/keyhunt#143]
Hello!
The new version (31) in no way displays the range in which the calculation is performed in real time or once in a given period of time. Previously, this was displayed on the screen, and removed with -q. Now -q doesn't make sense, since nothing changes with or without it.
Can this be fixed ?

BR

**Comment by albertobsd** [comment]
Hi, can you show us what is the exactly command that are you using?

I'm using this:

```./keyhunt -m bsgs -f tests/120.txt -b 120 -s 0 -R```

And the range is there

![image](https://user-images.githubusercontent.com/17832765/140527175-a63ae7ed-1ebf-4431-945f-79aa9bdbe5ef.png)

**Comment by Knopius** [comment]
Hello!
Below are screenshots for BSGS mode.
If I add a file with 500k + records, then "Thread" shows only the first value and freezes.
![image](https://user-images.githubusercontent.com/79412464/140610327-af9ab1db-611f-4e0d-b9a9-41d198dfed47.png)
If I add a file that contains 1 record, then everything works fine.
![image](https://user-images.githubusercontent.com/79412464/140610485-b61fc3cf-3cbb-4e9f-9414-ac387b8ccc66.png)

**Comment by Knopius** [comment]
Below is a screenshot of rmd160 mode.
Regardless of the number of records in this file, "Thread" shows only the first value and freezes.

![image](https://user-images.githubusercontent.com/79412464/140610937-5311e6df-bba3-4e45-96f6-36c240d664b1.png)

**Comment by albertobsd** [comment]
well that is normal for the other modes rmd160 since you are specifying a big N value the program will not update the Base key until each thread finish that N value.

for BSGS mode with more than some thousand of publickeys please check https://youtu.be/MVby8mYNxbI

Its completty normal because in BSGS the speed is shared between the number of keys that you add.
