### ISSUE TITLE
[Question] Where does the range comes from (-r)?

### ISSUE THREAD

**Issue by PavKmiec** [albertobsd/keyhunt#145]
Hi, 

I was wondering if someone could explain in little more detail: where does the range values `-r` come from?

Let say for a given address or a pub key (`bsgs`), are those ranges only known for the puzzle because we know the values of previous and following solved private keys/difficulty or is there some maths behind calculating/estimating a range for any address/pub key?

Thanks.

**Comment by albertobsd** [comment]
There is no way to calculate the range of a privatekeys for the non puzzles addresses.
