### ISSUE TITLE
Intermediate memory values 

### ISSUE THREAD

**Issue by phrutis** [albertobsd/keyhunt#148]
Hi albertobsd.
There are questions from memory.
If the PC is 64GB - Windows 3-4GB, you can use only 32GB (-k 2048) 28GB remains
If the pc is 128GB - Windows 3-4GB, you can use only 64GB (-k 4096) 60GB remains

If add value -k 2048 + (512, 1024) error
If add value -k 4096 + (512, 1024, 2048) error

If you run a copy of the program with a lower value, it gives an error. It turns out that for many, half of the memory is not used.
This works between -k 512 and -k 1024 can be set to -k 768
It turns out 2 TB RAM can only be used -k 16384 (1 TB cannot be used) 
Or how to specify intermediate values -k? 
Thanks 

Correct in README.md
64 GB -n 0x100000000000 **-k 4096**
128 GB -n 0x400000000000 **-k 4096**

**Comment by sssergy** [comment]
Я заметил что при увеличении памяти, скорость особо не растет.
Пробовал 756 ОЗУ 48 Ядер.

**Comment by albertobsd** [comment]
Hi, first thanks for test the program.

About your errors please Add one screenshot or full text output of each error just to review all of them in details, i want to solve if it is possible.

Actually you can use **any** K value Even numbers like `-k 1337` or any other i already test some values like that  and they works well since I solve the issue: [very strange issue (possible bug) ](https://github.com/albertobsd/keyhunt/issues/130) All the K errors are solved, but yes you need to test for hit and test for no missing keys.

For the tests add you currents N and K values

16 Publickeys in a 64 bits range this is the JeanLucPons test file tests/in.txt in this test all the 16 Publickeys must be found.

```
time ./keyhunt -m bsgs -f tests/in.txt -r 49dccfd96dc5df56487436f5a1b18c4f5d34f65ddb48cb5e0000000000000000:49dccfd96dc5df56487436f5a1b18c4f5d34f65ddb48cb5effffffffffffffff  -M -s 0 -S
```

64 Publickeys from the already solved puzzles from 1 to 65 in file `tests/1to63_65.txt` in this test all the 64 Publickeys must be found.

```
./keyhunt -m bsgs -f tests/1to63_65.txt -r 1:20000000000000000  -M -s 0 -S
```
 Any missing key please let me know

**Comment by phrutis** [comment]
Notebook i7 (6 cores 12 threads) 64GB Windows x64
I did my tests, I find everything.
I wanted to take the Keynunt and modify it. I looked at the code, everything is well done, I did tests.
New correct random start and finish works correctly, does not go out of range.
Here are the screenshots Intermediate memory values
![errr](https://user-images.githubusercontent.com/82582647/142363595-63e7a1b9-efc6-4a32-ac6a-60313b4742df.jpg)

-k 2048 work
![2048-12-Turbo](https://user-images.githubusercontent.com/82582647/142363757-9bf5d7b6-a545-482e-ae8f-4e9a5005aa5a.jpg)

**Comment by phrutis** [comment]
time in Windows does not work for me.
Invalid time value. Enter the time, after entering the time on the pc, the time changes.

**Comment by sssergy** [comment]
> Notebook i7 (6 cores 12 threads) 64GB Windows x64
> 
> Screenshots test Intermediate memory values ![errr](https://user-images.githubusercontent.com/82582647/142363595-63e7a1b9-efc6-4a32-ac6a-60313b4742df.jpg)
> 
> -k 2048 work ![2048-12-Turbo](https://user-images.githubusercontent.com/82582647/142363757-9bf5d7b6-a545-482e-ae8f-4e9a5005aa5a.jpg)
> 
> time in Windows does not work for me. Invalid time value. Enter the time, after entering the time on the pc, the time changes

В WSL Ubuntu все работает с последней версии. Из 16 Гб занято 14. Ида, в Windows time это совсем другая команда и нет ничего похожего на нее.
![image](https://user-images.githubusercontent.com/26333870/142378630-113a2d76-2503-48bc-a37b-9be39d698f14.png)

**Comment by phrutis** [comment]
Intermediate memory values between -k 128 and -k 1024 work, I wrote about it.
Test -k 768, -k 800 works in Windows.
Problem with intermediate values after -k 2048
-k 2176 Error! -k 3072 Error!

**Comment by sssergy** [comment]
> Промежуточные значения памяти между -k 128 и -k 1024 работают, я об этом писал. Test -k 768, -k 800 работает в Windows. Проблема с промежуточными значениями после -k 2048 -k 2176 Ошибка! -k 3072 Ошибка!

Забыл добавить, последние версии не компилировались для windows, эта проблема уже была уже решена ранее.

**Comment by sssergy** [comment]
https://github.com/albertobsd/keyhunt/issues/126

**Comment by phrutis** [comment]
In the evening I will try to compile the latest version of keyhunt for Windows. I will test, unsubscribe

**Comment by albertobsd** [comment]
The lastest version will solve your errors... but it can't be compiled in windows directly.

Please use the WSL with the Ubuntu shell it is available in the windows 10 Store for FREE

Regards!

**Comment by phrutis** [comment]
Thanks, I will try to compile
