### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sokary2004** [albertobsd/keyhunt#150]
keyhunt.cpp:545:50: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
  545 |      fprintf(stderr,"[E] Invalid Minikey length %i : %s\n",strlen(optarg),optarg);
      |                                                 ~^         ~~~~~~~~~~~~~~
      |                                                  |               |
      |                                                  int             size_t {aka long unsigned int}
      |                                                 %li

can not make keyhunt . 

and what is minikey ?  anybody know ?

**Comment by albertobsd** [comment]
It is just a warning

`keyhunt.cpp:545:50: warning: ` <<------------- warning

The keyhunt program is already compiled in your folder you can omit that warning.

Regards!
