### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by myne123** [albertobsd/keyhunt#151]
keyhunt.cpp: In function ‘int main(int, char**)’:
keyhunt.cpp:545:50: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
  545 |      fprintf(stderr,"[E] Invalid Minikey length %i : %s\n",strlen(optarg),optarg);
      |                                                 ~^         ~~~~~~~~~~~~~~
      |                                                  |               |
      |                                                  int             size_t {aka long unsigned int}
      |                                                 %li

**Comment by albertobsd** [comment]
That is just a warning. Your program it is already compiled please check your current directory
