### ISSUE TITLE
--Stride option  in what modes does it work?

### ISSUE THREAD

**Issue by Pidberezkiy** [albertobsd/keyhunt#152]
albertobsd commented 27 days ago
This option is already in the last update please use it with -I 1 where 1 is the stride.

Any comments let me now
https://github.com/albertobsd/keyhunt/issues/37#issuecomment-951156537
I tried using this parameter in xpoint modes as well as in bsgs mode but didn’t see it working. Stride: 100,000,000,000 I expected a stride every 100,000,000,000 keys, but it doesn't. Thanks.

**Comment by albertobsd** [comment]
Only is available for address, rmd160, xpoint and ethereum.

It will never going to work for bsgs check

https://github.com/albertobsd/keyhunt/issues/132

**Comment by timucindusunur** [comment]
Hi alberto I appreciate your work. If we specify the step option as 1, the name does not have any meaning? We should be able to specify the desired number, as in bitcrack. Therefore, the step function does not work.
