### ISSUE TITLE
Windows 64 Version ?

### ISSUE THREAD

**Issue by RobGo88** [albertobsd/keyhunt#154]
Is the current keyhunt version also available for Windows 64 ?
If so, where can I get this?
Am grateful for any support

**Comment by dem10** [comment]
No, not available (compilation problems). Use WSL.

**Comment by phrutis** [comment]
Try updated versions by XopMC [Windows](https://github.com/XopMC/keyhunt-win)

**Comment by dem10** [comment]
> 



> 

Yes, today XopMC has made a version for Windows but read readmi. The MINIKEYS mode is available only for processors with the SSSE3 instruction. https://github.com/XopMC/keyhunt-win/releases ReadMe https://github.com/XopMC/keyhunt-win#readme

**Comment by nightwalker89** [comment]
another window version https://github.com/kanhavishva/keyhunt

**Comment by myne123** [comment]
Just run it in windows subsystem for linux. It's easy enough.
