### ISSUE TITLE
Random mode in BSGS very slow?

### ISSUE THREAD

**Issue by onusai** [albertobsd/keyhunt#156]
Hi, when I use bsgs mode with `-b 120` the program runs at about 108 Pkeys/s. However, when I use `-R` its reporting about 47,000 keys/s. Is random mode that much slower?

`./keyhunt -m bsgs -t 12 -f ctests/t1.txt -k 1024 -R -S`
^C] Thread 0xf59960497840501e08e345d38a3bcf173b020201e6a3c6c44ae8f517150b568b  47472 keys/s)

`./keyhunt -m bsgs -t 12 -f ctests/t1.txt -k 1024 -b 120 -S`
^C] Thread 0x800000000000003b1a300000000000   ds: ~108 Pkeys/s (108766817719343149 keys/s)

**Comment by dem10** [comment]
Do you see that you have mixed speed and output of the thread? In random mode, the base key changes very quickly. Put the -q flag and I think that the correct speed will be shown ..

**Comment by onusai** [comment]
@dem10 That fixed it, thank you!
