### ISSUE TITLE
Make Error Ubuntu 20.04.3 LTS 

### ISSUE THREAD

**Issue by Knopius** [albertobsd/keyhunt#157]
keyhunt.cpp: In function ‘int main(int, char**)’:
keyhunt.cpp:545:50: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
  545 |      fprintf(stderr,"[E] Invalid Minikey length %i : %s\n",strlen(optarg),optarg);
      |                                                 ~^         ~~~~~~~~~~~~~~
      |                                                  |               |
      |                                                  int             size_t {aka long unsigned int}

**Comment by dem10** [comment]
This is not a Error but a warning.The compiled file must already be in the folder.

**Comment by Knopius** [comment]
What need I do ? Or is it normal ?

**Comment by albertobsd** [comment]
You don't need to do anything.

It is already compiled
