### ISSUE TITLE
best customized 80 CPU

### ISSUE THREAD

**Issue by AhrimanSefid** [albertobsd/keyhunt#159]
Hi.
Can help me best customized 80 CPU.

![image](https://user-images.githubusercontent.com/1332246/146574511-90d4f2a4-564f-40cb-8085-6b083f5fc69e.png)

**Comment by albertobsd** [comment]
`-t 80`

**Comment by AhrimanSefid** [comment]
yes me add
can anydesk my system check.

**Comment by dem10** [comment]
You have a flag value of -t 200. Do you have 200 threads? Oh my god.🤦‍♂️

**Comment by albertobsd** [comment]
> yes me add can anydesk my system check.

No sorry I don't do personal support. I already write that program for free.
