### ISSUE TITLE
Compile warning!

### ISSUE THREAD

**Issue by Chesterfield007** [albertobsd/keyhunt#16]
format ‘%f’ expects argument of type ‘double’, but argument 3 has type ‘uint32_t {aka unsigned int}’ [-Wformat=]
   printf("[+] Allocating memory for %u elements ?????

**Comment by albertobsd** [comment]
Hi, well technically is not an error but i'm going to clean up those warnings

thanks for report it

Regards!

**Comment by Chesterfield007** [comment]
> Hi, well technically is not an error but i'm going to clean up those warnings
> 
> thanks for report it
> 
> Regards!

Thank you so much bro, you did a great job

**Comment by albertobsd** [comment]
Solved in the last commit https://github.com/albertobsd/keyhunt/commit/519cbfd78ee9f7c5f68b94f642214c932b48061b

btw, I just compiled in Debian and in termux, no warning if you still get some other warning please letme know.
