### ISSUE TITLE
Searching for a part of the key

### ISSUE THREAD

**Issue by avtoblesk** [albertobsd/keyhunt#161]
Alberto, greetings! English is not my native language.
I have a question for you as a specialist.

For example, I have the address: 1C2oZf844C9ZM3g4gHKFQwPY7fYKKjMbD4
and part of the key (the last 40 characters): tPKuKoz2xD5AnujeeU6Y38hqwQVW9mFegtxjwjpi.
Pub key unknown
It is not known whether the key and address are compressed or not. How to determine /calculate in which range to search and which program is optimal?

How to split ranges if there are 3 powerful ones. 1x 16/32 streams, 2x 12/24 streams.
Your ideas are interesting. You can even make a short video with this research.
Thank you in advance!

**Comment by dem10** [comment]
You cannot find out the range. Your privkey is in WIF format and the first characters are missing. It is impossible to find out something by such a key.

**Comment by avtoblesk** [comment]
So, the selection range should be carried out according to the WIFE format, but which program and how best to split the search ranges on 3 systems and speed up the process?

**Comment by albertobsd** [comment]
If you have the publickey of that address I can find the key in 10 minutes, if not it will take thousand years

**Comment by nikolayresh** [comment]
But you will not crack it if you don't know the exact range of private key

**Comment by avtoblesk** [comment]
Well, how to find out exactly whether the key is compressed or not, or does it not play a special role? Now, to minimize the search, you need to understand this. WIF is not compressed or not, from this we get a search zone in K+10+ a known part / 3 of the process of 64 per thread, or it is compressed, then we will need to search for L1-4+10+ part of the key, or K at the beginning?

**Comment by albertobsd** [comment]
> But you will not crack it if you don't know the exact range of private key

The range is indicate by partial Wif.

**Comment by avtoblesk** [comment]
The question is also how the program will substitute values if some of the consecutive values are not valid for any of the existing keys.

**Comment by albertobsd** [comment]
Bro you will never solve that with CPU is like to solve the puzzle 64, and it is not solved yet.

**Comment by albertobsd** [comment]
Lets to supposse that the last missing characeter of your WIF is in the possition 44
So the increment will be 58^45

Example:
WIF: L2JR****tSVjxmTSXQs8WFz4y7Pbs1t9rdEqiSxQBYUMPuLNSNgE
Increment (base58) will be: 211111111111111111111111111111111111111111111

But to skip some inecesary process (Encode/decode  base58) we need to word with integers numbers only:

Increment in number.

Base10 : 389790918707373377135528568990913592653094657612049369038476873218241589149696
Base16: 0x035dc5d77b83d07b8feef18a81bd06d803b1ab9dcf25b6a6aed55f100000000000

So we need to define a Basekey it will be the Partial WIF but filled with ONES:

L2JR1111tSVjxmT11118WFz4y7Pbs1t9rdEqiSxQBYUMPuLNSNgE

Base16: 80979b548fd8e99e65fccb96df1351e125f3a58ee081368a0eb01287ab9765129c31ec9791ef

So for the first increment we need to ADD to Basekey the increment:

```
80979b548fd8e99e65fccb96df1351e125f3a58ee081368a0eb01287ab9765129c31ec9791ef +
          035dc5d77b83d07b8feef18a81bd06d803b1ab9dcf25b6a6aed55f100000000000 =
___________________________________________________________________________________________
80979b548fdc47643d784f675aa340d2b0756295b884e835ac7f383e52463a71ac31ec9791ef
```
That number is the next Base58 Key:

L2JR1112tSVjxmT11118WFz4y7Pbs1t9rdEqiSxQBYUMPuLNSNgE

But remember in this case we omit all the BAse58 Encode decode part and work direcly with the Numbers

The next step is make the Double sha256('80979b548fdc47643d784f675aa340d2b0756295b884e835ac7f383e52463a71ac31')  and check if the first bytes match with "ec9791ef" those are binary numbers not strings...

Also we only need to do this when the first Byte is 0x80.

How to do that with a program? well it need to be coded.

**Comment by avtoblesk** [comment]
What initial combinations can take 5, K, L, the first 2 characters?

**Comment by avtoblesk** [comment]
Well, and if we know the Public Key, will you find it quickly with this? Here's the public key, tell me the whole search algorithm. 022391D6A5DC858B2E9E771D0CC5A43ADD6969E38C6F220E1CAE527BD6F2ADD47D. This is for example, and the wallet is empty, but I need understanding.

**Comment by albertobsd** [comment]
> What initial combinations can take 5, K, L, the first 2 characters. Is it possible to calculate, analyze?

As i Said, if you don't have the publickey is impossible with a computer, even thousand computers can't solve that, maybe some 500 High end GPU can solve that in some 4 months.

> tell me the whole search algorithm

I can't tell you the algorithm until i solve some one or two real case examples and i get my part of that.

> Well, and if we know the Public Key, will you find it quickly with this?

Yes with the publickey and the partial WIF i know how to calculate that.

> Here's the public key,  022391D6A5DC858B2E9E771D0CC5A43ADD6969E38C6F220E1CAE527BD6F2ADD47D. 

Privatekey: 7127e99d3d86f58673898afd22f15636c430178693203aa3cf60c3aaaaef292b
WIF: L11ft74TkKXutPKuKoz2xD5AnujeeU6Y38hqwQVW9mFegtxjwjpi

If you have a real case with publickey please send me an email or a telegram message.

**Comment by avtoblesk** [comment]
Here you are handsome! How can I contact you in Telegram if I need your help promptly?

**Comment by albertobsd** [comment]
search for mi nickname on telegram

**Comment by avtoblesk** [comment]
There is no public key from the real task that I am currently solving. There is a compressed address and there is a part of the key last 40-41 characters. Now I'm solving it with Fialka, splitting the range into 58 threads with initial values KAA-K9, L1A-L9A. If you know the possible initial 3-4 characters, you can reduce the search range to 7 characters and increase the number of parallel lines of the problem being solved. We also excluded possible combinations of 3 consecutive characters in the WIF key.
