### ISSUE TITLE
Public keys

### ISSUE THREAD

**Issue by n1k1tozzz** [albertobsd/keyhunt#163]
please tell me! what scripts or programs do you use to quickly add and subtract public keys for the xpoint function? and is there a script or a program to convert a private key into a public key?

**Comment by albertobsd** [comment]
Check mi other repositories:

keysubtracter
https://github.com/albertobsd/keysubtracter

ecctools
https://github.com/albertobsd/ecctools

**Comment by n1k1tozzz** [comment]
thanks
