### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by Georgi0817** [albertobsd/keyhunt#165]
when i try to compile with the "make" command it gives me this error
g++ -O3 -c oldbloom/bloom.cpp -o oldbloom.o
make: g++: Command not found
make: *** [Makefile:2: default] Error 127

what do i do

![image](https://user-images.githubusercontent.com/75530459/152040212-649b33a6-1bb9-49f1-b810-0d35dfb78ad7.png)

**Comment by Georgi0817** [comment]
its a windows ubuntu shell

**Comment by albertobsd** [comment]
Install build essentials
