### ISSUE TITLE
new feature partial address?

### ISSUE THREAD

**Issue by werdegars** [albertobsd/keyhunt#166]
i noticed keyhunt only search for full complete address
any plan to add partially search or partially match function?

let say looking for 1BFhrfTTZP3N

i wish keyhunt can scan using random without having a complete address

**Comment by albertobsd** [comment]
That is the vanity search: https://github.com/albertobsd/keyhunt#vanity-search it already works but there are other good tools to do that kind of search faster. Check the previous Link:

Regards!
