### ISSUE TITLE
Compressed Key

### ISSUE THREAD

**Issue by TemplarWorld** [albertobsd/keyhunt#168]
Just to ask,

So if I just want to use bsgs to use one **compressed** public key, I could use -l compress

 like ./keyhunt -bsgs -f tests/pubkeyfile.txt -b 120 -R -t 4 -l compress -q -S  ??

I ask because I see the compress and uncompress variable used in the other formulas

**Comment by albertobsd** [comment]
That option is only for address and rmd160 modes, for Bsgs that option don't do anything

**Comment by TemplarWorld** [comment]
Thank you Alberto,

Also, what is the difference between -B random and -R ?

**Comment by albertobsd** [comment]
no one, both of them trigger the same flag.
