### ISSUE TITLE
acentry":  transactions & db 4.7 blockchain copy. 

### ISSUE THREAD

**Issue by mikejnpc** [albertobsd/keyhunt#170]
Luis

Have you seen and delt with "acentry":  transactions?

Do you have blockchain db47 4.7 ? ... the current version is 48 4.8 and i cannot use it... 

Thank you.

**Comment by mikejnpc** [comment]
Hi Luis,

I will send you a email about it with examples okay? ...

**Comment by albertobsd** [comment]
Send it here

**Comment by mikejnpc** [comment]
i dont want it to be in public  - msg me on telegram then...  @mikejnpc

**Comment by albertobsd** [comment]
That is a pity.
