### ISSUE TITLE
New Modi for improving address search performance

### ISSUE THREAD

**Issue by MajMcCloud** [albertobsd/keyhunt#171]
Hey!

I had thought about 2 new modi for improving the already existing rmd160 performance.

Im not 100% sure on that, but rmd160 should be slower than sha256, isnt it ?

How would it be, to have a modi for getting the sha256 bruteforced from the rmd160 hash. And then skipping the rmd160 hashing and only checking for the sha256 one ?

So technically it should "just" generate a 32 byte random number (random sha256 hash), hashing it with rmd160 and compares if it matches. So we can skip that rmd160 hashing in the future for getting the "full way" from private key to rmd160.
Could be called (like sha256 instead of rmd160/address)

And the bruteforce one named like bruteSha256 or rmd2sha256

Would be interesting how many of these bruteforces would be possible.

Thanks!
Floh

**Comment by MajMcCloud** [comment]
Ah ok, i just thought that it could speed up things, but thats fine. Im not sure which part of the process takes which percentage of cpu time.

**Comment by albertobsd** [comment]
Yes surely it will speed up the things, but in that case use the xpoint method it only search for public key coincidence, without do any of the sha256, rmd160 prorcess.

**Comment by MajMcCloud** [comment]
Ok sure, to be honest, I havent really understand how that xpoint method works. Maybe thats why i didnt try it in the first place. 
Did you have some reference to read about how xpoint works ?

Thank you!
