### ISSUE TITLE
Can i check multiple ranges in a text file for matching address

### ISSUE THREAD

**Issue by Dr-Shams** [albertobsd/keyhunt#176]
hello AlbertoBSD

i am using this command for example for one small range to check
/keyhunt -t 8 -m address -f address.txt -r 3E8:7D0 -l compress
but if i got multiple ranges in a text file is there a way to feed them into the program like the address.txt  ???

and Also Keyhunt keeps Processing further even after the range is completed

**Comment by albertobsd** [comment]
There is no way to feed the range in that way, the only way is split the range your self and run the programs one by one in  one batch script or something similar.

The minimum range is 32 bits this is near 4 billion keys.
