### ISSUE TITLE
Question about using bloom filter or bloom file instead of text file

### ISSUE THREAD

**Issue by bigvito19** [albertobsd/keyhunt#178]
Is it possible to use a bloom filter or a bloom file instead of the text file? It would at least increase the speed because you wouldn't have to load the text file and iterate of the public keys or addresses.

**Comment by albertobsd** [comment]
Not yet

**Comment by albertobsd** [comment]
The lastest `development` branch have enabled the `-S` parameter to create, write the file and read the file based on the txt data.
