### ISSUE TITLE
Stride not work

### ISSUE THREAD

**Issue by Nemcd-com** [albertobsd/keyhunt#180]
Hello, Alberto!
Good soft, but option Stride not work

./keyhunt -t 24 -m xpoint -f /data/p120.pub -b 120 -n 1024000 -s 10 -I 1024000000000
[+] Version 0.2.211117 SSE Trick or treat ¡Beta!, developed by AlbertoBSD
[+] Threads : 24
[+] Mode xpoint
[+] Stats output every 10 seconds
[+] Stride : 1024000000000
[+] Opening file /data/p120.pub
[+] N = 0xfa000
[+] Bit Range 120
[+] -- from : 0x800000000000000000000000000000
[+] -- to   : 0x1000000000000000000000000000000
[+] Allocating memory for 1 elements: 0.00 MB
[+] Bloom filter for 1 elements.
[+] Loading data to the bloomfilter total: 0.00 MB
[+] Bloomfilter completed
[+] Sorting data ... done! 1 values were loaded and sorted
^Cse key: 80000000000000000000001bc56000

**Comment by Nemcd-com** [comment]
[+] Stride : 1024000000000
print Ok and not skip pkey

**Comment by albertobsd** [comment]
Yes there is an error in the Stride option, it is not working properly sorry for that, i will try to solve it ASAP.

Thanks for report it.
