### ISSUE TITLE
ARM64

### ISSUE THREAD

**Issue by MajMcCloud** [albertobsd/keyhunt#183]
Hey together,

does anybody tested this tool on ARM64? 
Does it work ?

Thank you
Warm regards
Florian

**Comment by dem10** [comment]
> Hey together,
> 
> does anybody tested this tool on ARM64? Does it work ?
> 
> Thank you Warm regards Florian

Only old versions(GMP) work on ARM. ARM is an architecture with a lot of unavailable instructions.

**Comment by pianist-coder** [comment]
Its not compile in termux
