### ISSUE TITLE
No bloom/bloom.c: when i try to make,...

### ISSUE THREAD

**Issue by bane77111** [albertobsd/keyhunt#186]
When i try to make file (ubuntu 22.04) i get this error :

gcc -O3 -c bloom/bloom.c -o bloom.o
cc1: fatal error: bloom/bloom.c: No such file or directory
compilation terminated.
make: *** [Makefile:2: default] Error 1

Any advice how to fix this?

Thanks in nadvance

**Comment by albertobsd** [comment]
That is OK, this repository doesn't have a bloom.c file only a bloom.cpp file looks like you are doing something extrange.

Please tell us what are you trying to do.

The best way to compile keyhunt is with the command `Make`

**Comment by bane77111** [comment]
I downloaded zip file then when try to compile,...     
I get this error: 

:~/keyhunt-master$ make 
gcc -O3 -c bloom/bloom.c -o bloom.o
cc1: fatal error: bloom/bloom.c: No such file or directory
compilation terminated.
make: *** [Makefile:2: default] Error 1

**Comment by albertobsd** [comment]
Well, I don't know where you download that zip, but I'm pretty sure that it was NOT from this repository.

Maybe you download it from another repository or from an old version.

Install git and clone the repository with the git clone command. If you don't know how to do that google it please.

**Comment by bane77111** [comment]
I did zip it from your repository but i guess there is different script?  Anyways but now when i clone and try to compile it with `make` i get different error:  

:~/keyhunt$ make
g++ -O3 -c oldbloom/bloom.cpp -o oldbloom.o
g++ -O3 -c bloom/bloom.cpp -o bloom.o
gcc -O3 -c base58/base58.c -o base58.o
gcc -O3 -c rmd160/rmd160.c -o rmd160.o
g++ -O3 -c sha3/sha3.c -o sha3.o
g++ -O3 -c sha3/keccak.c -o keccak.o
gcc -O3 -c xxhash/xxhash.c -o xxhash.o
g++ -O3 -c util.c -o util.o
g++ -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -c secp256k1/Int.cpp -o Int.o
g++: error: unrecognized command-line option \u2018-m64\u2019
g++: error: unrecognized command-line option \u2018-mssse3\u2019
make: *** [Makefile:10: default] Error 1

**Comment by albertobsd** [comment]
what is your hardware? looks like you are using an incompatible hardware. Keyhunt is currently not compatible with ARM

**Comment by bane77111** [comment]
Yes sorry, i use ARM, in should read older issues before,...
So again sorry to wasted your time and thanks for your help
