### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by sssergy** [albertobsd/keyhunt#187]
Good afternoon.
The program does not look for keys at the end of the range.
Screenshot example.

![image](https://user-images.githubusercontent.com/26333870/202148223-9449878f-c0eb-48c7-96f1-b011f4090b39.png)

**Comment by sssergy** [comment]
If you run it like this, then the search starts from the value that you specified as the end of the range.
The question is, how can this be fixed?
![image](https://user-images.githubusercontent.com/26333870/202150190-6732f297-335f-4653-b5d4-50cc58087750.png)

**Comment by albertobsd** [comment]
> Good afternoon. The program does not look for keys at the end of the range. Screenshot example.

Any number  greater than N will apply Modulo N, so that mean that those numbers loops again form 1 and above.


> If you run it like this, then the search starts from the value that you specified as the end of the range. The question is, how can this be fixed? 

if the End range is less than the start renge, those values are swapped:

![image](https://user-images.githubusercontent.com/17832765/202307148-95574662-03c1-4b46-8d10-816620ac1f1b.png)
