### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Chesterfield007** [albertobsd/keyhunt#19]
keyhunt.c: In function ‘main’:                                                                                          keyhunt.c:1025:45: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]                                                                                                 1025 |      fprintf(stderr,"[E] error bloom_init [%i]\n",i);                                                                 |                                            ~^     ~                                                                   |                                             |     |                                                                   |                                             int   uint64_t {aka long unsigned int}                                    |                                            %li                                                                  keyhunt.c:1031:63: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]                                                                                                 1031 |      fprintf(stderr,"[E] error bloom_init for 1000 elements [%i]\n",i);                                               |                                                              ~^     ~                                                 |                                                               |     |                                                 |                                                               int   uint64_t {aka long unsigned int}                  |                                                              %li                                                keyhunt.c:1062:41: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]                                                                                             1062 |   printf("[+] Allocating %.1f MB for %llu aMP Points\n",(float)(((uint64_t)(bsgs_aux*sizeof(struct Point)))/(uint64_t)1048576),bsgs_aux);                                                                                                     |                                      ~~~^                                                                                      ~~~~~~~~                                                                                                       |                                         |                                                                                      |                                                                                                              |                                         long long unsigned int                                                                 long unsigned int                                                                                              |                                      %lu                                                                        keyhunt.c:1138:41: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]                                                                            1138 |   printf("[+] Allocating %.2f MB for %llu bP Points\n",(float)((uint64_t)((uint64_t)bsgs_m2*(uint64_t)sizeof(struct bsgs_xvalue))/(uint64_t)1048576),bsgs_m2);                                                                                |                                      ~~~^                                                                                                            ~~~~~~~                                                                                  |                                         |                                                                                                            |                                                                                        |                                         long long unsigned int                                                                                       uint64_t {aka long unsigned int}                                                         |                                      %lu                                                                        keyhunt.c: In function ‘thread_process_bsgs’:                                                                           keyhunt.c:2227:35: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]                                                                                             2227 |   if(FLAGDEBUG ) printf("%u of %llu\n",bloom_counter,(uint64_t)(bsgs_aux*bsgs_point_number));                         |                                ~~~^                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                           |                                   |                  |                                                                |                                   |                  long unsigned int                                                |                                   long long unsigned int                                                              |                                %lu                                                                              keyhunt.c: In function ‘thread_process_bsgs_random’:                                                                    keyhunt.c:2374:35: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]                                                                                             2374 |   if(FLAGDEBUG ) printf("%u of %llu\n",bloom_counter,(uint64_t)(bsgs_aux*bsgs_point_number));                         |                                ~~~^                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                           |                                   |                  |                                                                |                                   |                  long unsigned int                                                |                                   long long unsigned int                                                              |                                %lu

**Comment by albertobsd** [comment]
Yes again the warnings i will clean it again. But there is no error you can run the program without worrying for those warnings.

**Comment by albertobsd** [comment]
Solved in  37920b0000fdcfab30de2cae7fdf7ad032b89e23
