### ISSUE TITLE
Make Problem

### ISSUE THREAD

**Issue by Opeael2** [albertobsd/keyhunt#193]
Hello
I have problem with make command...

root@ubuntulab:~/Dokumenty/keyhunt# make
g++ -O3 -c oldbloom/bloom.cpp -o oldbloom.o
g++ -O3 -c bloom/bloom.cpp -o bloom.o
gcc -O3 -c base58/base58.c -o base58.o
gcc -O3 -c rmd160/rmd160.c -o rmd160.o
g++ -O3 -c sha3/sha3.c -o sha3.o
g++ -O3 -c sha3/keccak.c -o keccak.o
gcc -O3 -c xxhash/xxhash.c -o xxhash.o
g++ -O3 -c util.c -o util.o
g++ -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -c secp256k1/Int.cpp -o Int.o
g++: error: unrecognized command-line option ‘-m64’
g++: error: unrecognized command-line option ‘-mssse3’
make: *** [Makefile:10: default] Error 1

my pc

root@ubuntulab:~/Dokumenty/keyhunt# lscpu
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  1
  On-line CPU(s) list:   0
Vendor ID:               ARM
  Model name:            Neoverse-N1
    Model:               1
    Thread(s) per core:  1
    Core(s) per cluster: 1
    Socket(s):           1
    Cluster(s):          1
    Stepping:            r3p1
    BogoMIPS:            50.00
    Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp 
                         asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; __user pointer sanitization
  Spectre v2:            Mitigation; CSV2, BHB
  Srbds:                 Not affected
  Tsx async abort:       Not affected

Can i run keyhunt on this VPS ?
How can i fix this ??

**Comment by dem10** [comment]
ARM architecture - not compile.

**Comment by geokomplo** [comment]
I tried it on Ubuntu with Parallels on M1 and I'm looking for a solution for the same error.

**Comment by sari777** [comment]
it is due to doublings in code. alberto also not known about this error. but hope so, he will help.
