### ISSUE TITLE
max best number of threads

### ISSUE THREAD

**Issue by mirameshs** [albertobsd/keyhunt#195]
Endless peace and blessings be upon you

how to find the best number on threads for use in -t command for every cpu model to use in
 .\keyhunt.exe -m bsgs -f tests\test120.txt -b 120 -t 40

Processor	Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz   2.30 GHz
Installed RAM	32.0 GB (31.8 GB usable)

for example for my cpu, i am using -t 40 on win 10 and this is very good. how to find max number of -t ?

**Comment by sari777** [comment]
it depends upon how many threads your system have. you have i7 10th generation. your maximum threads can be 256. but if you put 256 threads at once then no space will be available left for other system to run on windows. might be your system can crash. so use -t 128. but i suggest you should try bsgs mod with your ram.. with the 32gb of ram. you can get 77-78 peta keys per second.

**Comment by albertobsd** [comment]
The max number of threads it given by your processor specifications.
