### ISSUE TITLE
xpoint

### ISSUE THREAD

**Issue by An1an1** [albertobsd/keyhunt#196]
To run xpoint just add a file with public keys ? it finds X not all public keys ? It did not give out anything at startup
./keyhunt -m xpoint -f tests/substracted40.txt -n 65536 -t 4 -b 40
[+] Version 0.2.211117 SSE Trick or treat ¡Beta!, developed by AlbertoBSD
[+] Mode xpoint
[+] Threads : 4
[+] Opening file tests/substracted40.txt
[+] N = 0x10000
[+] Bit Range 40
[+] -- from : 0x8000000000
[+] -- to   : 0x10000000000
[+] Allocating memory for 22 elements: 0.00 MB
[+] Bloom filter for 22 elements.
[+] Loading data to the bloomfilter total: 0.00 MB
[+] Bloomfilter completed
[+] Sorting data ... done! 22 values were loaded and sorted
Base key: ffffff0000     ys in 37320 seconds: ~14 Mkeys/s (14723908 keys/s)
End

**Comment by albertobsd** [comment]
Can you share the `tests/substracted40.txt` content? Also tell what are the privatekey of that test file?

**Comment by An1an1** [comment]
here is the file content :

0330e3c7d2d298b6370d84a15e169bad94489f9241cc9250b3e62a713c4ff78adf
03b08250fcde6aa8a8ec299734ffd3109ac5dae860e5c8e1162c9b35baa0851b15
024b6e50dba5385c0e889333abc569ab96883f40bb9b02449dbc15c1d54f655d47
04a89bd906e2ded61588687b0ed3cf9f07467c6807f46b05cd7e99a3188c334c30ab3c41d7ad575901d8cef09373ae32aa21783624672735fea6082033550aff3a
02eeaf23fa6d33ddc668a8795cb4466a5a221a6fce324ccce712cd0031b9f210e6
04233ce2875bb110e2b8e0ce8e72e1bd27d335f038e07d61e810a81cb5d61a17696e481b385bee124e1a85094ac239cb6eee7d18c8d688f0c357a2fcf803463d02
04d4e2c18929473d8d39cb60832f7d8c77dd6d6b9358d8ee026c5a71d23204a523934bed43ecd911196355b18caff1a562fa985ad70e59945bebed62aa5e94295e
04e4a74813a167778a5d019cc0afbf3fa31406a591e24d540b96e9544afb7caa1ffdc0e650bc7fd7ad22338a14e7e0543f82cde88ac537a0e16b9288b63e0f65b2
02c0cda2ec26b169ca84dc1e5079054a109bb6ab9c10db2f73bc768a2e2ac31fe0
031d54c988e49e329fc0f2abebf599f80929e6c9198789a35a865cd204abbfaa4a
024af48f1cf91b5e7d633225856028edef08dff7de486fd2c8ba13eeb819716434
02cffba2e1e67b6414e4d1d5e0e20103c5567ae823e8c5667b5c81d09cd9bd69e0
047219d5a2a7c006c649b121f9d0afc1e22bd9e33e5c9b50ba3fc0e0e45489d0c12da118b906225c1fb5a84d7421b50bb8eff952ef773c3133b0db7d89559115d7
02147f10dff2cf29dce5d89744f6216ac133632bd199f577f8ca27c26ef1d4c8b0
03179b66326c19c306dab336f06557b4abffb8ab8274d8892d89faec3188aaba84
03c6e4b7e1a72186d03a27fc3da3d3da664c41a16f78afc31a9e9600dc65be46a3
034da28bec83bf9e5ed3e68179596baa617eaca3994fd3ad40128d51bb1b04cc44
031d54c988e49e329fc0f2abebf599f80929e6c9198789a35a865cd204abbfaa4a
02c0cda2ec26b169ca84dc1e5079054a109bb6ab9c10db2f73bc768a2e2ac31fe0
04e4a74813a167778a5d019cc0afbf3fa31406a591e24d540b96e9544afb7caa1ffdc0e650bc7fd7ad22338a14e7e0543f82cde88ac537a0e16b9288b63e0f65b2
04d4e2c18929473d8d39cb60832f7d8c77dd6d6b9358d8ee026c5a71d23204a523934bed43ecd911196355b18caff1a562fa985ad70e59945bebed62aa5e94295e
04233ce2875bb110e2b8e0ce8e72e1bd27d335f038e07d61e810a81cb5d61a17696e481b385bee124e1a85094ac239cb6eee7d18c8d688f0c357a2fcf803463d02

It does not find the value of X.

**Comment by albertobsd** [comment]
what are their privatekeys?

**Comment by An1an1** [comment]
I don't know. 

Other public keys I know private keys, value X also does not find, what could be the reason? 

15N1KY5ohztgCXtEe13BbGRk85x2FPgW8E
0445952f99b777cbd57a9d03eb5196dd97622668f5bb6f4190d882a6a3987b0a4474109a96cd8949056267f928994d2c36a4f239d2e0b54e87667a37fe19244020
31AFD65CAD430D276E3360B1C762808D1D051154724B6FC15ED978FA9D06B1C1

1J7TUsfVc58ao6qYjcUhzKW1LxxiZ57vCq
0277144138c5d2e090d6cf65c8fc984cce82c39d2923c4e106a27e3e6bb92de4ab
0ab51e7092866dadf86165ea0d70beb69086237a0e7f5a123d496d3d98e03617

15wGrVZpLjfg47ZG43hHuJtrfdQyNFYGNz
02506c7593c4e301c2729dbfc46b2959c7a92f6f20c672b6d0feff9c5b6a567cf9
16f2eaf0c267f036f926d0b1332c05f244427c65ce70a11b96842bf1a8221301

18vXv21kk8PfN4KRX5i19QvDRM855qheQ
024feffc562717f5780235775c775d79b278d74dad2ec8032c4a138c6177693c99
f655071bf6c91cc8ce7ec7c7ece17e3aa6027762dd9c59bfd0889fd1817fb566

19BRiDqZfYxU4K3DCWAfbh925cr7L4Q8ac
023a936a1116ee1d51eceef530daf519824a89a3985c9eaa1c58cfcd2c78830903
4c708ac0c78e07552f14544758031d2ad9d0baee702b5b163b97f1e7200c007b

16jLdtAxgXVwcG93MyPcNALXMCv3D6dyDB
040bdd9d6830145552673ac35edcf49c3ce8fd6434fe16a4566ddff96af9164b3ee69829271fd5b5f1b19c0c2a2adf192341786bfe03f5ce122c743cfcf6a0705f
0e57a34ee4cf2242bc331494981aa896e803c598cc4a0f890b2e85d6acb85f29

1C7zdTfnkzmr13HfA2vNm5SJYRK6nEKyq8
0378d430274f8c5ec1321338151e9f27f4c676a008bdf8638d07c0b6be9ab35c71
c4bbcb1fbec99d65bf59d85c8cb62ee2db963f0fe106f483d9afa73bd4e39a8a

1DnqpnCFiXqMhvRfdRzPcRao7yxyoeXgjf
0441924caf245ffe052cbb69df676e45875f6e78cf0bb7327f096c8b9122310211f6e2066e8d7d11ae2580b1abf286c474b64cbe64492af997ed41d00d89e3e4ae
1bad2815705c693b4df94badf0f757c601d841bff62c40f9546432034a4c29b7

13w4Hn1BJQM4bjZZgYtXpyp4cioiw29tKj
04c3211b119fd7b937556504043217d8263dff249263cdb5c48cf29990fd926bf340f2d558d51abf90d4917d928abcbf4fb4129cc6f85af248a3a713143d4060c0
d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592

1H6nTPQ8wqdQ3QFrGc1qy9r63acpTAkwvc
041d3a9f74e1c9ee86f74d9dbcc0a559184231cee933b866331eb258141f613520f599bf7dd66e264abb95c5ffac3a59dc3be0f504d2445d09adb6a479704b7750
5e6fa5565782e85f3e305c422388e687e4fc8c2e7c572748f57ff7a4d6ff736a

1Gwd5BQCDsFrEvokGkto945smazwEMKqdo
048cfd13673d984c653c4d81378116f38e48e1b4ae2baae1de7d7015431cd18766bdcdbaddcc05e276ffe6a597faaf98e800cb6f234c43f4c9d18cc9e5ff63a0a9
e9f852cd97283461e254da265a27d2bda07f245cb5f8a6ee622355fcec63eb8c

1E2Wgex1ZGfZ9gb4MBubJJ5bnABkk2pbZf
0464978b8a5e156a6a94ed21c8feaf5f13209c9bcd348960e0a4256ba90a8948951cb9931913f16a0bb11cb12804794bcfc3f77d1790e336fe87ef77847f97f9a1
68b1282b91de2c054c36629cb8dd447f12f096d3e3c587978dc2248444633483

113W1qXf6DsJFtqMnR53tqvLrVfjkjR7g5
04dc758dacd7907c070be0616bdceec22b20ad05e4b4166b33b6633f197b7899638e361bb9670b45dd90d2577fc6648dc4b7ab507c27bddb977d97ab59b2041a69
0e3630f0f829d93afd8569f7c50aaced3d930353db8468d8c42b58d7f5ce1fdb

1KRGyNbq2yM1vAXscib74Snp6AUuUHVi2g
04e1a9c85a1dc77e35835fd1a84f583e85c58578295f27577ed722df0bf1227a9cef895cadbb36cc714d3be6d1a15907beef09c3816f56f9247997f8a299b0bb4d
2f8586076db2559d3e72a43c4ae8a1f5957abb23ca4a1f46e380dd640536eedb

**Comment by albertobsd** [comment]
> I don't know.
> 
> Other public keys I know private keys, value X also does not find, what could be the reason?


You don't know what are you doing, you haven't checked what range are you scanning? If the privatekeys aren't in the range that you are scanning obviously they never will be found.


Please test with examples in the documentation.... And don't make me lose my time.

**Comment by An1an1** [comment]
Okay, thank you for your time.
