### ISSUE TITLE
interval Bug

### ISSUE THREAD

**Issue by makabress** [albertobsd/keyhunt#20]
Hi
if i add -b XXX or -r XXXX......:XXXX....... key hunter will start from first Bit , the intervale work correctly only in random mode -R
just reporting the bug

thank you

**Comment by makabress** [comment]
I know im not using - r and - b in the same timei use -r -R or -b - R and im using -m bsgs, il will try to build again in another location this new version 
Don't care about this problem im just doing tests 

Other questions i don't understand -k for exemple : i can collid with 63bit without - k
But with - k 400 exemple and 2000 tera key/s in 12 threat, i can't get collision

If possible to explain k sorry im noob

**Comment by makabress** [comment]
> I can't understand what for do we need -bsgs mode as we do not have any leaked public keys (neither for puzzle nor for any other address). :))

There is a lot of publickey from 2009 to 2011, but bsgs or kangaroo can search by single address at time , so bsgs for puzzles and for other xpoint or rmd160

**Comment by albertobsd** [comment]
> Other questions i don't understand -k for exemple : i can collid with 63bit without - k
> But with - k 400 exemple and 2000 tera key/s in 12 threat, i can't get collision

Hi, K is one factor tha make the bP table k times bigger but also make the aMP K times more less, the number of aMP points are the number of Operations needed to complete one Range N, by example the k = 400 makes the aMP number to 10486 instead of the default 4194304, this is 400 times less operations this will mean that is 400 times faster

I tested the puzzle 63 many times, keyhunt always hit it, im testing it again for k = 400, 

```
./keyhunt -m bsgs -f tests/63.pub -k 400 -b 63 -t 6 -q -p bPfile.bin
[+] Version 0.1.20210328
[+] Setting mode BSGS
[+] Setting k factor to 400
[+] Min range: 4000000000000000
[+] Max range: 7fffffffffffffff
[+] Setting 6 threads
[+] Set quiet thread output
[+] Opening file tests/63.pub
[+] Added 1 points from file
[+] Bit Range 63
[+] Setting N up to 17592588697600.
[+] Init 1st bloom filter for 1677721600 elements : 5751.00 MB
[+] Init 2nd bloom filter for 83886080 elements : 287.55 MB
[+] Allocating 0.3 MB for 10486 aMP Points
[+] Precalculating 10486 aMP points
[+] Allocating 1280.00 MB for 83886080 bP Points
[+] Reading 1677721600 bP points from file bPfile.bin
[+] processing 1677721600/1677721600 bP points : 100 %
[+] Sorting 83886080 elements
Total 809980376226201600 keys in 390 seconds: 2076872759554363 keys/s
```

With that speed i think it will take some 1 hour an some minutes in solve the puzzle.




> I can't understand what for do we need -bsgs mode as we do not have any leaked public keys (neither for puzzle nor for any other address). :))

how?

We have available the 120 bit puzzle key, also all other address with spent and most dormats have publickeys available.

 
> There is a lot of publickey from 2009 to 2011, but bsgs or kangaroo can search by single address at time , so bsgs for puzzles and for other xpoint or rmd160

Actually keyhunt can search many publickeys at the same time, i tested it with 20 000 Publickeys and i get some 200 Gigakeys/s.

If you are going to load more that 1 million of publickeys then is better use the xpoint mode.

best regards!

**Comment by mrantonion** [comment]
> > I can't understand what for do we need -bsgs mode as we do not have any leaked public keys (neither for puzzle nor for any other address). :))
> 
> There is a lot of publickey from 2009 to 2011, but bsgs or kangaroo can search by single address at time , so bsgs for puzzles and for other xpoint or rmd160

Thanks for explanation. I'm going to explore this issue...

**Comment by makabress** [comment]
Thank you Albertobsd

**Comment by albertobsd** [comment]
Solved in 35 minutes

```[+] processing 1677721600/1677721600 bP points : 100 %
[+] Sorting 83886080 elements
Total 4376684216188928000 keys in 2100 seconds: 2084135341042346 keys/s
[+] Thread 5 Key found privkey 0000000000000000000000000000000000000000000000007cce5efdaccf6808
[+] Publickey 0465ec2994b8cc0a20d40dd69edfe55ca32a54bcbbaa6b0ddcff36049301a545795a1b76ab01e9edd0de24157ceff77bcb0f615560b250b365a5d435873eaa4625
All points were found
```

**Comment by makabress** [comment]
> Solved in 35 minutes
> 
> ```
> [+] Sorting 83886080 elements
> Total 4376684216188928000 keys in 2100 seconds: 2084135341042346 keys/s
> [+] Thread 5 Key found privkey 0000000000000000000000000000000000000000000000007cce5efdaccf6808
> [+] Publickey 0465ec2994b8cc0a20d40dd69edfe55ca32a54bcbbaa6b0ddcff36049301a545795a1b76ab01e9edd0de24157ceff77bcb0f615560b250b365a5d435873eaa4625
> All points were found
> ```

ok i will try again

**Comment by makabress** [comment]
with the Version 0.1.20210328 no more problem im was using the 0.1.20210322

**Comment by albertobsd** [comment]
> with the Version 0.1.20210328 no more problem im was using the 0.1.20210322

Ok, I made the test again with that version, and keyhunt hit again look
```
./keyhunt -m bsgs -f tests/63.pub -k 400 -b 63 -t 6 -q -p bPfile.bin
[+] Version 0.1.20210322
[+] Setting mode BSGS
[+] Setting k factor to 400
[+] Min range: 4000000000000000
[+] Max range: 7fffffffffffffff
[+] Setting 6 threads
[+] Set quiet thread output
[+] Opening file tests/63.pub
[+] Added 1 points from file
[+] Bit Range 63
[+] Setting N up to 17592588697600.
[+] Init 1st bloom filter for 1677721600 elements : 5751.00 MB
[+] Init 2nd bloom filter for 83886080 elements : 287.00 MB
[+] Allocating 0.0 MB for 10486 aMP Points
[+] Precalculating 10486 aMP points
[+] Allocating 1280.00 MB for 83886080 bP Points
[+] Reading 1677721600 bP points from file bPfile.bin
[+] Sorting 83886080 elements
...
Total 4344208297453158400 keys in 2100 seconds: 2068670617834837 keys/s
[+] Thread 3 Key found privkey 0000000000000000000000000000000000000000000000007cce5efdaccf6808
[+] Publickey 0465ec2994b8cc0a20d40dd69edfe55ca32a54bcbbaa6b0ddcff36049301a545795a1b76ab01e9edd0de24157ceff77bcb0f615560b250b365a5d435873eaa4625
All points were found
```

**Comment by makabress** [comment]
ok sorry so i don't know where is my mistake
