### ISSUE TITLE
Prefix pubkey

### ISSUE THREAD

**Issue by Gusev39rus** [albertobsd/keyhunt#204]
Sometimes, when the discharge is lowered, the key goes to the end of the range 2 ^256. It would be very convenient if it was possible to search for "mirror" keys in parallel. i.e. that the prefix 02, 03 is ignored when searching. Thus, you can search for keys only in the first half of the entire range. Now we have to duplicate keys and change the prefix, which doubles the number of keys and, accordingly, halves the search speed.

**Comment by dem10** [comment]
The 02 prefix indicates an even y point and the 03 prefix indicates an odd y point. These are completely different keys giving different addresses. This does not in any way indicate the beginning or end of the range.

**Comment by Gusev39rus** [comment]
> The 02 prefix indicates an even y point and the 03 prefix indicates an odd y point. These are completely different keys giving different addresses. This does not in any way indicate the beginning or end of the range.

That's right, I'm talking about something else... If you ignore the prefix in the compressed public key when checking with the list of keys, you can simultaneously search for "mirror" keys. With different methods of reducing the bit depth, it may be that the key is shifted to 256 bits. If you ignore the prefix, you can simultaneously search in the range (for example): 0:FFFFFFFFFFFF and FFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD15E8CD0364142:0 In decimal representation, this is the range: 281474976710655......-281474976710655
It is better to make this function as an optional parameter.

**Comment by albertobsd** [comment]
This kind of behavior is already present in Xpoint. I will make some examples and fix in case that it not work properly
