### ISSUE TITLE
Hi!!! [E] Can't alloc memory for 

### ISSUE THREAD

**Issue by winnery2022** [albertobsd/keyhunt#205]
[+] Range
[+] -- from : 0x10f00000000000000000000000000000
[+] -- to   : 0x1fffffff000000000000000000000000
[+] Allocating memory for 2147483649 elements: 40960.00 MB
[E] Can't alloc memory for 2147483649 elements

**Comment by albertobsd** [comment]
Please paste the full output and command ...
 Information of your system.

I don't do support on windows yet

**Comment by winnery2022** [comment]
> Please paste the full output and command ... Information of your system.
> 
> I don't do support on windows yet

Thx fo answer) i up virtual memory and wait now. Hope its working.

**Comment by albertobsd** [comment]
In windows I recommended use WSL

**Comment by winnery2022** [comment]
How it>? its comand? WSL how me start it?

**Comment by winnery2022** [comment]
Its more good working on linux?
