### ISSUE TITLE
Use bloom filter

### ISSUE THREAD

**Issue by sssergy** [albertobsd/keyhunt#207]
In this code the public keys are loaded from a text file, can a bloom filter be used instead?

#include <fstream>
#include <string>
#include "bloom_filter.hpp"

// ...

int main(int argc, char* argv[]) {
  // ...

  // Create and configure the Bloom filter
  bloom_parameters parameters;
  parameters.projected_element_count = 1000000; // Adjust this value based on the number of keys you expect
  parameters.false_positive_probability = 0.1;  // Adjust this value based on the desired false positive rate
  parameters.compute_optimal_parameters();

  bloom_filter filter(parameters);

  // Load keys from a text file and insert them into the Bloom filter
  std::ifstream keyFile("keys.txt");
  std::string line;
  while (std::getline(keyFile, line)) {
    filter.insert(line);
  }
  keyFile.close();

  // ...

  // Now you can use the `filter.contains()` method to check if a key is in the filter
}

**Comment by albertobsd** [comment]
I will add the feature that the tables and bloom filters will be saved for address/rmd160 and xpoint. Then once that you already created your bloom filter the program will read it from file skipping the original file.

**Comment by sssergy** [comment]
Is it possible to use the bloom filter in bsgs mode to store many public keys, for example, ten or five tens of millions?

**Comment by albertobsd** [comment]
Bloom filter is a probabilistic data structure this means that is not made to store data, it is only used like an oracle.
For each Value that you want to check the bloom filter respond "May be in" or "Definitely Not"
Something like:
Was the hash of this data already processed by the bloom filter? 
"May be in" or "Definitely Not"

So the bloom filter can process any number of values all depends of your RAM it is some like 29 bits per item inside of the bloom filter.
