### ISSUE TITLE
Why can't you use -r and -R together?

### ISSUE THREAD

**Issue by Noname400** [albertobsd/keyhunt#21]
Why can't you use -r and -R together?
it would be effective and interesting for experiments

**Comment by albertobsd** [comment]
Well actually you can use, i update the code to use those both paramether together, but i dont edit the help.

maybe maybe, there is some issue with addresses but i need to do more test the few test that i done works well but maybe i'm not doing your test.

What mode are you using and what is your current line that you want to use?

best regards!

**Comment by dem10** [comment]
> Why can't you use -r and -R together?
> it would be effective and interesting for experiments

-r is the key range in hexadecimal format. example -r 8000: FFFF. -R is a random search. You can use these two flags together.

**Comment by Noname400** [comment]
Yes. you're right. thanks!
your work is great.
thank you for giving food for mind and work for hands!
