### ISSUE TITLE
Prefix x

### ISSUE THREAD

**Issue by Leonkleyn88** [albertobsd/keyhunt#211]
Hi alberto
I am a huge fan of your work. I actually wanted to know, as i am not so clued up in C language. In address prefix search we can search for prefix starting with 1.....etc. I wanted to know what i would need to change in code to search for pubkey prefix. In example...  Say i want to search pubkey X point starting with either 02 or 03 and then followed by X prefix. 02abc123 or 03abc123. Is it possible. Would sincerely appreciate your feedback.
Kind regards Leon

**Comment by albertobsd** [comment]
Well for that you need to change alot of code.

I wonder why this strange peticion comes? Is there something interesting about publickeys with some prefix?

If it is interesting and useful for something maybe i can add it.

Please make a good example of it.

thanks

**Comment by Leonkleyn88** [comment]
Can i write to you personally by email? My email address Leonkleynhans07@gmail.com i would like to explain to you what i am trying to achieve . Its interesting in its own way.

**Comment by albertobsd** [comment]
Reopen if you explain what is the objetive of this petition, answer this how this is useful for puzzles or key finding?
