### ISSUE TITLE
Upgrade keyhunt version

### ISSUE THREAD

**Issue by ovix** [albertobsd/keyhunt#215]
Alberto, please tell me how to upgrade to version 0.2.230507 Satoshi Quest without deleting the existing application. I use version 0.2.211031 Trick or treat ¡Beta! .
Thank you and I want to tell you that Keyhunt is the most powerful, I only reached 10 Petakeys/s/session because I always opened 6 consoles simultaneously, but this is the hardware limitation. It doesn't compare to anything else anyway. I invested in the graphics card because of other applications and in vain.

**Comment by ovix** [comment]
Timeout

**Comment by albertobsd** [comment]
```
git fetch
git pull
```

**Comment by ovix** [comment]
Thank you. I changed the name of the folder to KeyhuntOld and installed a new one.
