### ISSUE TITLE
keyhunt speed with different k

### ISSUE THREAD

**Issue by jpyao78** [albertobsd/keyhunt#218]
Hi,
About the keyhunt speed,  I tried the new version on an ubuntu with 128GB real mem.
when I use k=4096, it shows ~1 Ekey/s。
and i use k=8192, it still shows ~1 Ekey/s, I think here the number should be doubled?
thanks
-------------------k=4096--------------------------------------------
[+] Version 0.2.230519 Satoshi Quest, developed by AlbertoBSD
[+] Random mode
[+] K factor 4096
[+] Stats output every 10 seconds
[+] Threads : 28
[+] Quiet thread output
[+] Mode BSGS random
[+] Opening file tests/125.txt
[+] Added 1 points from file
[+] Bit Range 125
[+] -- from : 0x10000000000000000000000000000000
[+] -- to   : 0x20000000000000000000000000000000
[+] N = 0x100000000000
[+] Bloom filter for 17179869184 elements : 58890.60 MB
[+] Bloom filter for 536870912 elements : 1840.33 MB
[+] Bloom filter for 16777216 elements : 57.51 MB
[+] Allocating 256.00 MB for 16777216 bP Points
[+] Reading bloom filter from file keyhunt_bsgs_4_17179869184.blm .... Done!
[+] Reading bloom filter from file keyhunt_bsgs_6_536870912.blm .... Done!
[+] Reading bP Table from file keyhunt_bsgs_2_16777216.tbl .... Done!
[+] Reading bloom filter from file keyhunt_bsgs_7_16777216.blm .... Done!
[+] Total 5612535600316722184192 keys in 2940 seconds: ~1 Ekeys/s (1909025714393442919 keys/s)

-------------------k=8192--------------------------------------------
[+] Version 0.2.230519 Satoshi Quest, developed by AlbertoBSD
[+] Random mode
[+] K factor 8192
[+] Stats output every 10 seconds
[+] Threads : 28
[+] Quiet thread output
[+] Mode BSGS random
[+] Opening file tests/125.txt
[+] Added 1 points from file
[+] Bit Range 125
[+] -- from : 0x10000000000000000000000000000000
[+] -- to   : 0x20000000000000000000000000000000
[+] N = 0x100000000000
[+] Bloom filter for 34359738368 elements : 117781.20 MB
[+] Bloom filter for 1073741824 elements : 3680.66 MB
[+] Bloom filter for 33554432 elements : 115.02 MB
[+] Allocating 512.00 MB for 33554432 bP Points
[+] Reading bloom filter from file keyhunt_bsgs_4_34359738368.blm .... Done!
[+] Reading bloom filter from file keyhunt_bsgs_6_1073741824.blm .... Done!
[+] Reading bP Table from file keyhunt_bsgs_2_33554432.tbl .... Done!
[+] Reading bloom filter from file keyhunt_bsgs_7_33554432.blm .... Done!
[+] Total 765848340449049182208 keys in 420 seconds: ~1 Ekeys/s (1823448429640593290 keys/s)

**Comment by albertobsd** [comment]
Check this part of the README:

https://github.com/albertobsd/keyhunt#what-values-use-according-to-my-current-ram


Basically for values for k above 4096 you need to start changing the -n value also

```
64 GB -n 0x100000000000 -k 4096

128 GB -n 0x400000000000 -k 4096
```

**Comment by sssergy** [comment]
Hello .
Is there any difference with which parameters to note this  -n 0x1000000000000 -k 4096 or -n 0x10000000000000000 -k 32

> Check this part of the README:
> 
> https://github.com/albertobsd/keyhunt#what-values-use-according-to-my-current-ram
> 
> Basically for values for k above 4096 you need to start changing the -n value also
> 
> ```
> 64 GB -n 0x100000000000 -k 4096
> 
> 128 GB -n 0x400000000000 -k 4096
> ```

Hello .
Is there any difference with which parameters to run the program -n 0x1000000000000 -k 4096 or -n 0x100000000000000000 -k 32?

**Comment by albertobsd** [comment]
> Hello . Is there any difference with which parameters to run the program -n 0x1000000000000 -k 4096 or -n 0x100000000000000000 -k 32?

if you have doubts check the amount of size reserver for Main bloomfitler, yes they are different check, the first option use almost 256 GB and the other one use near two TeraBytes:

```
./keyhunt -m bsgs -f tests/125.txt -b 125 -q -s 10 -R -S -n 0x1000000000000 -k 4096 -t 8 -6
....
[+] Bloom filter for 68719476736 elements : 235562.39 MB
[+] Bloom filter for 2147483648 elements : 7361.33 MB
[+] Bloom filter for 67108864 elements : 230.04 MB
[+] Allocating 1024.00 MB for 67108864 bP Points


./keyhunt -m bsgs -f tests/125.txt -b 125 -q -s 10 -R -S -n 0x100000000000000000 -k 32 -t 8 -6
[+] Bloom filter for 549755813888 elements : 1884499.12 MB
[+] Bloom filter for 17179869184 elements : 58890.60 MB
[+] Bloom filter for 536870912 elements : 1840.33 MB
[+] Allocating 8192.00 MB for 536870912 bP Points
```

**Comment by jpyao78** [comment]
> Check this part of the README:
> 
> https://github.com/albertobsd/keyhunt#what-values-use-according-to-my-current-ram
> 
> Basically for values for k above 4096 you need to start changing the -n value also
> 
> ```
> 64 GB -n 0x100000000000 -k 4096
> 
> 128 GB -n 0x400000000000 -k 4096
> ```
-----------------------------
./keyhunt -m bsgs -f tests/125.txt -b 125 -R -s 10 -t 28 -S -q -n 0x400000000000  -k 4096
hi, it's 3Ekeys/s , thanks!

[+] Version 0.2.230519 Satoshi Quest, developed by AlbertoBSD
[+] Random mode
[+] Stats output every 10 seconds
[+] Threads : 28
[+] Quiet thread output
[+] K factor 4096
[+] Mode BSGS random
[+] Opening file tests/125.txt
[+] Added 1 points from file
[+] Bit Range 125
[+] -- from : 0x10000000000000000000000000000000
[+] -- to   : 0x20000000000000000000000000000000
[+] N = 0x400000000000
[+] Bloom filter for 34359738368 elements : 117781.20 MB
[+] Bloom filter for 1073741824 elements : 3680.66 MB
[+] Bloom filter for 33554432 elements : 115.02 MB
[+] Allocating 512.00 MB for 33554432 bP Points
[+] Reading bloom filter from file keyhunt_bsgs_4_34359738368.blm .... Done!
[+] Reading bloom filter from file keyhunt_bsgs_6_1073741824.blm .... Done!
[+] Reading bP Table from file keyhunt_bsgs_2_33554432.tbl .... Done!
[+] Reading bloom filter from file keyhunt_bsgs_7_33554432.blm .... Done!
[+] Total 37447008689120608256 keys in 10 seconds: ~3 Ekeys/s (37447008689120608
[+] Total 74856299731361988608 keys in 20 seconds: ~3 Ekeys/s (37428149865680994
[+] Total 112244339412861714432 keys in 30 seconds: ~3 Ekeys/s (3741477980428723
[+] Total 149618446083014262784 keys in 40 seconds: ~3 Ekeys/s (3740461152075356569 keys/s)

**Comment by sssergy** [comment]
> > Hello . Is there any difference with which parameters to run the program -n 0x1000000000000 -k 4096 or -n 0x100000000000000000 -k 32?
> 
> if you have doubts check the amount of size reserver for Main bloomfitler, yes they are different check, the first option use almost 256 GB and the other one use near two TeraBytes:
> 
> ```
> ./keyhunt -m bsgs -f tests/125.txt -b 125 -q -s 10 -R -S -n 0x1000000000000 -k 4096 -t 8 -6
> ....
> [+] Bloom filter for 68719476736 elements : 235562.39 MB
> [+] Bloom filter for 2147483648 elements : 7361.33 MB
> [+] Bloom filter for 67108864 elements : 230.04 MB
> [+] Allocating 1024.00 MB for 67108864 bP Points
> 
> 
> ./keyhunt -m bsgs -f tests/125.txt -b 125 -q -s 10 -R -S -n 0x100000000000000000 -k 32 -t 8 -6
> [+] Bloom filter for 549755813888 elements : 1884499.12 MB
> [+] Bloom filter for 17179869184 elements : 58890.60 MB
> [+] Bloom filter for 536870912 elements : 1840.33 MB
> [+] Allocating 8192.00 MB for 536870912 bP Points
> ```

I apologize for the confusion, I gave these figures for clarity. I meant that I can increase the value of n, but decrease k. You can, on the contrary, increase the value of k, but decrease the value of n and get the same amount of used RAM. So if there is any difference in these options, which one is better to use?

**Comment by albertobsd** [comment]
> I apologize for the confusion, I gave these figures for clarity. I meant that I can increase the value of n, but decrease k. You can, on the contrary, increase the value of k, but decrease the value of n and get the same amount of used RAM. So if there is any difference in these options, which one is better to use?

Ok, i got you point now...

There are some combinations of K and N that use the same amount of memory (same amount on each bloomfilter and table).

if the those values are the same the speed will be the same, and the result also will be the same,

The only difference is that bigger N with lower K (or not K default value 1) take a little more of time to update the speed counters, while the lower N with some big K update it more offten, but the average final speed will be the same.

**Comment by sssergy** [comment]
> > I apologize for the confusion, I gave these figures for clarity. I meant that I can increase the value of n, but decrease k. You can, on the contrary, increase the value of k, but decrease the value of n and get the same amount of used RAM. So if there is any difference in these options, which one is better to use?
> 
> Ok, i got you point now...
> 
> There are some combinations of K and N that use the same amount of memory (same amount on each bloomfilter and table).
> 
> if the those values are the same the speed will be the same, and the result also will be the same,
> 
> The only difference is that bigger N with lower K (or not K default value 1) take a little more of time to update the speed counters, while the lower N with some big K update it more offten, but the average final speed will be the same.

In order not to produce new topics, I'll ask here. How are addresses loaded into RAM? For example, after your keysubtracter program, I will get, for example, 5 million keys, but they are loaded very slowly, why is that?

**Comment by albertobsd** [comment]
input file reading is single thread, also the program need internally calculate the full key, if the input is compressed publickeys it need to calculate the Y value, maybe the program will be a little faster if you only provide uncompressed publickeys. Let me think if i can add some multithread to that part but the code is already very complex.

I will think in that.
