### ISSUE TITLE
Some issues about mode pub2rmd and rmd160 

### ISSUE THREAD

**Issue by Maxim-MDProjects** [albertobsd/keyhunt#219]
Hi, you did a great job. I am a fan of your programm. There are a couple of questions.
1. I am using the latest version. Why does it give 0 speed when running on command under Linux:
mx@NB-IDEA14are05:~/keyhunt$ ./keyhunt -m pub2rmd -f tests/puzzleswopublickey.txt -t 2 -q
[+] Version 0.2.230507 Satoshi Quest, developed by AlbertoBSD
[+] Mode pub2rmd
[+] Threads : 2
[+] Quiet thread output
[+] N = 0x100000000
[+] Range
[+] -- from : 0x1
[+] -- to   : 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141
[+] Allocating memory for 30 elements: 0.00 MB
[+] Bloom filter for 30 elements.
[+] Loading data to the bloomfilter total: 0.03 MB
[+] Sorting data ... done! 30 values were loaded and sorted
[+] Total 0 keys in 180 seconds: 0 keys/s

Also when starting this mode:
./keyhunt -m rmd160 -f tests/66.rmd -b 66 -l compress -R -q

it does not correctly show the speed and time counter, 2 hours have passed and the counter shows 180 seconds and the speed is 120 million (this is on a Rizen 7 4000 series laptop)

2. Is it possible to select a range in this mode (pub2rmd)? otherwise I'm looking for public keys for a 66-100 puzzle, and the program is looking for the entire range.

3. Сould you give a link where you can read x points? and it is not entirely clear how it works.

4. What search mode do you think is the most promising?

small addition, the error of updating the counter and speed occurs more often with the parameter -t> 1
 ./keyhunt -m rmd160 -f tests/66.rmd -b 66 -l compress -R -q -t 2

**Comment by albertobsd** [comment]
Mode pub2rmd will be delete from the program...

That mode have two times more the complexity of get the privatekey.

Get the private key is 1 of  2^256 or 1 of 2^160 depending of the mode

Get the publickey is 1 of 2^257
