### ISSUE TITLE
problem in range

### ISSUE THREAD

**Issue by mirameshs** [albertobsd/keyhunt#220]
I am scanning a little range. 

```
C:\Users\Administrator\Desktop\asd\keyhunt-win-main\keyhunt-win-main\CYGWIN>keyhunt.exe -m address -f addresses.txt -r 1111:2222
[+] Version 0.2.230519 Satoshi Quest, developed by AlbertoBSD
[+] Mode address
[+] Setting search for btc adddress
[+] N = 0x100000000
[+] Range
[+] -- from : 0x1111
[+] -- to   : 0x2222
[+] Allocating memory for 1 elements: 0.00 MB
[+] Bloom filter for 1 elements.
[+] Loading data to the bloomfilter total: 0.03 MB
[+] Sorting data ... done! 1 values were loaded and sorted
[+] Total 103898112 keys in 120 seconds: 865817 keys/s
```

the range is very small but the program does not tell me that finished the range.
please fix this

**Comment by albertobsd** [comment]
Add -n 1024 or -n 0x400

**Comment by winnery2022** [comment]
> I am scanning a little range.
> 
> ```
> C:\Users\Administrator\Desktop\asd\keyhunt-win-main\keyhunt-win-main\CYGWIN>keyhunt.exe -m address -f addresses.txt -r 1111:2222
> [+] Version 0.2.230519 Satoshi Quest, developed by AlbertoBSD
> [+] Mode address
> [+] Setting search for btc adddress
> [+] N = 0x100000000
> [+] Range
> [+] -- from : 0x1111
> [+] -- to   : 0x2222
> [+] Allocating memory for 1 elements: 0.00 MB
> [+] Bloom filter for 1 elements.
> [+] Loading data to the bloomfilter total: 0.03 MB
> [+] Sorting data ... done! 1 values were loaded and sorted
> [+] Total 103898112 keys in 120 seconds: 865817 keys/s
> ```
> 
> the range is very small but the program does not tell me that finished the range. please fix this

Hi its new version? How you start on windows? I can't start new version in windows 10 only server 2019

**Comment by winnery2022** [comment]
> https://github.com/XopMC/keyhunt-win/releases @winnery2022

Not working on windows 10 last version(

**Comment by albertobsd** [comment]
my program if for linux. if you guys want to run on windows without rewrite the program for windows properly... then those errors will come out.

**Comment by sssergy** [comment]
> Older versions are running. The latter does not work in any mode. Only worked on windows server 2019.

![image](https://github.com/albertobsd/keyhunt/assets/26333870/d0086e03-0d53-4aee-bc1f-6ebcb5f85dac)
all working

**Comment by winnery2022** [comment]
> > Older versions are running. The latter does not work in any mode. Only worked on windows server 2019.
> 
> ![image](https://user-images.githubusercontent.com/26333870/241737291-02f4410b-ea23-4265-8ce0-ee2d14b24973.png) all working ![image](https://user-images.githubusercontent.com/26333870/241737643-962b44b9-40d8-477f-b7e5-a7fad02547c1.png)

I have reinstalled Windows already. Older versions are running. New no (on 2 devices I can’t find the reason. I also have 2 laptops on Windows 10 pro
 (

**Comment by sssergy** [comment]
> > Older versions are running. The latter does not work in any mode. Only worked on windows server 2019.


> 
> I have reinstalled Windows already. Older versions are running. New no (on 2 devices I can’t find the reason. I also have 2 laptops on Windows 10 pro (
Maybe it shows some errors?

**Comment by winnery2022** [comment]
> Maybe it shows some errors?
> 
> > > Older versions are running. The latter does not work in any mode. Only worked on windows server 2019.
> 
> > I have reinstalled Windows already. Older versions are running. New no (on 2 devices I can’t find the reason. I also have 2 laptops on Windows 10 pro (

No any error. Old version working good. Not start.

**Comment by winnery2022** [comment]
> Maybe it shows some errors?
> 
> > > Older versions are running. The latter does not work in any mode. Only worked on windows server 2019.
> 
> > I have reinstalled Windows already. Older versions are running. New no (on 2 devices I can’t find the reason. I also have 2 laptops on Windows 10 pro (

C:\Program Files\Keyhunt19.05.23\MinGW>keyhunt.exe -m bsgs -r 1019a24dd2f1a9fbe76c8b4395810625:1020c49ba5e353f7ced916872b020c4a -f 1.txt -s 6 -l compress -t 2 -q -k 200 -M -S -6

**Comment by winnery2022** [comment]
> > Maybe it shows some errors?
> > > > Older versions are running. The latter does not work in any mode. Only worked on windows server 2019.
> > 
> > 
> > > I have reinstalled Windows already. Older versions are running. New no (on 2 devices I can’t find the reason. I also have 2 laptops on Windows 10 pro (
> 
> C:\Program Files\Keyhunt19.05.23\MinGW>keyhunt.exe -m bsgs -r 1019a24dd2f1a9fbe76c8b4395810625:1020c49ba5e353f7ced916872b020c4a -f 1.txt -s 6 -l compress -t 2 -q -k 200 -M -S -6

its old 


C:\Users\Winnery\Desktop\Version 0.2.211117 ¡Beta! (MinGW)>keyhunt.exe -m bsgs -r 1010624dd2f1a9fbe76c8b4395810625:10f0724dd2f1a9fbe76c8b4395810625 -f 147.txt -s 12 -l compress -t 4 -q -k 125 -M -S -R
[+] Version 0.2.211117 SSE Trick or treat ┬бBeta!, developed by AlbertoBSD
[+] Stats output every 12 seconds
[+] Search compress only
[+] Threads : 4
[+] Quiet thread output
[+] K factor 125
[+] Matrix screen
[+] Random mode
[+] Mode BSGS random
[+] Opening file 147.txt
[+] Added 251 points from file
[+] Range
[+] -- from : 0x1010624dd2f1a9fbe76c8b4395810625
[+] -- to   : 0x10f0724dd2f1a9fbe76c8b4395810625
[+] N = 0xffff2800000
[+] Bloom filter for 524288000 elements : 1797.20 MB
[+] Bloom filter for 16384000 elements : 56.16 MB
[+] Bloom filter for 512000 elements : 1.76 MB
[+] Allocating 7.00 MB for 512000 bP Points
[+] Reading bloom filter from file keyhunt_bsgs_4_524288000.blm .

**Comment by winnery2022** [comment]
So i don't know why not working new version on my 2 laptops

**Comment by winnery2022** [comment]
> Maybe it shows some errors?
> 
> > > Older versions are running. The latter does not work in any mode. Only worked on windows server 2019.
> 
> > I have reinstalled Windows already. Older versions are running. New no (on 2 devices I can’t find the reason. I also have 2 laptops on Windows 10 pro (

Cann you help?
