### ISSUE TITLE
cpu usage

### ISSUE THREAD

**Issue by mirameshs** [albertobsd/keyhunt#223]
hello
I am using keyhunt on Win 10 64bit
```
C:\Users\Administrator\Desktop\asd\keyhunt-win\CYGWIN>keyhunt -m address -f tests/66.txt -b 66 -l compress -R -q -s 10
[+] Version 0.2.230519 Satoshi Quest, developed by AlbertoBSD
[+] Mode address
[+] Search compress only
[+] Random mode
[+] Quiet thread output
[+] Stats output every 10 seconds
[+] Setting search for btc adddress
[+] N = 0x100000000
[+] Bit Range 66
[+] -- from : 0x20000000000000000
[+] -- to   : 0x40000000000000000
[+] Allocating memory for 1 elements: 0.00 MB
[+] Bloom filter for 1 elements.
[+] Loading data to the bloomfilter total: 0.03 MB
[+] Sorting data ... done! 1 values were loaded and sorted
[+] Total 225062912 keys in 80 seconds: ~2 Mkeys/s (2813286 keys/s)
```
my CPU usage is about 30.5
is this possible keyhunt to use all of my CPU 100% and increase the speed?
how is it possible?

**Comment by winnery2022** [comment]
> hello I am using keyhunt on Win 10 64bit
> 
> ```
> C:\Users\Administrator\Desktop\asd\keyhunt-win\CYGWIN>keyhunt -m address -f tests/66.txt -b 66 -l compress -R -q -s 10
> [+] Version 0.2.230519 Satoshi Quest, developed by AlbertoBSD
> [+] Mode address
> [+] Search compress only
> [+] Random mode
> [+] Quiet thread output
> [+] Stats output every 10 seconds
> [+] Setting search for btc adddress
> [+] N = 0x100000000
> [+] Bit Range 66
> [+] -- from : 0x20000000000000000
> [+] -- to   : 0x40000000000000000
> [+] Allocating memory for 1 elements: 0.00 MB
> [+] Bloom filter for 1 elements.
> [+] Loading data to the bloomfilter total: 0.03 MB
> [+] Sorting data ... done! 1 values were loaded and sorted
> [+] Total 225062912 keys in 80 seconds: ~2 Mkeys/s (2813286 keys/s)
> ```
> 
> my CPU usage is about 30.5 is this possible keyhunt to use all of my CPU 100% and increase the speed? how is it possible?

Try -t 100 or -t 5000 -n 1024

**Comment by albertobsd** [comment]
You don't setup your number of threads, please don't open an issue every time that you don't undertand how the tools works
