### ISSUE TITLE
Address vs rmd 160 mode

### ISSUE THREAD

**Issue by gitrub20** [albertobsd/keyhunt#225]
Hola Alberto, una consulta: ¿cual es la diferencia entre el modo address y rmd 160?. Tenía entendido que en rmd 160 obtenía mas velocidad, pero ahora con la ultima versión al comparar los dos metodos obtengo mejor performance en address. Ej: 
modo 160:
./keyhunt -m rmd160 -f tests/66.rmd -b 66 -l compress -R -q -t 4
[+] Total 7994802176 keys in 720 seconds: ~11 Mkeys/s (11103891 keys/s)

address: 
./keyhunt -m address -f tests/66.txt -b 66 -l compress -R -q -s 10 -t 4
[+] Total 1055014912 keys in 80 seconds: ~13 Mkeys/s (13187686 keys/s)

Por lo que veo está muy optimizado con respecto a la version anterior, lograba solo 2 mkeys en modo address y 6 mkeys en rmd 160. (con 4 threads igual)

**Comment by albertobsd** [comment]
He combinado los modos rmd160 y address en una misma función, la velocidad a largo plazo debe de ser la misma, el los primeros segundos la velocidad varía mucho debido al Random ya que algunos rangos activan más seguido los falsos positivos del bloom filter pero a largo plazo y con las mismas condiciones de ventilación, la velocidad debe de ser igual
