### ISSUE TITLE
 BSGS Server (Only linux)

### ISSUE THREAD

**Issue by domineaf** [albertobsd/keyhunt#226]
Greetings **albertobsd**, I see that you updated today, if it is not too much trouble I would like to know what this modification refers to, thank you.

**Comment by albertobsd** [comment]
Welll you always can see the difference between commits:

https://github.com/albertobsd/keyhunt/commit/2edbebf862fc66f1abb2609d6bbb68976834ee12

Maybe you will notice some new files :)

https://github.com/albertobsd/keyhunt/blob/main/BSGSD.md

Check it

**Comment by sssergy** [comment]
This works pretty slow. Is it possible to read public keys from a file, and set the range when starting the application?

**Comment by albertobsd** [comment]
> This works pretty slow. Is it possible to read public keys from a file, and set the range when starting the application?

What? is the same speed of keyhunt bsgs.

About read the public keys from file then USE keyhunt instead..

if you want to use the server in that way you need to write your own client in your prefered language...

**Comment by sssergy** [comment]
I meant delays between the client and the server.
There is another problem, with a large number of requests, RAM consumption increases.
At the start, 180GB out of 250 is occupied, after half an hour the system kills the application due to lack of RAM.

![image](https://github.com/albertobsd/keyhunt/assets/26333870/ab42518c-7fab-441c-ad79-97811cd92507)

**Comment by albertobsd** [comment]
> I meant delays between the client and the server. There is another problem, with a large number of requests, RAM consumption increases. At the start, 180GB out of 250 is occupied, after half an hour the system kills the application due to lack of RAM.

OK the delays between client and server shoulbe near 0 unless you are running some things manually.

What language is your client? The time between then end of a conection and the new one should be near to zero

About the RAM consumption increase let me check that is something that i can test, thank you to point me to that.

Regards!.

**Comment by sssergy** [comment]
> > I meant delays between the client and the server. There is another problem, with a large number of requests, RAM consumption increases. At the start, 180GB out of 250 is occupied, after half an hour the system kills the application due to lack of RAM.
> 
> OK the delays between client and server shoulbe near 0 unless you are running some things manually.
> 
> What language is your client? The time between then end of a conection and the new one should be near to zero
> 
> About the RAM consumption increase let me check that is something that i can test, thank you to point me to that.
> 
> Regards!.

`import socket



def send_request(pub_key, range_start, range_end):

    request_str = f"{pub_key} {range_start}:{range_end}"



    # Connect to the server

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    s.connect(('10.10.0.28', 8181))



    try:

        # Send the request

        s.sendall(request_str.encode())



        # Receive the response

        response = s.recv(1024)

        response_str = response.decode().strip()



        # Handle the response

        if response_str != "404 Not Found" and response_str != "400 Bad Request":

            # If the response is not an error message, it should be the private key

            print(f"The private key is: {response_str}")

            with open('found.txt', 'a') as f:

                f.write(f"Public key: {pub_key}, Private key: {response_str}\n")



    finally:

        # Always close the connection

        s.close()



# Read public keys from a file

with open('1test.txt', 'r') as f:

    lines = f.readlines()



# Extract public keys from lines and strip comments

public_keys = [line.split('#')[0].strip() for line in lines]



# Send a request for each public key

for pub_key in public_keys:

    send_request(pub_key, "1", "1FFFFFFFFFFFFFFFF")

`

The simplest version in python

**Comment by sssergy** [comment]
![image](https://github.com/albertobsd/keyhunt/assets/26333870/eff31a08-32d7-4015-90a4-92459d65dace)
![image](https://github.com/albertobsd/keyhunt/assets/26333870/21c55d4a-86ca-45f8-9b5e-58cc19edf936)
26788 keys tested, increased RAM consumption from 182GB to 250GB.

**Comment by albertobsd** [comment]
Thanks for sharing the client is ok.

I already checked what are the issue about the ram consumption, i will commit the changes in some three hours.

**Comment by albertobsd** [comment]
The update is already available.

**Comment by sssergy** [comment]
> The update is already available.

![image](https://github.com/albertobsd/keyhunt/assets/26333870/3e5803a9-978a-4055-9dd8-a36b8f0d47ec)
These messages after each key are clearly not needed))

**Comment by albertobsd** [comment]
Ok I will remove those in the next update, mean while you can comment those printf lines.

By the way, what about the memory consumption? It was fixed?

**Comment by sssergy** [comment]
> Ok I will remove those in the next update, mean while you can comment those printf lines.
> 
> By the way, what about the memory consumption? It was fixed?

Yes, no more memory leaks. The server is stable.

**Comment by sssergy** [comment]
Hello!
I'll ask again here
The server code was loading a list of keys from a file, could you return this function?

> Ok I will remove those in the next update, mean while you can comment those printf lines.
> 
> By the way, what about the memory consumption? It was fixed?

Hello!
I'll ask again here) Together with the correction for a memory leak, you removed part of the commented out code.
The server code was loading a list of keys from a file, could you return this function? I didn't save the old version.
