### ISSUE TITLE
One or many points in mode BSGS

### ISSUE THREAD

**Issue by Doktor1024** [albertobsd/keyhunt#230]
Good afternoon! Please tell me so that I understand! What does the program do with the cars that I have in the list in bags mode ? What is the difference if there is 1 public key or 50 keys in the list? Does the program use all the keys to build a bloom? or does the program use keys only for comparison?

**Comment by albertobsd** [comment]
The bloom is generated independently of the keys values, number or range.

The keys are only used to make the calculations and Comparations corresponding to the BSGS algorithm.

The speed of the whole process is divided between the number of keys on your file, one key give you the max speed for your hardware.

Check https://andrea.corbellini.name/2015/06/08/elliptic-curve-cryptography-breaking-security-and-a-comparison-with-rsa/

**Comment by Doktor1024** [comment]
So bloom is always the same, we don't influence him in any way? It can't always be the same - then we wouldn't create it different every time - it would be constant for all occasions) Excuse me

**Comment by Doktor1024** [comment]
> Цветение генерируется независимо от значений ключей, их количества или диапазона.
> 
> Ключи используются только для выполнения вычислений и сравнений, соответствующих алгоритму BSGS.
> 
> Скорость всего процесса делится между количеством клавиш в вашем файле, одна клавиша дает вам максимальную скорость для вашего оборудования.
> 
> Проверить [https://andrea.corbellini.name/2015/06/08/elliptic-curve-cryptography-breaking-security-and-a-comparison-with-rsa/ ](https://andrea.corbellini.name/2015/06/08/elliptic-curve-cryptography-breaking-security-and-a-comparison-with-rsa/)

Bloom - has some point from which he starts? he can't start from nothing, can he? If the range and the starting point from which bloom starts are not important for bloom, it turns out that we use the same bloom on any range - with the same chances?
