### ISSUE TITLE
The bloom file it always start from publickey 1 to X where X is a value calculated from the current values of N and K, -n and -k

### ISSUE THREAD

**Issue by Doktor1024** [albertobsd/keyhunt#231]
Good afternoon again!
Alberto, we really appreciate your work and what you do! That's why I ask questions that I can't answer myself - I'm not a brilliant mathematician like you!
 I have the same question - I just want to understand the difference - in the work of Keyhant!
 In the program manual, you say - no need to download more keys than 100 1000 - in BSGS mode! I realized that this affects the speed and output of statistics!
 Also you say - ...The bloom file always starts with publickey 1 by X, where X is the value calculated from the current values of N and K, -n and -k respectively!
 Please explain - if I upload 100 or 1000 keys - do all these keys work in creating bloom? or only 1 out of 100 1000? or are these 100 1000 involved in the search process?
please explain - what happens if there is only 1 key? and what happens if there are 100 keys? I don't mean speed - I mean the participation of these keys in the process!

I'm sorry for the trouble
With respect to you

Doctor

**Comment by albertobsd** [comment]
Let Me repeat it AGAIN, for mode `bsgs` the Bloom filter IS INDEPENDENTLY of your input file.
