### ISSUE TITLE
Output of matches to a text file

### ISSUE THREAD

**Issue by Musashih** [albertobsd/keyhunt#238]
Hello! Again, I didn't find a command to write matches to a text file, is there such a command?

**Comment by Musashih** [comment]
Okay, thanks

**Comment by marissia** [comment]
sorry. what about vanity addresses? it doesnt save in directory, LAptop can close any time and I will lost all data, no any file, just print on terminal. it possible to fix?

**Comment by albertobsd** [comment]
> sorry. what about vanity addresses? it doesnt save in directory, LAptop can close any time and I will lost all data, no any file, just print on terminal. it possible to fix?

Vanity are saved in the `VANITYKEYFOUND.txt` file

**Comment by marissia** [comment]
doesnt save  I swear, directory empty, if key found I see file, but vanitykeys no,,,

**Comment by albertobsd** [comment]
I guess that you don't have the privilegies to write in that directory... 

Please learn about chmod and chown. And NEVER run keyhunt as the root user or with sudo

**Comment by marissia** [comment]
I try by command  > keys.txt  it works , but asks privilegies, added sudo chmod -R 777 keys.txt, only this way success.

**Comment by marissia** [comment]
can you give me command please how i can open all directories for writing, tired to add every time with new file, windows-ubuntu

**Comment by albertobsd** [comment]
No i can't I am not here to teach you how to use linux, search a good course for it and don't use this Issue section to ask those basic things
