### ISSUE TITLE
Make windows

### ISSUE THREAD

**Issue by Noname400** [albertobsd/keyhunt#24]
after editing the Makefile, the build was successful.
thanks for the windows version.
but the assembly behaves strangely at work.
1) run (./keyhunt -m rmd160 -f tests / 1to32.rmd -r 1: FFFFFFFF -l compress)
2) the program finds 22 addresses and stops.
3) run (./keyhunt -m rmd160 -f tests / 64.rmd -b 64 -l compress -R)
4) the program does not display anything, exits
5) this behavior in all modes (address, rmd160)

**Comment by Noname400** [comment]
1.in the first case, I used the assembly win-builds-1.5.0.exe (compiles only with -std = c99. But works partially. Description above)
ran tests with standard build mingw-w64 (compiled as is in Makefile) but doesn't work at all. screen below.
![image](https://user-images.githubusercontent.com/74019756/113103377-a597ee00-9218-11eb-9f27-89303d5a87b2.png)

**Comment by chawyehsu** [comment]
I guess win-builds is too old to work properly, it stays at GCC 4.x which released 7 years ago. Can you install [MSYS2](https://www.msys2.org/) and try to build with the newer version of GCC and its libs?

**Comment by Noname400** [comment]
of course. I'll do it now.

**Comment by Noname400** [comment]
Yes. it really works. the speed is higher.
I continue to test.
instruction:
1.install MSYS2
2.install additional packages (pacman -S --needed base-devel mingw-w64-x86_64-toolchain)
3.Go to the program directory
4. ./Make
5. copy the libraries to the directory with the program (libgmp-10.dll, libwinpthread-1.dll)

**Comment by chawyehsu** [comment]
to avoid step 5, you can make static link binaries, don't forget to install gmp package

**Comment by Noname400** [comment]
Replase string Makefile
gcc -Wl,-Bstatic -o keyhunt keyhunt.o base58.o rmd160.o sha256.o custombloom.o bloom.o xxhash.o -lgmp -lm -lpthread
to
gcc -o keyhunt keyhunt.o base58.o rmd160.o sha256.o custombloom.o bloom.o xxhash.o -lgmp -lm -lpthread

> to avoid step 5, you can make static link binaries, don't forget to install gmp package

thanks.

**Comment by albertobsd** [comment]
I wil add that line but over the seccion `windows` just to do `make windows` instead of just `make`. I will notify you guys when the change  will be done

regards!

**Comment by studyroom1** [comment]
cut this **** please be kind and post exe file , i am trying from 10 days

**Comment by studyroom1** [comment]
@albertobsd when you will do this

**Comment by ndamofli** [comment]
Can someone help the rest of us and show the updated makefile and keyhunt.cpp for windows compilation? I am getting so many errors and don't know how to begin.
