### ISSUE TITLE
Can keyhunt solve for multiple different public keys?

### ISSUE THREAD

**Issue by FeatureSpitter** [albertobsd/keyhunt#241]
If I have multiple public keys in the .pub file (one per row), will it search the 2^256 key space for any private key solving for any of those multiple public keys?

Gracias!

**Comment by albertobsd** [comment]
You can having any number of keys in the file, but I don't think that be feasible find one in our timeline.

**Comment by FeatureSpitter** [comment]
It is possible, randomly, by chance: https://lbc.cryptoguru.org/trophies
