### ISSUE TITLE
vanity generate wrong  private key not in range 39eb851eb851ec000:40000000000000000

### ISSUE THREAD

**Issue by djemilbakhti** [albertobsd/keyhunt#247]
./keyhunt -m  vanity -l compress  -t 8 -B sequential -r 39eb851eb851ec000:40000000000000000 -v 13zb1hQ
[+] Version 0.2.230519 Satoshi Quest, developed by AlbertoBSD
[+] Mode vanity
[+] Search compress only
[+] Threads : 8
[+] Added Vanity search : 13zb1hQ
[+] N = 0x100000000
[+] Range 
[+] -- from : 0x39eb851eb851ec000
[+] -- to   : 0x40000000000000000
[+] Bloom filter for 1 elements.
[+] Loading data to the bloomfilter total: 0.03 MB
Base key: 39eb851f2851ec000     
Vanity Private Key: 39eb851ec861f298a
pubkey: 03c278658e5d1731d0407eaa6de30a875d40f1c70da4556b4e0b7c9831aa1778e2
Address 13zb1hQ57FnFr7MFzcLceFt3oRczbJhKaQ
rmd160 20d45a6a5085bcd8620c67c74f662b7bb0c66dd1
[+] Total 23138977792 keys in 810 seconds: ~28 Mkeys/s (28566639 keys/s)
Vanity Private Key: 39eb851eedd4d5c48
pubkey: 03f2079e99018f63e51cb560697c6d9edecb386407c7cea56c14bc84bcaca3ffaa
Address 13zb1hQZxWRUsatXYBESBxBJicVc11SvuZ
rmd160 20d45a6a7439a5df44f4444380645e88a70f663d
[+] Total 24693708800 keys in 870 seconds: ~28 Mkeys/s (28383573 keys/s)
Vanity Private Key: 39eb851eee26befa5
pubkey: 026d9f0a84b5302c08fbd957c408abc5109bf7dc99154b172d32adfe8423027cce
Address 13zb1hQYAKpARkW45b3NLyJ9HNHxz4YuNG
rmd160 20d45a6a7200902c33cb326483cb53a58dc64b63
[+] Total 33409474560 keys in 1200 seconds: ~27 Mkeys/s (27841228 keys/s)
Vanity Private Key: fffffffffffffffffffffffffffffffebaaedce6af48a038211a0ca0cb82cd5a
pubkey: 02a2b2de152f19bb8f3e2af06fe7ae7e5d641d5f24b1a9b503905dfbbb10be9ce6
Address 13zb1hQuNbSymKhfRyLfQRKmqezWCVDkHA
rmd160 20d45a6a8c40bd9c60359c13ebb1160fe8ffff1d
[+] Total 44711376896 keys in 1620 seconds: ~27 Mkeys/s (27599615 keys/s)
Vanity Private Key: fffffffffffffffffffffffffffffffebaaedce6af48a038211a0c9ea102fcd1
pubkey: 03a87d58aa53b91c7f2bd2b2fdfa2d57c6cd5a7967f896d1bcc31041bfc80bd2b7
Address 13zb1hQDZazWrSKskKXo1BBR11oDksh2en
rmd160 20d45a6a5afc1ab127f79ae61267d55c25b91696

**Comment by albertobsd** [comment]
Compress search have some bug/feature... it search on both sides of the curve, there is no another way to do that, any other way to avoid to search in both sides of the curve lead to a decrement on speed.

To solve your issue search FOR A BIGGER PREFIX STRING..... use:

`-v 13zb1hQbWVsc2S7ZTZ`

Regards!
