### ISSUE TITLE
BSGS Speed

### ISSUE THREAD

**Issue by mr-fahrenheit-repo** [albertobsd/keyhunt#252]
Is it possible to reach quetta keys/ second?

**Comment by mr-fahrenheit-repo** [comment]
Is that really possible? So the speed doesn't depends on cpu cores? Can you show some math for that? 

Sorry, i just really curious XD

**Comment by mr-fahrenheit-repo** [comment]
Oh wow thanks for the info man. One more, is there any reason for using intel xeon cpu?

**Comment by albertobsd** [comment]
> Is it possible to reach quetta keys/ second?

Sorry but is not possible to get that speed

**Comment by sssergy** [comment]
> if you want to use a higher volume of ram, it is impossible to install them on PC. Almost the PC's RAM capacity is about 128 GB in maximum . so you should systems u can install more ram. it is often a server and servers use Xeon in most cases. there is another reason and it is related to Xeon architecture. server cpus have higher bandwidth to process data.

It's about optimizing for Intel processors. I tried to run on amd 7763, and even xenon 8280 bypass it in speed. Although AMD is a generation higher.
