### ISSUE TITLE
Difference of speed between version 0.1.20210322  and 0.1.20210330

### ISSUE THREAD

**Issue by albertobsd** [albertobsd/keyhunt#26]
Hi everyone, some user report this decrement of speed with K = 1450

```
Version 0.1.20210322  Total 5283603588684185600 keys in 600 seconds: 8 806 005 981 140 309 keys/s
Version 0.1.20210330  Total 3282812546108620800 keys in 600 seconds: 5 471 354 243 514 368 keys/s
```
I do similar test with K = 128 without any difference but i will rerun that test again with a bigger K

Anyone have that issue too?

![9fecfe97-a1dd-432b-95d3-36b66585a6e3](https://user-images.githubusercontent.com/17832765/113100655-e7914780-91b8-11eb-9510-f323ffa77f93.jpg)

![02569dc3-dd6a-44ed-80fe-6ac1da92fd53](https://user-images.githubusercontent.com/17832765/113100661-e9f3a180-91b8-11eb-9874-0be13b373d67.jpg)

**Comment by albertobsd** [comment]
Thinking in this, there are a few changes between those versions.

- I remove the hash funtion from the custombloom filter for mode bsgs.

In theory removing the hash funtion is Good speed improvement, the actual X value of the Points in the curve always is a seemingly random value, hash this value is some redundant. But if the distribution is skewed then it can affect to the bloom filter check result leading  it in more false positive results this will be a decrement. 

I will test the collision factor for both, hashing the values and not hashing it.


I correct to varible from `unsignet int` to `uint64_t` 
This change CANT be undone because some users use the bloom filter with more than 4 GB of data, then if we keep this variable like `unsigned int` then this will keep the bloom filter useless, that is way this variable neet to be a 64 bits variable.

This code have some comment from the original autor:

```
  uint64_t byte = bit >> 3;
  uint8_t c = buf[byte];        // expensive memory access
```

I need to check if the perfomance can be affected by changin the variable type.

best regards!

**Comment by dolaor** [comment]
How to get a link for these versions because I can't find them on your repo? I will check.

**Comment by dolaor** [comment]
I did not clone the code with git so I can't get back to these versions.

**Comment by dolaor** [comment]
I have tested with -k 3400 the versions 0.1.20210322 and 0.1.20210331 (not the version 0.1.20210330) and I did not see any differences at all.

**Comment by albertobsd** [comment]
Its ok, not problem the drop of perfomance happen in the 0.1.20210330, but i already solve this bug, in the last development version.
