### ISSUE TITLE
Why -r 1:ff does not work as expected?

### ISSUE THREAD

**Issue by xiongnuren** [albertobsd/keyhunt#264]
I'm trying to understand how -r works by testing -r 1:ff but the search doesn't stop on ff.
./keyhunt -m address -f tests/1to32.txt -r 1:ff

Anyone can give a hint?

**Comment by albertobsd** [comment]
Because that range is very small compared with the defaul N value (2^32) for address the range should be 2^32 per thread

try to reduce N to at least 2^24, but not less than 1024

i mean the next command.

```
./keyhunt -m address -f tests/1to32.txt -r 1:1000001 -n 0x1000000 
```

do you want less ?

```
./keyhunt -m address -f tests/1to32.txt -r 1:10001 -n 0x10000 
```

**Comment by xiongnuren** [comment]
Thanks. That solved my issue.

**Comment by xiongnuren** [comment]
Closed.
