### ISSUE TITLE
bPfile

### ISSUE THREAD

**Issue by Noname400** [albertobsd/keyhunt#27]
what are the parameters for 64GB memory
he always puts me 1410065408

PS **> .\bPfile.exe 10000000000 bPfile.bin
[+] precalculating 1410065408 bP elements in file bPfile.bin

**Comment by dolaor** [comment]
./bPfile 14260633600 bPfile.bin
./keyhunt -m bsgs -f 120.txt -b 120 -k 3400 -t 8 -p ./bPfile.bin -R -q

It should use at the end around 62GB memory

**Comment by albertobsd** [comment]
I need to add that table to the readme
