### ISSUE TITLE
[question] with -b 256, are the keys sorted randomly or in order?

### ISSUE THREAD

**Issue by MrJorman** [albertobsd/keyhunt#272]
if I specify range 256 (-b 256) are the private keys sorted randomly or in order?

It’s just that if I specified -b 66, the keys were constantly sorted in order without randomness.

**Comment by MrJorman** [comment]
example 
please tell me, are my keys sorted randomly or in order?
![image](https://github.com/albertobsd/keyhunt/assets/55187962/f4214901-603f-47cb-9866-a25ef9bf8b37)

**Comment by albertobsd** [comment]
Please read the document and command help

```
./keyhunt -h
```

The option for random is `-R`

**Comment by woodand0912** [comment]
### ### _**你好，请问这个地址文件那里下载的？我的文件有几千万个地址，但是显示Ommiting**_ invalid line
