### ISSUE TITLE
Help me get a private key

### ISSUE THREAD

**Issue by MrJorman** [albertobsd/keyhunt#275]
Please tell me.
What steps need to be taken to get a private key? Look, please, I got a Hit! But I don’t know how to get the private key, I even read the article, but I still don’t understand. If there are kind people here who are ready to help, please tell me and teach me. Thank you!

```
Private Key: d2c55
pubkey: 033c4a45cbd643ff97d77f41ea37e843648d50fd894b864b0d52febc62f6454f7c
Address 1HsMJxNiV7TLxmoF6uJNkydxPFDog4NQum
rmd160 b907c3a2a3b27789dfb509b730dd47703c272868
```

**Comment by albertobsd** [comment]
Listen everybody, this is is the kind of dummy question that I usually handle everyday I get some dozens of them daily, I am not going to keep replying them in telegram, email or here.  I am just going to block/close/ignore them.
