### ISSUE TITLE
speed is not real ?

### ISSUE THREAD

**Issue by Haniamin90** [albertobsd/keyhunt#276]
![image](https://github.com/albertobsd/keyhunt/assets/107732507/eda8414a-e576-4574-9686-c45b7cdf4d62)

it should have found the key at 12,121,633,238,354,651,240

for the pubkey: 0230210c23b1a047bc9bdbb13448e67deddc108946de6de639bcc75d47c0216b1b

Privkey 000000000000000000000000000000000000000000000001a838b13505b26867
Start key 0000000000000000000000000000000000000000000000010000000000000000
Stop key 000000000000000000000000000000000000000000000001ffffffffffffffff

The number of keys in the range 
from 0x10000000000000000 
to 0x1A838B13505B26867 
is 12,121,633,238,354,651,240

The number of keys in the range 
from 0x10000000000000000 
to 0x20000000000000000
is 18,446,744,073,709,551,617.

am i missing something ?

**Comment by albertobsd** [comment]
Can you write the exact command that you use? Maybe a full screenshot?

**Comment by Haniamin90** [comment]
commad : -m bsgs -f 65.txt -t 32 -k 64 -l compress -b 65 -q

**Comment by albertobsd** [comment]
Thank you well yes i just checked it, and something is not adding well in the final counter i am going to debug it later, but in any case the case KEY should be found any second form your screenshot look:

<img width="767" alt="image" src="https://github.com/albertobsd/keyhunt/assets/17832765/cd880bb7-0827-4253-8e1d-7497802d86fb">

if you see my speed: `8338670122555340` keys/s

```
>>> 0x1a838b13505b26867 / 83386701225553404
366.5857608322883
>>> 0x1a838b13505b26867 / 83386701225553404 / 60
6.109762680538139
```

That should be > 6 Minutes and the program found it in 4m53.594s

I am going to check what is happening with the speed counter

**Comment by Haniamin90** [comment]
Yes it found the key at around 25.. i forgot to take screenshot. thanks for the amazing work, i wish you split the code into functions to make it easier to understand and optimize, i will try to contribute
