### ISSUE TITLE
Hit puzzle 130 

### ISSUE THREAD

**Issue by winnery2022** [albertobsd/keyhunt#277]
Hi alberto.

We can hit some whith this?

C:\Users\win>C:\Users\win\Desktop\ecctools\keymath.exe

**Comment by sssergy** [comment]
It’s a little unclear what you wanted to say by this, since some of the numbers are closed.

**Comment by winnery2022** [comment]
> It’s a little unclear what you wanted to say by this, since some of the numbers are closed.

I know Alberto will understand this. I can’t put everything out there for everyone to see because there’s just one movement missing for the full formula. Lust number of keys is not xxx

**Comment by sssergy** [comment]
> > It’s a little unclear what you wanted to say by this, since some of the numbers are closed.
> 
> I know Alberto will understand this. I can’t put everything out there for everyone to see because there’s just one movement missing for the full formula. Lust number of keys is not xxx

Just explain what you want to convey to Alberto? What's the point?
Do you use only keymath, or also keysubtracter?

**Comment by winnery2022** [comment]
I use two programs. My total file weighs a lot, about 400,000 mb. An intersection with half a key is possible here.

**Comment by winnery2022** [comment]
I use two programs. My total file weighs a lot, about 400,000 mb. An intersection with half a key is possible here.

**Comment by sssergy** [comment]
> I use two programs. My total file weighs a lot, about 400,000 mb. An intersection with half a key is possible here.

Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.

**Comment by winnery2022** [comment]
> Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.

An even key is very easy to check.

**Comment by Gusev39rus** [comment]
> > It’s a little unclear what you wanted to say by this, since some of the numbers are closed.
> 
> I know Alberto will understand this. I can’t put everything out there for everyone to see because there’s just one movement missing for the full formula. Lust number of keys is not xxx

to crack all the keys, there is also only one step missing... determine the even key or not. )))

**Comment by sssergy** [comment]
> > Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.
> 
> An even key is very easy to check.

How do you imagine it? After all, we cannot check the result of division, whether it is correct or not.

**Comment by Gusev39rus** [comment]
> > Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.
> 
> An even key is very easy to check.

these words are followed by a ban))

**Comment by winnery2022** [comment]
Realy?


> > > Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.
> > 
> > 
> > An even key is very easy to check.
> 
> How do you imagine it? After all, we cannot check the result of division, whether it is correct or not.

C:\Users\win>C:\Users\win\Desktop\ecctools\keymath.exe 035dee726b0fe623224fa1f4d79af66a9a1829213ec675875c619266a5f184e7d1  / 2 
Result: 0307814838a8456397f0f7523300e07418da15484b169467bd74e7d1e5947e8981 

03633cbe3ec02b9401c5effa144c5b4d22f87940259634858fc7e59b1c09937852 / 2 
0337374e00a32eaf009e9946035c0e69085627b60a844637d2b958dd83bcfa4383 


C:\Users\win>C:\Users\win\Desktop\ecctools\keymath.exe 0307814838a8456397f0f7523300e07418da15484b169467bd74e7d1e5947e8981 - 0xx000000000000000000000000000000xxxxd0cf2d4b7ee5eaddxxxxxxxxxxxxxxxxxxx
Result: 0xxxxxxdb096b7d5fb22bf9786db97cc48a55930545265d9737c40a41e5f3b982

**Comment by winnery2022** [comment]
I can no longer answer here. I'll wait for Alberto's answer.

**Comment by Gusev39rus** [comment]
> > > Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.
> > 
> > 
> > An even key is very easy to check.
> 
> How do you imagine it? After all, we cannot check the result of division, whether it is correct or not.

Это был очередной мамкин хакер, который знает проверку чёткости, но он лёгких путей не ищет )))

**Comment by winnery2022** [comment]
> > > > Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.
> > > 
> > > 
> > > An even key is very easy to check.
> > 
> > 
> > How do you imagine it? After all, we cannot check the result of division, whether it is correct or not.
> 
> Это был очередной мамкин хакер, который знает проверку чёткости, но он лёгких путей не ищет )))

Show me the easy way, maybe you hacked 120 and 125?

**Comment by Gusev39rus** [comment]
> Realy?
> 
> > > > Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.
> > > 
> > > 
> > > An even key is very easy to check.
> > 
> > 
> > How do you imagine it? After all, we cannot check the result of division, whether it is correct or not.
> 
> C:\Users\win>C:\Users\win\Desktop\ecctools\keymath.exe 035dee726b0fe623224fa1f4d79af66a9a1829213ec675875c619266a5f184e7d1 / 2 Result: 0307814838a8456397f0f7523300e07418da15484b169467bd74e7d1e5947e8981
> 
> 03633cbe3ec02b9401c5effa144c5b4d22f87940259634858fc7e59b1c09937852 / 2 0337374e00a32eaf009e9946035c0e69085627b60a844637d2b958dd83bcfa4383
> 
> C:\Users\win>C:\Users\win\Desktop\ecctools\keymath.exe 0307814838a8456397f0f7523300e07418da15484b169467bd74e7d1e5947e8981 - 0xx000000000000000000000000000000xxxxd0cf2d4b7ee5eaddxxxxxxxxxxxxxxxxxxx Result: 0xxxxxxdb096b7d5fb22bf9786db97cc48a55930545265d9737c40a41e5f3b982

I can do it too: 
n-n*1/2= target
)))

**Comment by sssergy** [comment]
> > > > > Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.
> > > > 
> > > > 
> > > > An even key is very easy to check.
> > > 
> > > 
> > > How do you imagine it? After all, we cannot check the result of division, whether it is correct or not.
> > 
> > 
> > Это был очередной мамкин хакер, который знает проверку чёткости, но он лёгких путей не ищет )))
> 
> Show me the easy way, maybe you hacked 120 and 125?

They were revealed using a large number of video cards. They wrote about this on Bittalk.
Probably the next key will be revealed by the same miner.

**Comment by winnery2022** [comment]
> > > > Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.
> > > 
> > > 
> > > An even key is very easy to check.
> > 
> > 
> > How do you imagine it? After all, we cannot check the result of division, whether it is correct or not.
> 
> Это был очередной мамкин хакер, который знает проверку чёткости, но он лёгких путей не ищет )))

I made sure that you know perfectly well how to check this. So I'll delete this.

**Comment by winnery2022** [comment]
> > > > > > Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.
> > > > > 
> > > > > 
> > > > > An even key is very easy to check.
> > > > 
> > > > 
> > > > How do you imagine it? After all, we cannot check the result of division, whether it is correct or not.
> > > 
> > > 
> > > Это был очередной мамкин хакер, который знает проверку чёткости, но он лёгких путей не ищет )))
> > 
> > 
> > Show me the easy way, maybe you hacked 120 and 125?
> 
> They were revealed using a large number of video cards. They wrote about this on Bittalk. Probably the next key will be revealed by the same miner.

I know about it. The person is just talking off topic. You asked a question, I answered. I don’t think it’s worth discussing this with you since I don’t get any reasonable answers. It seems you know more than me.

**Comment by Gusev39rus** [comment]
if you knew how to check the parity, then you wouldn't have any questions at all, because parity check = complete hacking of all keys that have a public key and you don't need to invent anything else. if you know the parity of the key, then it will take less than 1 second to crack one key.

**Comment by winnery2022** [comment]
You probably don't know about divisions. Firstly, the question is not about even and odd numbers. Secondly, even if you practice honesty, it will not give you anything. You will have to divide it 90 times and that is more than 10,000 million. If you miss once, you lose.

**Comment by winnery2022** [comment]
> if you knew how to check the parity, then you wouldn't have any questions at all, because parity check = complete hacking of all keys that have a public key and you don't need to invent anything else. if you know the parity of the key, then it will take less than 1 second to crack one key.

03d500a207108b7198419afaaf7d79a59b67f2de9eb4966ffdc903e1ae878780eb even 130 bit  Prove that you are not your mother's hacker.

**Comment by Gusev39rus** [comment]
> You probably don't know about divisions. Firstly, the question is not about even and odd numbers. Secondly, even if you practice honesty, it will not give you anything. You will have to divide it 90 times and that is more than 10,000 million. If you miss once, you lose.

You just wrote that it's easy to determine parity))))))

**Comment by Gusev39rus** [comment]
> > Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.
> 
> An even key is very easy to check.

ВОТ ЭТОТ ПОСТ

**Comment by winnery2022** [comment]
> You just wrote that it's easy to determine parity))))))

I proved it. If you don't understand, sorry. But you have not proven how to hack an even 130 bit wallet in 1 second.

**Comment by winnery2022** [comment]
> > > Maybe so, but we don’t know the parity of the key and can’t check it. Even if you are sure that the target key is even and can be divided by 2, it is still not possible to solve it in a short time.
> > 
> > 
> > An even key is very easy to check.
> 
> ВОТ ЭТОТ ПОСТ

I don't have time to discuss this with you. I'll wait for Alberto's answer.

**Comment by Gusev39rus** [comment]
> > You just wrote that it's easy to determine parity))))))
> 
> I proved it. If you don't understand, sorry. But you have not proven how to hack an even 130 bit wallet in 1 second.

the thing is, it's impossible. You haven't proven anything, absolutely

**Comment by winnery2022** [comment]
> the thing is, it's impossible. You haven't proven anything, absolutely

I repeat once again, you don’t have to have a conversation with me. She's not talking about anything. This can be checked very easily. I gave you 2 even keys. Prove to everyone here your words on how to hack in 1 second. Don't change the subject. You won't get any more information.

**Comment by Gusev39rus** [comment]
> > the thing is, it's impossible. You haven't proven anything, absolutely
> 
> I repeat once again, you don’t have to have a conversation with me. She's not talking about anything. This can be checked very easily. I gave you 2 even keys. Prove to everyone here your words on how to hack in 1 second. Don't change the subject. You won't get any more information.

Dude, you didn't get the point at all..

**Comment by winnery2022** [comment]
> > > the thing is, it's impossible. You haven't proven anything, absolutely
> > 
> > 
> > I repeat once again, you don’t have to have a conversation with me. She's not talking about anything. This can be checked very easily. I gave you 2 even keys. Prove to everyone here your words on how to hack in 1 second. Don't change the subject. You won't get any more information.
> 
> Dude, you didn't get the point at all..

I just understood the point. Let's be more specific. The question here is not even or uneven numbers. You're probably unlikely to understand what's written at the top. You can keep even and odd numbers in parallel, but it will take a lot of time. This topic is clearly not worth discussing with you. I don't see the answer in 1 second with an even key. And if you meant that knowing each next subtracted key, then express your thoughts correctly (and once again, they can be done in parallel), but this will take a lot of time manually. If you manually proofread with such thoughts, you are unlikely to achieve success.

**Comment by albertobsd** [comment]
> We can hit some whith this?

@winnery2022 can you be more specific with this? i don't know what are you asking.

**Comment by Gusev39rus** [comment]
> > > > the thing is, it's impossible. You haven't proven anything, absolutely
> > > 
> > > 
> > > I repeat once again, you don’t have to have a conversation with me. She's not talking about anything. This can be checked very easily. I gave you 2 even keys. Prove to everyone here your words on how to hack in 1 second. Don't change the subject. You won't get any more information.
> > 
> > 
> > Dude, you didn't get the point at all..
> 
> I just understood the point. Let's be more specific. The question here is not even or uneven numbers. You're probably unlikely to understand what's written at the top. You can keep even and odd numbers in parallel, but it will take a lot of time. This topic is clearly not worth discussing with you. I don't see the answer in 1 second with an even key. And if you meant that knowing each next subtracted key, then express your thoughts correctly (and once again, they can be done in parallel), but this will take a lot of time manually. If you manually proofread with such thoughts, you are unlikely to achieve success.

You didn't understand the question from sergy about parity. To paraphrase: we do not know and cannot verify the parity of the key if its private key is unknown. If we could check the honesty, we would divide the honest key by 2, check the parity again and divide it by 2 again, and so about 90 times and then we would find the key by a simple search. Try to determine the parity of these public keys even or not the private key from them: 
1. 02b30ef81221219e64d429f30e783a125e0988c8cf3ab9437a45b727618adb7385 
2. 03e227af2a43bf8eb8e50ca80e1ef920f06613a1450f07d1e3e6841c8c19557ba0 
3. 03bf68a3a688f57bdb8a0e2ce19b7cecd69354de3edad7a834c36bbed191c96ed6

And never think that you know something more than everyone else, for example, I never publish my promotions. but I work in a completely different direction, more fundamental.

**Comment by winnery2022** [comment]
> > > > > the thing is, it's impossible. You haven't proven anything, absolutely
> > > > 
> > > > 
> > > > I repeat once again, you don’t have to have a conversation with me. She's not talking about anything. This can be checked very easily. I gave you 2 even keys. Prove to everyone here your words on how to hack in 1 second. Don't change the subject. You won't get any more information.
> > > 
> > > 
> > > Dude, you didn't get the point at all..
> > 
> > 
> > I just understood the point. Let's be more specific. The question here is not even or uneven numbers. You're probably unlikely to understand what's written at the top. You can keep even and odd numbers in parallel, but it will take a lot of time. This topic is clearly not worth discussing with you. I don't see the answer in 1 second with an even key. And if you meant that knowing each next subtracted key, then express your thoughts correctly (and once again, they can be done in parallel), but this will take a lot of time manually. If you manually proofread with such thoughts, you are unlikely to achieve success.
> 
> You didn't understand the question from sergy about parity. To paraphrase: we do not know and cannot verify the parity of the key if its private key is unknown. If we could check the honesty, we would divide the honest key by 2, check the parity again and divide it by 2 again, and so about 90 times and then we would find the key by a simple search. Try to determine the parity of these public keys even or not the private key from them:
> 
> 1. 02b30ef81221219e64d429f30e783a125e0988c8cf3ab9437a45b727618adb7385
> 2. 03e227af2a43bf8eb8e50ca80e1ef920f06613a1450f07d1e3e6841c8c19557ba0
> 3. 03bf68a3a688f57bdb8a0e2ce19b7cecd69354de3edad7a834c36bbed191c96ed6
> 
> And never think that you know something more than everyone else, for example, I never publish my promotions. but I work in a completely different direction, more fundamental.

Now you have expressed yourself in more detail. Are these 130 bit keys? We can divide every 2 next keys, then 4, and so on, but the file will be very large and difficult to do manually. I talked about this earlier. We can also conduct them in parallel. I think we can close the topic on division at this point.

**Comment by winnery2022** [comment]
> > We can hit some whith this?
> 
> @winnery2022 can you be more specific with this? i don't know what are you asking.

I meant that different numbers from the main x2 division intersect relatively, this can be seen in my file. Is it possible to improve this process?

**Comment by Gusev39rus** [comment]
> > > We can hit some whith this?
> > 
> > 
> > @winnery2022 can you be more specific with this? i don't know what are you asking.
> 
> I meant that different numbers from the main x2 division intersect relatively, this can be seen in my file. Is it possible to improve this process?

Invented the bicycle.) This is the natural and well-known behavior of numbers when dividing modulo))))



> > > > > > the thing is, it's impossible. You haven't proven anything, absolutely
> > > > > 
> > > > > 
> > > > > I repeat once again, you don’t have to have a conversation with me. She's not talking about anything. This can be checked very easily. I gave you 2 even keys. Prove to everyone here your words on how to hack in 1 second. Don't change the subject. You won't get any more information.
> > > > 
> > > > 
> > > > Dude, you didn't get the point at all..
> > > 
> > > 
> > > I just understood the point. Let's be more specific. The question here is not even or uneven numbers. You're probably unlikely to understand what's written at the top. You can keep even and odd numbers in parallel, but it will take a lot of time. This topic is clearly not worth discussing with you. I don't see the answer in 1 second with an even key. And if you meant that knowing each next subtracted key, then express your thoughts correctly (and once again, they can be done in parallel), but this will take a lot of time manually. If you manually proofread with such thoughts, you are unlikely to achieve success.
> > 
> > 
> > You didn't understand the question from sergy about parity. To paraphrase: we do not know and cannot verify the parity of the key if its private key is unknown. If we could check the honesty, we would divide the honest key by 2, check the parity again and divide it by 2 again, and so about 90 times and then we would find the key by a simple search. Try to determine the parity of these public keys even or not the private key from them:
> > 
> > 1. 02b30ef81221219e64d429f30e783a125e0988c8cf3ab9437a45b727618adb7385
> > 2. 03e227af2a43bf8eb8e50ca80e1ef920f06613a1450f07d1e3e6841c8c19557ba0
> > 3. 03bf68a3a688f57bdb8a0e2ce19b7cecd69354de3edad7a834c36bbed191c96ed6
> > 
> > And never think that you know something more than everyone else, for example, I never publish my promotions. but I work in a completely different direction, more fundamental.
> 
> Now you have expressed yourself in more detail. Are these 130 bit keys? We can divide every 2 next keys, then 4, and so on, but the file will be very large and difficult to do manually. I talked about this earlier. We can also conduct them in parallel. I think we can close the topic on division at this point.

-1/2 -1/2 ??? Wow, this is a discovery))

I got it, forgot the subject... bro....

**Comment by winnery2022** [comment]
> > > > We can hit some whith this?
> > > 
> > > 
> > > @winnery2022 can you be more specific with this? i don't know what are you asking.
> > 
> > 
> > I meant that different numbers from the main x2 division intersect relatively, this can be seen in my file. Is it possible to improve this process?
> 
> Invented the bicycle.) This is the natural and well-known behavior of numbers when dividing modulo))))
> 
> > > > > > > the thing is, it's impossible. You haven't proven anything, absolutely
> > > > > > 
> > > > > > 
> > > > > > I repeat once again, you don’t have to have a conversation with me. She's not talking about anything. This can be checked very easily. I gave you 2 even keys. Prove to everyone here your words on how to hack in 1 second. Don't change the subject. You won't get any more information.
> > > > > 
> > > > > 
> > > > > Dude, you didn't get the point at all..
> > > > 
> > > > 
> > > > I just understood the point. Let's be more specific. The question here is not even or uneven numbers. You're probably unlikely to understand what's written at the top. You can keep even and odd numbers in parallel, but it will take a lot of time. This topic is clearly not worth discussing with you. I don't see the answer in 1 second with an even key. And if you meant that knowing each next subtracted key, then express your thoughts correctly (and once again, they can be done in parallel), but this will take a lot of time manually. If you manually proofread with such thoughts, you are unlikely to achieve success.
> > > 
> > > 
> > > You didn't understand the question from sergy about parity. To paraphrase: we do not know and cannot verify the parity of the key if its private key is unknown. If we could check the honesty, we would divide the honest key by 2, check the parity again and divide it by 2 again, and so about 90 times and then we would find the key by a simple search. Try to determine the parity of these public keys even or not the private key from them:
> > > 
> > > 1. 02b30ef81221219e64d429f30e783a125e0988c8cf3ab9437a45b727618adb7385
> > > 2. 03e227af2a43bf8eb8e50ca80e1ef920f06613a1450f07d1e3e6841c8c19557ba0
> > > 3. 03bf68a3a688f57bdb8a0e2ce19b7cecd69354de3edad7a834c36bbed191c96ed6
> > > 
> > > And never think that you know something more than everyone else, for example, I never publish my promotions. but I work in a completely different direction, more fundamental.
> > 
> > 
> > Now you have expressed yourself in more detail. Are these 130 bit keys? We can divide every 2 next keys, then 4, and so on, but the file will be very large and difficult to do manually. I talked about this earlier. We can also conduct them in parallel. I think we can close the topic on division at this point.
> 
> -1 /2 -1 /2 ??? Wow, this is a discovery))
> 
> I got it, forgot the subject... bro....

Сool Bro maiby you Satoshi  D

**Comment by albertobsd** [comment]
> I meant that different numbers from the main x2 division intersect relatively, this can be seen in my file. Is it possible to improve this process?

No, that is just some properties of the curve, not big deal.

Please don't use the issues section for this kind of post
