### ISSUE TITLE
[Question] Is this how I use it to hunt from a public key?

### ISSUE THREAD

**Issue by FeatureSpitter** [albertobsd/keyhunt#279]
I have a public key in the file "pkey.pub":
`04a9c9c642db794(...)00e726368d6ec7c1`

That can be extracted from P2PK scripts

```
ScriptPubKey (ASM)
OP_PUSHBYTES_65 04a9c9c642db794(...)00e726368d6ec7c1
OP_CHECKSIG
```

For 256GB of RAM, is this the right command to hunt for this key?

`./keyhunt -m bsgs -f pkey.pub -t 128 -s 10 -R -c btc -B random -S -q -n 0x400000000000 -k 8192`

Any optimizations you could suggest?

Thanks.

**Comment by albertobsd** [comment]
make your own test

**Comment by FeatureSpitter** [comment]
How?

Where can I find a public bitcoin key that I can compute in less than the universe time?

**Comment by albertobsd** [comment]
puzzles already solved, test keys on the documentation examples, generate a random keys and give the program some "small" range maybe some 65 to 70 bits.

There are different approach to test your own setup.

**Comment by FeatureSpitter** [comment]
Got it. Thanks!
