### ISSUE TITLE
can't seek the file

### ISSUE THREAD

**Issue by dem10** [albertobsd/keyhunt#28]
For some reason, the program does not see the bPfile.bin, although it is located in the same folder as the keyhunt.exe.
![125](https://user-images.githubusercontent.com/24973894/113204249-c17dad00-9275-11eb-8f5f-849e61a239f8.png)

**Comment by albertobsd** [comment]
Seems like your file is truncate or is not enough for the number of element that you need, can you tell me the exact size of your file in Bytes?

- The file need to be divisible by 32
- The fille need to have almost (32 * 671088640 bytes)  where 671088640 is the number showed in your image, this is 21474836480 bytes or exactly 20 Gigabytes

**Comment by dem10** [comment]
bPfile exact size 21 474 836 480 bytes.

**Comment by albertobsd** [comment]
Extrange, maybe is something with windows, seeek or the size of the variable, can you change the next line:

```
fprintf(stderr,"Can't seek the file\n");
```

by the next one:

```
fprintf(stderr,"Can't seek the file at index %"PRIu64", offset %"PRIu64"\n",i,(uint64_t)(i*32));
```

also change the next line:

```
if(fseek(fd,i*32,SEEK_SET) != 0)	{
```

by

``` 
if(fseek(fd,(uint64_t)(i*32),SEEK_SET) != 0)	{
```

please change those lines, recompile the code and execute again.

letme know if that works

best regards!

**Comment by dem10** [comment]
Ok, I'll try this a little later.

**Comment by dem10** [comment]
I modified the keyhunt.с file this way.
![123](https://user-images.githubusercontent.com/24973894/113261914-b314ad00-92d8-11eb-9a6f-a38bc6562d20.png)
this is the result
![124](https://user-images.githubusercontent.com/24973894/113262096-e2c3b500-92d8-11eb-8705-90b5321cd9cb.png)

**Comment by albertobsd** [comment]
Definily is a error of the windows version, i don't know if this is exclusive of Windows or the compiler version.

The bP table generation without file is also multi thread, you weill use for now without the `-p file` option in windows

**Comment by dem10** [comment]
An assembly error appeared in the new version, which is probably why the program also produces an error.
![123](https://user-images.githubusercontent.com/24973894/114820498-becb9d80-9dc7-11eb-9aaa-dc27743c5bae.png)
![124](https://user-images.githubusercontent.com/24973894/114820518-c723d880-9dc7-11eb-81b9-02e7d29cea3f.png)

**Comment by dem10** [comment]
An assembly error appeared in the new version. But if I understood correctly, the program is not fully working and there is no BSGS mode.
![123](https://user-images.githubusercontent.com/24973894/114904168-3f1ded00-9e20-11eb-86f5-2a55c20d8292.png)

**Comment by dem10** [comment]
As I understand it, the program uses uint64 and emulates uint128. If everything is correct, uint128 has not yet been implemented. But why is not uint256 used because it operates with large numbers. Or will it slow down the program? I'm not a programmer, just a question of interest.When compiling, some kind of error occurs. I do not know how much this affects the operation of the program. But the program still does not see the bPfile.
![123](https://user-images.githubusercontent.com/24973894/115222156-1abd5b80-a113-11eb-977c-b463c307b688.png)
![124](https://user-images.githubusercontent.com/24973894/115222688-aa630a00-a113-11eb-8e6f-36a507b6ddae.png)

**Comment by dem10** [comment]
An interesting imitation of a quantum computer and Shor's algorithm. Maybe this will help speed up the keyhunt.
https://github.com/rafa32/Quantum-Shor/blob/master/shor.c

**Comment by albertobsd** [comment]
this should be solved now?
