### ISSUE TITLE
creating bloom filters files without the required ram

### ISSUE THREAD

**Issue by eshbeata** [albertobsd/keyhunt#281]
Hello

Generating the bloom filters takes a lot of time example for 1 TB 
[+] Bloom filter for 274877906944 elements : 942249.56 MB
[+] Bloom filter for 8589934592 elements : 29445.30 MB
[+] Bloom filter for 268435456 elements : 920.17 MB
[+] Allocating 4096.00 MB for 268435456 bP Points
[+] processing 78643200/274877906944 bP points : 0%

is there a way to have an option to generate the files without having the actual ram on the devices? and without even running the bsgs and brute force .
Then we can use these files with a real server that have the RAM needed to process it?

**Comment by albertobsd** [comment]
No
