### ISSUE TITLE
Total 0 keys in seconds... keyhunt legacy

### ISSUE THREAD

**Issue by Yaroslav-Boiko** [albertobsd/keyhunt#284]
Hi
I have a problem with displaying progress and speed.
![image](https://github.com/albertobsd/keyhunt/assets/20477802/dd95c67a-d82e-47ad-a1c3-bbc48e0e38db)
Key search works, tests pass.

CPU ARMv7
\# g++ --version
g++ (OpenWrt GCC 8.4.0) 8.4.0

**Comment by albertobsd** [comment]
its a thread problem for some ARM processors there is nothing that i can do. if you test more or less the same command in a Intel machine  the speed counter  works perfectly:

![image](https://github.com/albertobsd/keyhunt/assets/17832765/18f01e86-35df-4759-9ac6-f630765e161f)
