### ISSUE TITLE
Error reading the file keyhunt_bsgs_4_4194304.blm

### ISSUE THREAD

**Issue by mehdibil** [albertobsd/keyhunt#288]
help please i tried to run it from a cpu cloud but i got this error i tried different -k values but i have the same problem, what should i do please
![Screenshot_2024-02-02_15_30_20](https://github.com/albertobsd/keyhunt/assets/105067781/c9a47889-da58-45db-98c8-45ec015fc7ee)

**Comment by albertobsd** [comment]
Its a problem of your system, please don't open issues like this
