### ISSUE TITLE
keyhunt P2WPKH Bech32 addresses

### ISSUE THREAD

**Issue by dolaor** [albertobsd/keyhunt#29]
Hi Alberto,

Is it possible to use the rmd160 mode to hunt for SegWit(Bech32) addresses (example: bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4)? This will probably hurt a lot the speed of the script?
What about hunting P2SH addresses like SegWit(nested) (example: 3DwYUKCDoU8hdBgpGkNy8QXjUV6qTb6yp1) or P2WSH addresses (example: bc1qgdjqv0av3q56jvd82tkdjpy7gdp9ut8tlqmgrpmv24sq90ecnvqqjwvw97)? I think it is not possible since the [steps](https://en.bitcoin.it/w/images/en/4/48/Address_map.jpg) involved are differents than P2PKH or SegWit(Bech32) invoice adresses.

Thanks!

**Comment by albertobsd** [comment]
Well yes, is possible but i need to impplement those steps. And yes the speed will decrease with more steps in the addres generation. maybe i add some option to targe exclusive one of those opcions.

best regards!

**Comment by albertobsd** [comment]
i'm a little lazy, can someone post a link to the correct documentation of this kind of address.

Regards!

**Comment by phaenomenon** [comment]
> Hi Alberto,
> 
> Is it possible to use the rmd160 mode to hunt for SegWit(Bech32) addresses (example: bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4)? This will probably hurt a lot the speed of the script? What about hunting P2SH addresses like SegWit(nested) (example: 3DwYUKCDoU8hdBgpGkNy8QXjUV6qTb6yp1) or P2WSH addresses (example: bc1qgdjqv0av3q56jvd82tkdjpy7gdp9ut8tlqmgrpmv24sq90ecnvqqjwvw97)? I think it is not possible since the [steps](https://en.bitcoin.it/w/images/en/4/48/Address_map.jpg) involved are differents than P2PKH or SegWit(Bech32) invoice adresses.
> 
> Thanks!

I second that. It would be a great enhancement for keyhunt to have p2sh, p2wsh and bech32 support. And most of all it would be awesome to have multiGPU support

**Comment by albertobsd** [comment]
I wil not add those kind of addresses unless there are some good puzzle for it.
