### ISSUE TITLE
Starting the program

### ISSUE THREAD

**Issue by Bitcoin228** [albertobsd/keyhunt#291]
Greetings... How to properly run the key search program, I have a 14-core Intel Core i9-13900H processor (4.1 - 5.4 GHz) how to register 14 cores or 20 threads in the program. ? By default, there are 4 cores in the program itself

**Comment by dem10** [comment]
Read Readmi. Launch the tool with the command -h. If you don’t understand how to launch it, repeat the first 2 steps, and if you don’t understand, is it worth running this tool at all?

**Comment by Bitcoin228** [comment]
👍
