### ISSUE TITLE
The string  is not Valid Base58

### ISSUE THREAD

**Issue by NovaHelmet** [albertobsd/keyhunt#292]
Please Fix the strings to add them like The string "1India" is not Valid Base58

**Comment by sssergy** [comment]
> Please Fix the strings to add them like The string "1India" is not Valid Base58

https://bitcoinwiki.org/wiki/base58

**Comment by albertobsd** [comment]
@NovaHelmet are you retarded?

**Comment by NovaHelmet** [comment]
@albertobsd I am So sorry Mate
