### ISSUE TITLE
Not showing speed on Raspberry Pi Zero 2W

### ISSUE THREAD

**Issue by klgor1803** [albertobsd/keyhunt#299]
even after 1000 seconds it doesn't shows the speed

ram: 512M
swap: 4G
os: Kali ARM 2024.1 RPI 02W armhf build
command: ./keyhunt -m address -b 66 -f tests/66.txt -Rqs1 -l compress
also tried with sudo, no difference

[+] Total 0 keys in 1198 seconds: 0 keys/s

but i know it works bc if i run it with "-f tests/1to32.txt", it shows the keys, but can't get speed

**Comment by albertobsd** [comment]
I don't know if this is a problem with some small ARM processor

Some users report similar issues before
https://github.com/albertobsd/keyhunt/issues/284

I need to find a way to test if this is a pthread problem or a hardware problem.

**Comment by klgor1803** [comment]
I switched to raspbian, now it shows the speed

**Comment by klgor1803** [comment]
may be because i was using armhf kali, now i am using arm64 raspbian
