### ISSUE TITLE
Question about bPfile generation.

### ISSUE THREAD

**Issue by dimon105** [albertobsd/keyhunt#30]
Hello Alberto! First of all, I want to thank you for this wonderful program! Yes, of course GPU implementation are lacking, but even so, it works just fine. A question. Is it possible to specify the range for generating points when creating a bPfile yourself? Or does the generation always start from one and up to the value specified at startup? Thanks.

**Comment by albertobsd** [comment]
The bP table is always the same, it don't get affected  byte the selected range that you are scanning, it always is from G (Point genetator) to N where N is the number that you specify. This will done from this way to avoid different tables at diffrent ranges.

**Comment by dimon105** [comment]
I understand correctly that bPfile contains public keys starting from point G and up to the value specified when forcibly generating this file with the command ./bPfile <bP items> <output filename>, where the end point, or rather the X coordinate, is specified as the <bP items> parameter

**Comment by albertobsd** [comment]
> I understand correctly that bPfile contains public keys starting from point G and up to the value specified

Yest the bP items is the las privatekeys generated:

G, 2G, 3G ... (bP items) G

The file only store the X value of the publickey, only 32 bytes in RAW format.

Best regards!
