### ISSUE TITLE
Still getting N =0 and 0key per 1000 sec 

### ISSUE THREAD

**Issue by Shubsaini08** [albertobsd/keyhunt#303]
Hi there thanks for making this project its working in other devices but in my mobile when i set it up it shows n=0x0 
And i tried everything but its not working.
I'm pinning screenshot here hope you'll helpme out![Screenshot_20240420_014812_Termux.jpg](https://github.com/albertobsd/keyhunt/assets/161625628/699e798a-9cde-4ab3-b3ed-687a4ab09ccb)

**Comment by albertobsd** [comment]
That is an ARM problem for some processor, please stop posting it again
