### ISSUE TITLE
MiniKeys sequencial bruteforce hash an ERR

### ISSUE THREAD

**Issue by Nakinthorn** [albertobsd/keyhunt#304]
I try to run MiniKeys mode with base key

example : S7AfhgDK111111111111

the program is working well until
program run through   S7AfhgDK11111111zzzz
it never change next position to number 2
it loop to  S7AfhgDK111111111zzz again

i try many use case , sometime it pass to position 6 and then loop

**Comment by albertobsd** [comment]
can you share the full comant that you use?
