### ISSUE TITLE
Range End Not Working

### ISSUE THREAD

**Issue by brunosantiagodesouza** [albertobsd/keyhunt#308]
I’ve been using the keyhunt tool, and I’ve noticed that the -r (range) option doesn’t seem to work as expected. Specifically, when I specify a range like -r 1:FFFFFFFF, it doesn’t behave as intended. Instead, I get unexpected results.

Could you please investigate this issue? It would be great if the tool could accurately handle the specified range.

Thank you for your attention to this matter!

Best regards

**Comment by albertobsd** [comment]
I guess that you are using it with multiple threads don't you?

If that is the case the default subrange per thread is 32 bits just like your specified range. If you are going to work with small ranges ( yes that 32 bit range  -r 1:FFFFFFFF  is small) please specify the N value to some lower value with  -n 0x1000000 or to -n 0x10000 ( 24 or 16 bit respectively) personally I prefer 24 bits.

With this I guess that your problem will be solved
