### ISSUE TITLE
I have a personalized private key but I can't use it because it starts differently.

### ISSUE THREAD

**Issue by all4x** [albertobsd/keyhunt#309]
./keyhunt -m address -t 10 -f tests/judeu.txt -s 10 -r c0de00000000000000000000000000000000000000000000330000000000000000:c0de0000000
000000000000000000000000000000000000033FFFFFFFFFFFFFFFF

output : 

./keyhunt -m address -t 10 -f tests/judeu.txt -s 10 -r c0de00000000000000000000000000000000000000000000330000000000000000:c0de0000000000000000000000000000000000000000000033FFFFFFFFFFFFFFFF

[+] Version 0.2.230519 Satoshi Quest, developed by AlbertoBSD
[+] Mode address
[+] Threads : 10
[+] Stats output every 10 seconds
[+] Setting search for btc adddress
[E] Start and End range can't be great than N
Fallback to random mode!
[+] N = 0x100000000
[+] Range 
[+] -- from : 0x1
[+] -- to   : 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141
[+] Allocating memory for 1 elements: 0.00 MB
[+] Bloom filter for 1 elements.
[+] Loading data to the bloomfilter total: 0.03 MB
[+] Sorting data ... done! 1 values were loaded and sorted
^Cse key: 900000001

**Comment by sssergy** [comment]
> ./keyhunt -m address -t 10 -f tests/judeu.txt -s 10 -r c0de00000000000000000000000000000000000000000000330000000000000000:c0de0000000 000000000000000000000000000000000000033FFFFFFFFFFFFFFFF
> 
> output :
> 
> ./keyhunt -m address -t 10 -f tests/judeu.txt -s 10 -r c0de00000000000000000000000000000000000000000000330000000000000000:c0de0000000000000000000000000000000000000000000033FFFFFFFFFFFFFFFF
> 
> [+] Version 0.2.230519 Satoshi Quest, developed by AlbertoBSD [+] Mode address [+] Threads : 10 [+] Stats output every 10 seconds [+] Setting search for btc adddress [E] Start and End range can't be great than N Fallback to random mode! [+] N = 0x100000000 [+] Range [+] -- from : 0x1 [+] -- to : 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141 [+] Allocating memory for 1 elements: 0.00 MB [+] Bloom filter for 1 elements. [+] Loading data to the bloomfilter total: 0.03 MB [+] Sorting data ... done! 1 values were loaded and sorted ^Cse key: 900000001

There is no such private key format.

**Comment by albertobsd** [comment]
> There is no such private key format.

Exactly, all privatekeys internally are modulo N
Real key = fake key %  N
Where N is 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141

Then you real key range should be the real key
