### ISSUE TITLE
Add manual.

### ISSUE THREAD

**Issue by Noname400** [albertobsd/keyhunt#31]
if you have a work computer, it is recommended to use only 80% of the RAM.
All settings are specified for a working computer!
bPfile must be a multiple of 32 (Gb memory * 134217728)
Create a file for 2 GB memory with a dual core processor: ./bPfile 268435456 ./bPfile.bin -t 2
P .S: On Windows, use PowerShell.

dear developers, please check my numbers and if they are correct it may be worth adding them to the description for other people to understand.

```
+-----------------------------------------------------------------+
|   Gb memory | - k     | bPfile  (134217728 * gb)  | Size gb HDD |
+------------ | --------| --------------------------| ------------+
 | 2          | 64      | 268435456                 | 8,192       |
| 4           | 128     | 536870912                 |             |
| 8           | 256     | 1073741824                |             |
| 16          | 512     | 2147483648                |             |
| 24          | 768     | 3221225472                |             |
| 32          | 1024    | 4294967296                |             |
| 64          | 2048    | 8589934592                |             |
+-------------+---------+---------------------------+-------------+
```

**Comment by sezginyildirim91** [comment]
If the -n parameter is specified, these values change according to the situation.

**Comment by dem10** [comment]
all this can be calculated by running the program without the -p flag. It is enough to look at bloom filter 1 and start creating a table with filter 1 parameters.

**Comment by Noname400** [comment]
I do not pretend to be complete, but for those who want to try but little knowledge, I think it will be useful!

**Comment by dem10** [comment]
The value of the -k flag can be different  -k 200 and -k 220 or -k 240. It is better to always look at the number of bloom filter 1 elements and generate a table according to your values.

**Comment by albertobsd** [comment]
Thanks guys i will check those values.

Best regards

**Comment by Lexus247** [comment]
The calculations in the table are not correct.
I have To 2500 and the memory is occupied by 35.9 GB and bPfile 1895825408.
And according to table K, it should be about 1100.
Also, the data on the bPfile table simply does not start.
For example, with my K 2500 bPfile 895825408-starts.

**Comment by Lexus247** [comment]
> Thanks guys i will check those values.
> 
> Best regards

The calculations in the table are not correct.
I have To 2500 and the memory is occupied by 35.9 GB and bPfile 1895825408.
And according to table K, it should be about 1100.
Also, the data on the bPfile table simply does not start.
For example, with my K 2500 bPfile 895825408-starts.
