### ISSUE TITLE
Error searching for keys in the right range.

### ISSUE THREAD

**Issue by jonathanferreiras** [albertobsd/keyhunt#311]
Gentlemen, I found something that I'm confused about. 

When looking for challenge 10, it is in the **200:3ff** range, but when using the command:
` ./keyhunt -m address -f tests/10.txt -b 10 -l compress -R -q -s 10 -t 11  `

the same is not found.

![image](https://github.com/albertobsd/keyhunt/assets/25043239/8b78aba4-fbbb-4347-874a-5f101d0c356e)

Now if I change to 9 bit. The range is wrong and you can find it.

![image](https://github.com/albertobsd/keyhunt/assets/25043239/57a4c282-f7ba-401b-a170-5c5b5981f59d)

How did you find an out of reach key? And why is it giving an error in the right lane?

Thanks.

**Comment by sssergy** [comment]
> Gentlemen, I found something that I'm confused about.
> 
> When looking for challenge 10, it is in the **200:3ff** range, but when using the command: `./keyhunt -m address -f tests/10.txt -b 10 -l compress -R -q -s 10 -t 11 `
> 
> the same is not found.
> 
> ![image](https://private-user-images.githubusercontent.com/25043239/338007053-8b78aba4-fbbb-4347-874a-5f101d0c356e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NjQzODUsIm5iZiI6MTcxNzk2NDA4NSwicGF0aCI6Ii8yNTA0MzIzOS8zMzgwMDcwNTMtOGI3OGFiYTQtZmJiYi00MzQ3LTg3NGEtNWYxMDFkMGMzNTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDIwMTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNGUxODhlZjRkNTZjMjY2ODg1ZGM5ZjkyZGQ5NzBlNmQ3NTYzMmM0MDZhOWRiYTNmOTMzNTdjNTUzNDQxZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B-LsSkGR4kMowKse1W1mFN0I3e8eGjgdgodGkDX4MjU)
> 
> Now if I change to 9 bit. The range is wrong and you can find it.
> 
> ![image](https://private-user-images.githubusercontent.com/25043239/338007213-57a4c282-f7ba-401b-a170-5c5b5981f59d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NjQzODUsIm5iZiI6MTcxNzk2NDA4NSwicGF0aCI6Ii8yNTA0MzIzOS8zMzgwMDcyMTMtNTdhNGMyODItZjdiYS00MDFiLWExNzAtNWM1YjU5ODFmNTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDIwMTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZjQ4NDhiNTFjNDNmZDJkNjBiNmUxYjQ4ZjhjNmZkYjA0Nzc4YjEzZjUwNmMxZDljMjYwZGEzYzhkYzAzY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DfBTe4Vzy2jzCq-nPYwwSp3E-MjLL1MWK6QKmMA_Udw)
> 
> How did you find an out of reach key? And why is it giving an error in the right lane?
> 
> Thanks.

Well, even one processor thread captures a larger range than is specified for search! Would you also conduct experiments in the 5-bit range with a 96-core processor))

**Comment by jonathanferreiras** [comment]
I believe I was confused. The number of bits would not be the challenge number, but rather how many bits are left to find? Example, in challenge 66 I would put how many bits? And how would you know the number of bits of the next challenges?

**Comment by albertobsd** [comment]
Default subrange thread is 0x100000000 so every thread start from your initial range to that value plus 32 bits.
Let's to said 0x100 to 0x100000100 -1 First thread
Second thread is from 0x100000100 to 0x200000100 - 1 
 Etc.....
Minimum sub range value is 0x400 
This is -n 0x400 or -n 1024 

Any value lower than it it's inefficient.
So in your case you should chose values larger than 32 bits or set your -n value to 0x400 and you minimum range from 0x100 to 0x500 and number of threads to 1
-t 1 or not -t at all defual thread number is 1.

About the -b 9 or -b 10  you should tell us what address you targeted to check if the range is 9 or 10 bits

**Comment by jonathanferreiras** [comment]
Thank you my friend. Now I understand. 
Congratulations on the project.
