### ISSUE TITLE
Input range from a file

### ISSUE THREAD

**Issue by LDogi** [albertobsd/keyhunt#314]
Hi Alberto, is it possible to scan several specific key ranges at once? let's say I have 1000 specific key ranges in myrange.txt file and want to scan each range sequentially.
it would be nice if that feature could be added. Thank You

**Comment by albertobsd** [comment]
Hi.
I am not goint to add anything that doesn't bring more performance.

what you are looking for can be achieved with bash or with python, easy read a line from the file and pass it as Argument to keyhunt.
