### ISSUE TITLE
Frozen process

### ISSUE THREAD

**Issue by mrantonion** [albertobsd/keyhunt#32]
Dear Alberto!

Smth strange goes on when i'm trying to run this code.
![keyhunt_001](https://user-images.githubusercontent.com/78864485/113839843-bc01f480-9798-11eb-9212-d6768b8108e6.PNG)
I run this code and nothing happens, no speed per second, no new range displayed.... But the CPU utilization is good (3 threads are used on 100%).
But if I run smth like searching 64th or 120th puzzle everything goes well.
Why this can occur?

**Comment by albertobsd** [comment]
You are testing 136K publickeys you need to add some K factor check the readme please i suggest 
-k 128
To start but you can run it with more RAM to get better speed

**Comment by mrantonion** [comment]
Dear Alberto. I didn't hurry to reply to you. I wanted to check weather the -k option will work or not. But unfortunately it didn't help to solve the problem. May be i should install new version as of 30th of March.. I don't know... Very strange...
The command line i used is:
./keyhunt -f allpubkeys.txt -m bsgs -r 1:ffffffffffffffffff -k 24 -t 7 -s 20 -p ./Pfile.bin
(a low value of -k was entered in order to check quickly the functionality)
![keyhunt_002](https://user-images.githubusercontent.com/78864485/113929481-ca7ff880-97f8-11eb-8311-b8d16ad9b05d.PNG)

**Comment by albertobsd** [comment]
In that case please use a file with a less number of publickeys, some 50 or 100 publickeys will be enough. the speed of the BSGS mode decrease with the number of keys that your input file have.

**Comment by mrantonion** [comment]
Thank you very much, Alberto! And excuse me for annoying :)

**Comment by mrantonion** [comment]
It seems to me that i have understood what's up. The calculations are processing but very-very slowly due to huge amount of public keys. It was a bit strange for me as i remember that you've been writing that you've tried 20K keys and got a speed of Tera-, Peta- or smth like this. I tried xpoint mode and obtained a speed of 1,5Mkey/s ))
Hence we can make a conclusion (by comparing VanitySearch using search by address and -bsgs mode using search by public key) that keyhunt is devilishly useful for searching 1 address by public key in a specified range. Searching for a list of addresses/public keys is useless in both cases. :)

**Comment by albertobsd** [comment]
Yes it was 20 000 publickeys at 200  @Gigakeys/s
![IMG_20210408_075738_505](https://user-images.githubusercontent.com/17832765/114030605-30dc3980-9840-11eb-9b79-fb799dda5d92.jpg)

**Comment by mrantonion** [comment]
Step by step i involving in understanding the process of searching ))
My further 120K file compressed onto 20K public addresses with balance as you do have.
I see that these addresses have the first mined coins (most of them have 50 BTC), but to determine the range of searching these addresses is still a difficult problem. :)

**Comment by dem10** [comment]
The range of keys you cannot find unless it was deliberately disclosed, you can only guess that the range of addresses with 50 bitcoins is from 254 to 256 .

**Comment by mrantonion** [comment]
To "see how many bits your private key is" for this moment is rather difficult for me to understand. :) I will just believe you that those addresses are in 254...256 bit range. As i've understood it's just need to add a "-b 254" argument in command line (then "-b 255"...) at that is all?

**Comment by dem10** [comment]
You cannot know how many bits the private key has. In the puzzle, this is intentionally open. But knowing the public key, you cannot know the key space.

**Comment by mrantonion** [comment]
> The range of keys you cannot find, unless it was deliberately disclosed, you can only guess that the range of addresses with 50 bitcoins is from 254 to 256 bits .in principle, you can download early versions of the bitcoin core 0.1-0.1.3, extract the priv key of the address and see how many bits your private key is.

With all respect to all written above i'd like to add a POV that the range of 2^253 is just a 12,5% of the whole range. Thus the scanning of whole range neither scanning the 2^254...2^256 has no difference (or it just give a 12.5% less performance rather than scanning the whole range). It both cases the result is zeroth )))

**Comment by mrantonion** [comment]
I just wanted to say that in case of searching for 50BTC-wallets there's no difference neither to scan the whole range nor to scan 2^254...256 range. Sorry for my English :)

**Comment by mrantonion** [comment]
Dear Alberto. Could you explain am i right or not? :)
Look. We are (i do) searching for 120th puzzle with a speed of 5*10^14 keys/thread/second. So to pass all the range (with 1 thread) we need 2^119 divide the speed. It equals near 10^21 seconds. The probability of finding the 1 key is 1/(10^21). **Or reversing: 10^21 to scan for 1 key.**

Thus extracting the public keys from blockchain we have near (supposedly) 20K keys. The speed of searching lowers approx. 10 times down. Suppose it will be 5*10^13 keys/thread/second. But we need to scan the full range from 1 to 2^256. So we need 2^256 divide the speed. It equals near 2*10^63 second. The probability of finding any key is 20000/(2*10^63). **Reversing: 10^59 to scan for 1 key.**   
Thus what is the reason to search using public keys in full range if there exist a huge probability to search for 120th puzzle?
Smth like this :)

**Comment by albertobsd** [comment]
This is the times of resolutions of all the puzzlez
```
Puzzle 64 @ 1 Megakeys/s  (10^6):       292471 years
Puzzle 64 @ 1 Gigakeys/s  (10^9):       292 years
Puzzle 64 @ 1 Terakeys/s  (10^12):      0 years

Puzzle 120 @ 1 Megakeys/s  (10^6):      21074771622667996462833 years
Puzzle 120 @ 1 Gigakeys/s  (10^9):      21074771622667996462 years
Puzzle 120 @ 1 Terakeys/s  (10^12):     21074771622667996 years
Puzzle 120 @ 1 Petakeys/s  (10^15):     21074771622667 years
Puzzle 120 @ 1 Exakeys/s  (10^18):      21074771622 years
Puzzle 120 @ 1 Zettakeys/s  (10^21):    21074771 years
Puzzle 120 @ 1 Yottakeys/s  (10^24):    21074 years
Puzzle 125 @ 1 Megakeys/s  (10^6):      674392691925375886810658 years
Puzzle 125 @ 1 Gigakeys/s  (10^9):      674392691925375886810 years
Puzzle 125 @ 1 Terakeys/s  (10^12):     674392691925375886 years
Puzzle 125 @ 1 Petakeys/s  (10^15):     674392691925375 years
Puzzle 125 @ 1 Exakeys/s  (10^18):      674392691925 years
Puzzle 125 @ 1 Zettakeys/s  (10^21):    674392691 years
Puzzle 125 @ 1 Yottakeys/s  (10^24):    674392 years
Puzzle 130 @ 1 Megakeys/s  (10^6):      21580566141612028377941058 years
Puzzle 130 @ 1 Gigakeys/s  (10^9):      21580566141612028377941 years
Puzzle 130 @ 1 Terakeys/s  (10^12):     21580566141612028377 years
Puzzle 130 @ 1 Petakeys/s  (10^15):     21580566141612028 years
Puzzle 130 @ 1 Exakeys/s  (10^18):      21580566141612 years
Puzzle 130 @ 1 Zettakeys/s  (10^21):    21580566141 years
Puzzle 130 @ 1 Yottakeys/s  (10^24):    21580566 years
Puzzle 135 @ 1 Megakeys/s  (10^6):      690578116531584908094113865 years
Puzzle 135 @ 1 Gigakeys/s  (10^9):      690578116531584908094113 years
Puzzle 135 @ 1 Terakeys/s  (10^12):     690578116531584908094 years
Puzzle 135 @ 1 Petakeys/s  (10^15):     690578116531584908 years
Puzzle 135 @ 1 Exakeys/s  (10^18):      690578116531584 years
Puzzle 135 @ 1 Zettakeys/s  (10^21):    690578116531 years
Puzzle 135 @ 1 Yottakeys/s  (10^24):    690578116 years
Puzzle 140 @ 1 Megakeys/s  (10^6):      22098499729010717059011643709 years
Puzzle 140 @ 1 Gigakeys/s  (10^9):      22098499729010717059011643 years
Puzzle 140 @ 1 Terakeys/s  (10^12):     22098499729010717059011 years
Puzzle 140 @ 1 Petakeys/s  (10^15):     22098499729010717059 years
Puzzle 140 @ 1 Exakeys/s  (10^18):      22098499729010717 years
Puzzle 140 @ 1 Zettakeys/s  (10^21):    22098499729010 years
Puzzle 140 @ 1 Yottakeys/s  (10^24):    22098499729 years
Puzzle 145 @ 1 Megakeys/s  (10^6):      707151991328342945888372598701 years
Puzzle 145 @ 1 Gigakeys/s  (10^9):      707151991328342945888372598 years
Puzzle 145 @ 1 Terakeys/s  (10^12):     707151991328342945888372 years
Puzzle 145 @ 1 Petakeys/s  (10^15):     707151991328342945888 years
Puzzle 145 @ 1 Exakeys/s  (10^18):      707151991328342945 years
Puzzle 145 @ 1 Zettakeys/s  (10^21):    707151991328342 years
Puzzle 145 @ 1 Yottakeys/s  (10^24):    707151991328 years
Puzzle 150 @ 1 Megakeys/s  (10^6):      22628863722506974268427923158445 years
Puzzle 150 @ 1 Gigakeys/s  (10^9):      22628863722506974268427923158 years
Puzzle 150 @ 1 Terakeys/s  (10^12):     22628863722506974268427923 years
Puzzle 150 @ 1 Petakeys/s  (10^15):     22628863722506974268427 years
Puzzle 150 @ 1 Exakeys/s  (10^18):      22628863722506974268 years
Puzzle 150 @ 1 Zettakeys/s  (10^21):    22628863722506974 years
Puzzle 150 @ 1 Yottakeys/s  (10^24):    22628863722506 years
Puzzle 155 @ 1 Megakeys/s  (10^6):      724123639120223176589693541070266 years
Puzzle 155 @ 1 Gigakeys/s  (10^9):      724123639120223176589693541070 years
Puzzle 155 @ 1 Terakeys/s  (10^12):     724123639120223176589693541 years
Puzzle 155 @ 1 Petakeys/s  (10^15):     724123639120223176589693 years
Puzzle 155 @ 1 Exakeys/s  (10^18):      724123639120223176589 years
Puzzle 155 @ 1 Zettakeys/s  (10^21):    724123639120223176 years
Puzzle 155 @ 1 Yottakeys/s  (10^24):    724123639120223 years
Puzzle 160 @ 1 Megakeys/s  (10^6):      23171956451847141650870193314248525 years
Puzzle 160 @ 1 Gigakeys/s  (10^9):      23171956451847141650870193314248 years
Puzzle 160 @ 1 Terakeys/s  (10^12):     23171956451847141650870193314 years
Puzzle 160 @ 1 Petakeys/s  (10^15):     23171956451847141650870193 years
Puzzle 160 @ 1 Exakeys/s  (10^18):      23171956451847141650870 years
Puzzle 160 @ 1 Zettakeys/s  (10^21):    23171956451847141650 years
Puzzle 160 @ 1 Yottakeys/s  (10^24):    23171956451847141 years
Puzzle 256 @ 1 Megakeys/s  (10^6):      1835871531540401373407708412745559168131740612197318060720331403 years
Puzzle 256 @ 1 Gigakeys/s  (10^9):      1835871531540401373407708412745559168131740612197318060720331 years
Puzzle 256 @ 1 Terakeys/s  (10^12):     1835871531540401373407708412745559168131740612197318060720 years
Puzzle 256 @ 1 Petakeys/s  (10^15):     1835871531540401373407708412745559168131740612197318060 years
Puzzle 256 @ 1 Exakeys/s  (10^18):      1835871531540401373407708412745559168131740612197318 years
Puzzle 256 @ 1 Zettakeys/s  (10^21):    1835871531540401373407708412745559168131740612197 years
Puzzle 256 @ 1 Yottakeys/s  (10^24):    1835871531540401373407708412745559168131740612 years
```

I know there is not puzzle 256 but  that is the time to scan only the 256 bit space.
