### ISSUE TITLE
MacOS build errors

### ISSUE THREAD

**Issue by pbies** [albertobsd/keyhunt#322]
I download repo:

git clone https://github.com/albertobsd/keyhunt.git

Then enter folder and run "make": cd keyhunt ; make

I am getting these errors while doing "make" for keyhunt:

[errors.txt](https://github.com/user-attachments/files/16194638/errors.txt)

Seems like on ARM MacOS keyhunt can't be compiled.

**Comment by albertobsd** [comment]
Search on closed or open issues for MAC some other users work arount this. I don't have time and Also i don't have Any apply product.
