### ISSUE TITLE
Offtopic question (Random or continuously search: which one is better?) 

### ISSUE THREAD

**Issue by mrantonion** [albertobsd/keyhunt#33]
As most of all i interact with Alberto's repository, i decided to publish this issue here.
Does anyone know what kind of searching is better mathematically? Continuously or random?
For example in the hypothetical range of 0...100 with can forcibly search diving range on 2. I.e. from 0 to 1, then from 99 to 100; Next from 50 to 51. Then from 24 to 25 and from 74 to 75... etc..
Or we can simply run random mode and wait for results.
What is better particularly from mathematical point of view?

**Comment by sezginyildirim91** [comment]
If you enter the `-n 10000` command, you will search for hex equivalent `2710`. If you enter it together with `-R`, it searches from the end of any randomly generated location to `2710` and switches to a different location.

**Example:**

./keyhunt -t 4 -f tests/64.rmd -m rmd160 -n 1000 -r 1:FFFFF -R

**Comment by mrantonion** [comment]
Thank you very much for example and for explanation, it's useful for me.
But i'd like to understand what type of searching is better? Fully random or (as in your example) with "-n" argument?

**Comment by sezginyildirim91** [comment]
My point of view.

In terms of philosophy: Just as things work in Quantum, the same adventure of possibilities is valid here.

**Comment by mrantonion** [comment]
Thank you very much :)

**Comment by albertobsd** [comment]
I think that ranom search is better, but from a point o view from statistic both will have exact same probability to get success.

**Comment by mrantonion** [comment]
Thank you, Alberto, for reply!

**Comment by mrantonion** [comment]
May be it will be interesting and useful:
Some time ago i've made an excel macro that generated random numbers in a range for example 0...100 of 0...1Million (i don't remember).
And i've got very interesting results. The quantity of iterations when _all_ numbers will be generated is near 30% more than the quantity of numbers. This means that to generate all nonrepeatable numbers from 0 to 100 needs near 130 iterations. So we lost 30% of generation power...
So by this reason i asked about mathematical point of view. But i don't know weather this rule works with large numbers. May be when we scan the range from 2^119 to 2^120 this rule doesn't work.))))

**Comment by albertobsd** [comment]
in my personal opinion this doesn't matter in large ranges, the odds of repeat some range is the same odds of hit the key.

BTW i will add the option of not repeat ranges and keep log of the reanges that were already tested.

**Comment by mrantonion** [comment]
I fully agree with you. The probability of repeating in such ranges is extremely low.

> BTW i will add the option of not repeat ranges and keep log of the ranges that were already tested.
It will be very cool and useful!!!
