### ISSUE TITLE
Puzzle 10 can't find private key with `-b 10` argument but finds it with `-b 9` argument  

### ISSUE THREAD

**Issue by DeepDoge** [albertobsd/keyhunt#335]
I was testing to see what happens when we find the key.

So I got the puzzle 66 command:
```
./keyhunt -m address -f tests/66.txt -b 66 -l compress -R -q -s 10
```

And converted it to puzzle 10 command:
```
./keyhunt -m address -f tests/10.txt -b 10 -l compress -R -q -s 10
```
Also created the `./tests/10.txt` file with the address `1LeBZP5QCwwgXRtmVUvTVrraqPUokyLHqe`

I was expecting it to find the private key instantly but it didn't find anything.
Then I changed the bit range to 9:
 ```
./keyhunt -m address -f tests/10.txt -b 9 -l compress -R -q -s 10
```

And it instantly found the address.

Is this how it's suppose to be, or there is an issue?

**Comment by albertobsd** [comment]
default subrange value is 0x100000000 that is 32 bits range, for a larger range than 32 bits that value is OK, but for small ranges like 10 bits (9 bits becuase it is from 0x200 to 0x400) that value is not OK. The minumun `-n` value is 0x400 you can use it for small ranges

Now `-R` value selected a random value from 0x200 to 0x400 and start from it, it usually don't 0x200 at the first try you need some other tries to hit the 0x202 privatekey.

if you add the -n 0x400 it would hit the keys almost instantly:

![image](https://github.com/user-attachments/assets/7bad3042-762b-4a78-8e2e-577ae08e2566)
