### ISSUE TITLE
Public Key from crackBTCwallet

### ISSUE THREAD

**Issue by luckyalab** [albertobsd/keyhunt#34]
Hello,
Q1
 We extract cKey, Public Key and Public address using your other program crackBTCwallet  command get_mkey_ckey. 
Can we use the extracted public key  0113c403exxxecbcb83e93xxxxxxxxx1b04d9479bfc0864ef46c49a6caxxxb6f1f as input for bsgs scenario in key hunt?

Q2
-r range is not working
I input  -r 800000000000000000000000000000:900000000000000000000000000000
where as the program shows
[+] Min range: 800000000000000000000000000000
[+] Max range: ffffffffffffffffffffffffffffff

Thank you and please advise

**Comment by dem10** [comment]
If file wallet.dat is not encrypted, you can already extract the private key. Public keys can only start at 04 uncompressed and 02 03 compressed. 0113c403exxxecbcb83e93xxxxxxxxx1b04d9479bfc0864ef46c49a6caxxxb6f1f this is most likely an encrypted key and you cannot use it.

**Comment by luckyalab** [comment]
> 
> 
> If file wallet.dat is not encrypted, you can already extract the private key. Public keys can only start at 04 uncompressed and 02 03 compressed. 0113c403exxxecbcb83e93xxxxxxxxx1b04d9479bfc0864ef46c49a6caxxxb6f1f this is most likely an encrypted key and you cannot use it.Tool crackBTCwallet is designed to try to guess the password for an encrypted file wallet.dat .

Public key starts with 2. I had changed to 1
028c............................

**Comment by dem10** [comment]
Throw us a screenshot of what doesn't work for you. The -r flag seems to have always worked well. Well, how are you sure that your public key is in the 800000000000000000000000000000:900000000000000000000000000000 range?

**Comment by luckyalab** [comment]
> 
> 
> Throw us a screenshot of what doesn't work for you. The -r flag seems to have always worked well. Well, how are you sure that your public key is in the 800000000000000000000000000000:900000000000000000000000000000 range?

![image](https://user-images.githubusercontent.com/82208222/114170199-17abb980-9922-11eb-897d-29679b0293e3.png)
Screen shot attached for you reference
As I could not find save progress option , I was planning to run range of keys one at at  time :)

**Comment by luckyalab** [comment]
> 
> 
> Hello,
> Q1
> We extract cKey, Public Key and Public address using your other program crackBTCwallet command get_mkey_ckey.
> Can we use the extracted public key 0113c403exxxecbcb83e93xxxxxxxxx1b04d9479bfc0864ef46c49a6caxxxb6f1f as input for bsgs scenario in key hunt?
> 
> Q2
> -r range is not working
> I input -r 800000000000000000000000000000:900000000000000000000000000000
> where as the program shows
> [+] Min range: 800000000000000000000000000000
> [+] Max range: ffffffffffffffffffffffffffffff
> 
> Thank you and please advise

waiting for @albertobsd  to confirm if I can use the public key from crackBTCwallet  program TIA

**Comment by dem10** [comment]
Why do you write 2 flags? You have -r and flag -b. Remove the flag -b 120

**Comment by luckyalab** [comment]
> 
> 
> Why do you write 2 flags? You have -r and -b flags. Remove the flag -b 120

OK, Thank You

**Comment by luckyalab** [comment]
> 
> 
> Why do you write 2 flags? You have -r and -b flags. Remove the flag -b 120
![image](https://user-images.githubusercontent.com/82208222/114172299-ff896980-9924-11eb-8ff3-8a82bf4db1af.png)
Removed the -b flag , now the range is not displaying

**Comment by dem10** [comment]
Now the program is looking for a key in the range you specified 800000000000000000000000000000:900000000000000000000000000000. If you want to make sure of this, uncheck the -q flag. But it will not show the speed and the number of processed keys.

**Comment by albertobsd** [comment]
> Hello,
> Q1
> We extract cKey, Public Key and Public address using your other program crackBTCwallet command get_mkey_ckey.
> Can we use the extracted public key 0113c403exxxecbcb83e93xxxxxxxxx1b04d9479bfc0864ef46c49a6caxxxb6f1f as input for bsgs scenario in key hunt?

Ok that publickey seen extrange, maybe the version of your wallet file have the publickey at different offset, the program show you the correct address?

Maybe the program (get_mkey_ckey) is returned a Incorrect publickey 

Best regard

**Comment by luckyalab** [comment]
> 
> 
> > Hello,
> > Q1
> > We extract cKey, Public Key and Public address using your other program crackBTCwallet command get_mkey_ckey.
> > Can we use the extracted public key 0113c403exxxecbcb83e93xxxxxxxxx1b04d9479bfc0864ef46c49a6caxxxb6f1f as input for bsgs scenario in key hunt?
> 
> Ok that publickey seen extrange, maybe the version of your wallet file have the publickey at different offset, the program show you the correct address?
> 
> Maybe the program (get_mkey_ckey) is returned a Incorrect publickey
> 
> Best regard

@albertobsd Thank you for the quick response. The program get_mkey_ckey has returned the following example public key 
02907e551a13f3c6f4f4b6a8e05decf53e126bdcffac136dc2b01530ac619a7841. 
Can I use this public key in keyhunt for flag bsgs scenario.
and should I use - b flag ?
Best Regards TIA

**Comment by dem10** [comment]
-b is the full range. For example -b 120 and the program will look for a key from 8......0000 to ffffff....fffff. If you specify the -r flag this is the range you want 80000000000000000000000000000:900000000000000000000000000000

**Comment by albertobsd** [comment]
Only use it is the publickeys have the correct length 02 y 03 publcikeys have 66 hex characters and 04 have 130 hex characters. Also check if the address have balance.

Yes you can omit the -b and setup a custom range o just omit both of them, we don't have way to know the range. You maybe want to try luck with `-b 256` 50% of the keys are there

**Comment by dem10** [comment]
There is a theory and only a theory that the early keys could have been 254 bit. So perhaps the search should be done in the ranges 254-256. I have a bitcoin kernel 0.1.3. I will extract the key and take a look, but I think it will not help much.

**Comment by luckyalab** [comment]
> 
> 
> Only use it is the publickeys have the correct length 02 y 03 publcikeys have 66 hex characters and 04 have 130 hex characters. Also check if the address have balance.
> 
> Yes you can omit the -b and setup a custom range o just omit both of them, we don't have way to know the range. You maybe want to try luck with `-b 256` 50% of the keys are there

Thank you very much @albertobsd .  

yes the address has a small balance
I will check with -b 256

2 more questions
1. Soes these program always run random even if -R flag is not added. is there way to run it sequentially?
2. Is there way to save progress? so that we can run the program later or move to higher configuration system 
Regards
Thank you

**Comment by albertobsd** [comment]
![IMG_20210128_181326_814](https://user-images.githubusercontent.com/17832765/114179363-7c581b80-9904-11eb-8027-e361c716a352.jpg)

I run many test with different RNG ssl included and in most of then i get some well distributed keys, the imagen is a test of 1 milliok of random keys look that every bit less is half % of the previous one, and is that every bit space have the half of size of the previous (in descendent mode from 256 to 1, no the other way around)

**Comment by luckyalab** [comment]
@ @albertobsd 

sudo ./keyhunt -m bsgs -f  mypublicaddress.txt  -b 256 -t 3 -k 170  -q -p ./Pfile.bin
--




> 
> 
> -b is the full range. For example -b 120 and the program will look for a key from 80000......0000 to ffffff....fffff. If you specify the -r flag this is the range you want 80000000000000000000000000000:900000000000000000000000000000 or 80000000000000000000000000000:850000000000000000000000000000

Thank you @dem10 Got it :)

**Comment by luckyalab** [comment]
when I execute 

sudo ./keyhunt -m bsgs -f  tests/120.txt  -b 256 -t 3 -k 170  -q -p ./Pfile.bin

the output
question is the range is showing 
[+] Min range: 8000000000000000000000000000000000000000000000000000000000000000
[+] Max range: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

Is this OK?

![image](https://user-images.githubusercontent.com/82208222/114180812-3ca72900-9930-11eb-8e0d-a93598098614.png)

**Comment by dem10** [comment]
It seems abnormal to me - the end of the key space is fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140

**Comment by luckyalab** [comment]
> 
> 
> It seems abnormal to me - the end of the key space is fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140

waiting for @albertobsd response to see if there is an issue

**Comment by dem10** [comment]
the program is clearly confusing something.

**Comment by albertobsd** [comment]
> the program is clearly confusing something.the last key is(max range) fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140

Yes that will be te max value yes that is an issue in my code, i will solve it.

Thanks!

**Comment by luckyalab** [comment]
> 
> 
> > the program is clearly confusing something.the last key is(max range) fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140
> 
> Yes that will be te max value yes that is an issue in my code, i will solve it.
> 
> Thanks!

Thanks will wait for the code update.
Can you please respond to these 2 questions

1. Does these program always run random even if -R flag is not added. is there way to run it sequentially?
2. Is there way to save progress? so that we can run the program later or move to higher configuration system
Regards

Regards

**Comment by dem10** [comment]
I can only answer the first question, if there is no -R flag, then the program starts from the smallest key of the specified or the smallest key of the range and moves up.

**Comment by luckyalab** [comment]
> 
> 
> I can only answer the first question, if there is no -R flag, then the program starts from the smallest key of the specified or the smallest key of the range and moves up.

Thank you

**Comment by albertobsd** [comment]
> 2. Is there way to save progress? so that we can run the program later or move to higher configuration system

Yes i will implement that but im looking the best way to do it, maybe i will change the way that the random mode works because saving different randoms ranges will fill all your  storage space quickly. There is no disk in  the Earth enough to save that amount of ranges so i need only start to scan a new range every 1 billlions of iterations or something like that.

Is reallly a problem i need to change a lot of code

**Comment by dem10** [comment]
I'm not an encoder. But maybe it will be possible to make the random range not completely random, but with a shift of several keys in the header? 8 +20 check... 8+30 check

**Comment by luckyalab** [comment]
> 
> 
> > 1. Is there way to save progress? so that we can run the program later or move to higher configuration system
> 
> Yes i will implement that but im looking the best way to do it, maybe i will change the way that the random mode works because saving different randoms ranges will fill all your storage space quickly. There is no disk in the Earth enough to save that amount of ranges so i need only start to scan a new range every 1 billlions of iterations or something like that.
> 
> Is reallly a problem i need to change a lot of code

I do understand the gravity of the problem.

My suggestion would be to start with saving progress for sequential search.
start=0000000000000000000000000000000000000000000000000000000000000001
next=0000000000000000000000000000000000000000000000000001159800000001
end=FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364140
save next value every 60 secs. 

Thank you
Regards

**Comment by albertobsd** [comment]
well yes for no random option that is good, the problem is that most users like random because they feel that it has better chances to hit some key.

**Comment by albertobsd** [comment]
> I'm not an encoder. But maybe it will be possible to make the random range not completely random, but with a shift of several keys in the header? 8 +20 check... 8+30+1 check.Thus, this search is shifted every cycle by +1 address ... or something like that.

Yes that is a good option too, thanks!

**Comment by luckyalab** [comment]
> 
> 
> well yes for no random option that is good, the problem is that most users like random because they feel that it has better chances to hit some key.

 I agree. To start save the progress of sequential search.  We will test and let you know if any issues and meanwhile you can work out the logic for random version :)

**Comment by dem10** [comment]
you mean a BitCrack. If you search with a shift then there will never be a repetition. If you search in a random order and save all the points, then I think the computer will overflow very quickly.

**Comment by mrantonion** [comment]
Reading all the messages, it seems to me that people are going to live eternally. :) Myself included.

**Comment by mrantonion** [comment]
> I run many test with different RNG ssl included and in most of then i get some well distributed keys, the imagen is a test of 1 milliok of random keys look that every bit less is half % of the previous one, and is that every bit space have the half of size of the previous (in descendent mode from 256 to 1, no the other way around)

Very interesting conclusion requiring attention...

**Comment by luckyalab** [comment]
> 
> 
> > the program is clearly confusing something.the last key is(max range) fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140
> 
> Yes that will be te max value yes that is an issue in my code, i will solve it.
> 
> Thanks!

Good Morning @albertobsd 
Is the max range issue fixed?
Thank You
Regards
