### ISSUE TITLE
"Sorting elements" string

### ISSUE THREAD

**Issue by mrantonion** [albertobsd/keyhunt#35]
Dear Alberto!
Can you tell me what is the meaning of "Sorting elements" string?
It takes a lot of time to proceed this step. Is it possible to fasten it somehow?
 
![keyhunt_003](https://user-images.githubusercontent.com/78864485/114265285-a4c14200-99f8-11eb-8d7b-138f3e896594.PNG)

**Comment by mrantonion** [comment]
P.s. Very strange situation. After 1 hour of "sorting" processing the remote server (i'm using remote services) reports "connection error" and the remote session disconnects. Very pity ((( And how to start searching with "200M elements" i don't know. Probably i need my own home server ))

**Comment by albertobsd** [comment]
Please avoid using bsgs mode with more of 100K publickeys that process of sorting is fast even with 200 Millions items.

Did you use the -q option right?

Please alwayss add your fulln line of execution. 
-  `-q` option quiet the thread output
- speed is not showing until one thread finish his process.

The las one is made in that way to not show 0 keys/s

Wit more of 100 Millions publickeys please use `xpoint` mode.

Best regards

**Comment by mrantonion** [comment]
Sorry for inconvenience. Yes, I used the -q option. I used -k 960 for the first time, then a terminated process and run again. And it took only 50 minutes to start. The problem is solved! Excuse once again.

**Comment by albertobsd** [comment]
is ok, i will Add some ".. Done!" string when the sorting process will be complete.

Please don't close this issue until that par was done.

Regards!

**Comment by albertobsd** [comment]
Solved
