### ISSUE TITLE
Compressed Public Key in bsgs mode

### ISSUE THREAD

**Issue by luckyalab** [albertobsd/keyhunt#38]
Hello @albertobsd ,
Can we use this public key (66 Characters) in bsgs mode?
This key was extracted using crackbtc. 
0313c402e03becbcc93e93fadd8eb9d1b04c7479bfc0864fff6c49a5ca233b6f2f

Thank you
Regards

**Comment by albertobsd** [comment]
Yes you can :) I need to update the README to specify that, please don't close this issue until the README  was updated.

Regards!

**Comment by luckyalab** [comment]
> 
> 
> Yes you can :) I need to update the README to specify that, please don't close this issue until the README was updated.
> 
> Regards!

Thank you. will not close until you update.

**Comment by luckyalab** [comment]
> 
> 
> Yes you can :) I need to update the README to specify that, please don't close this issue until the README was updated.
> 
> Regards!

 A quick followup question. Can I use both compressed and uncompressed keys in the same input file?

Thank you
Regards

**Comment by albertobsd** [comment]
> A quick followup question. Can I use both compressed and uncompressed keys in the same input file?

Yes, both, mixed in the same file :)

**Comment by luckyalab** [comment]
> 
> 
> > A quick followup question. Can I use both compressed and uncompressed keys in the same input file?
> 
> Yes, both, mixed in the same file :)

Ok :)

**Comment by albertobsd** [comment]
Solved, is now in the readme.

**Comment by luckyalab** [comment]
Thank you
Regards
