### ISSUE TITLE
Ram usage increased during the program run on Windows 10.

### ISSUE THREAD

**Issue by kanhavishva** [albertobsd/keyhunt#4]
Thank you for the codes in c especially. Somehow I managed to build it on Windows 10 but there is one problem: Ram usage increased during the program run, and eventually after few minutes my whole 16GB got eaten and the computer froze. Maybe this is caused by the platform change or maybe some memory re-allocation issue.
Is there anyone who is facing the same problem?

**Comment by albertobsd** [comment]
Hi, before all, thanks for using my program.

Just to know what enviroment did you use to compile it in windows 10? cgywin? This to try to reproduce the same behaivor than you

Well i'm sure that my code don't have memory issues in Linux, one that all data was load the amount of memory is stable for all the time

btw, what mode are you using, if you load an address file what length is this file?

Kind regards

**Comment by kanhavishva** [comment]
Hi, I built it with mpir library [https://github.com/BrianGladman/mpir.git] for big numbers math. And changed the codes to work with Win32 threads instead of pthreads.

I have tested it with default address mode, -crypto btc, with some files of different sizes with different number of threads, even a 4MB addresses text file caused the same issue.

I guess some how it is allocating memory again and again in loop, thats why memory usage is increasing over the time.

Thank you.
Regards

**Comment by albertobsd** [comment]
Ok, maybe is some of the changes that you made, maybe is the mpir library I really don't know how those library manage the resources. a lot of maybes

Did you made some other modification to the code?

Can you publish you code? just to see what are your changes.

BTW the code work very well in linux i'm running some instances of keyhunt 24/7 and the memory keep stable, did you try ubuntu shell for windows 10? is avaible in windows store. Some friends compile keyhunt in that shell and nobody have those problems of memory.

Regards!

**Comment by kanhavishva** [comment]
I don't want to build it with linux shell for windows due to performance issue.
Here it is, I have pushed the visual studio 2019 project, you can lookout -> https://github.com/kanhavishva/keyhunt.git

Let me know if you found some mistakes(& I'm sure there is 😀).
Regards..

**Comment by kanhavishva** [comment]
Hi, I have found the reason behind the memory issue. This is not a library-related issue.
This is caused by repeatedly calling 'malloc' without calling 'free' in base58.c file. There are 3 malloc calls in the base58.c file.

I don't know how it is working on your system, maybe gcc compiler is detecting any memory allocation calls without free and puts the free calls in codes at compile time.

Well, now it is running with stable memory usage.

Thank you.
Best regards

**Comment by albertobsd** [comment]
Excellent thanks for debuging that part, I was a little bussy that why I don't reply before

I really don't test a lot the Address generation, I don't develop that part, i will report that issue to the correct developer, thanks a lot. When i change the code in my version y will close the this issue.

best regards!
