### ISSUE TITLE
BSGS mining implementation

### ISSUE THREAD

**Issue by Mafiasource** [albertobsd/keyhunt#42]
Hi there,

Awesome project you've developped! Really loving it.
More of a question not an issue because I simply lack the technical knowledge.
Would your BSGS algorithm be applicable to mining software and maybe achieve the same kind of performance of x petahashes/s?
To my knowledge i've never seen petahashes/s on even high end ASIC mining gear. (except when combined) Imagine mining with the performance of BSGS even on low-end hardware wouldn't that drastically increase the blockchain network's performance worldwide for the same amount of power used?

Just a thought, I'd love to read thoughts on this as well thanks!

**Comment by Mafiasource** [comment]
> Hi there,
> 
> Awesome project you've developped! Really loving it.
> Would your BSGS algorithm be applicable to mining software and maybe achieve the same kind of performance of x petahashes/s?
> To my knowledge i've never seen petahashes/s on even high end ASIC mining gear. (except when combined) Imagine mining with the performance of BSGS even on low-end hardware wouldn't that drastically increase the blockchain network's performance worldwide for the same amount of power used.
> 
> Just a thought, I'd love to read thoughts on this as well thanks!

**Comment by albertobsd** [comment]
Sorry no, that can't be done in that way, Mining only depend of sha256 process and there is no easy way to get more speed (only more processor (CPU/GPU)  power or specailized hardware) and the bsgs mode depend of math behind the Eliptic Curve and it can't be use to mining anything.

**Comment by garingdest** [comment]
how to increase the power for m rmd
