### ISSUE TITLE
Is not compiling in Android Termux

### ISSUE THREAD

**Issue by albertobsd** [albertobsd/keyhunt#45]
the new secp256k1 is not compiling in termux

sorry guys i will work in that.

**Comment by Mehdi3123** [comment]
Hi Alberto, I sent you some messages in that group of puzzles, but I did not receive a reply.  Why we used to work for Android, but now it can not be compiled !!.  You mentioned that it works on Termux.  Please solve this problem, you will satisfy everyone.  thanks for everything

**Comment by albertobsd** [comment]
> Hi Alberto, I sent you some messages in that group of puzzles, but I did not receive a reply. Why we used to work for Android, but now it can not be compiled !!. You mentioned that it works on Termux. Please solve this problem, you will satisfy everyone. thanks for everything

Sorry for not reply before, i left the channel in that momment. But as you see im back.

Im thinking in make an altertate keyhunt native, this is all the new features but with GMP, this will include all excepy the new speed :(

**Comment by albertobsd** [comment]
Compile with 

```make legacy```

compilation with termux is back!
