### ISSUE TITLE
how -R mode works ?

### ISSUE THREAD

**Issue by Noname400** [albertobsd/keyhunt#46]
the mode works permanently randomly or as in bitcrack.

**Comment by Noname400** [comment]
in bitkrak it works:
1.Random points are selected (for example 1,000,000 points)
00adf754734f7cf61a
2. to the point there is an increase (+1 +1 +1 and so on.)
0adf754734f7cf61a (+1)
0adf754734f7cf61в (+1)
0adf754734f7cf61с (etc.)

**Comment by albertobsd** [comment]
Each thread select his own base point to start and for modes address and rmd160 the search is one by one as you describe, but each N items the base point is changing for other random point Default N is 2^32 for address and rmd160, this is about 4.2 billions, you can setup the N value with `-n value`

**Comment by Noname400** [comment]
sorry but then it doesn't make sense.
Suppose N points are selected.
and that would go through consistently it will take a lot of time.
I understand that the implementation of such an algorithm for the GPU is justified.
but we are still working on the CPU and random search would probably be more relevant
puzzle 64:
(9223372036854775808 <Rand (N) <18446744073709551615)
maybe I don't understand something, excuse me.

**Comment by Mafiasource** [comment]
I'd like to add that running though 4.2b (default N) combinations in bsgs mode seems very reasonable and fast as it can run through that many combinations within a second before jumping to a new random base point am I correct?
