### ISSUE TITLE
pub2rmd -r Range of

### ISSUE THREAD

**Issue by sezginyildirim91** [albertobsd/keyhunt#47]
Hello Alberto

Wouldn't it be more efficient to search with the -r parameter in pub2rmd mode? In this state it looks like looking for a needle in the ocean. I thought it would be better if it searches by private key range.

Thanks.

**Comment by albertobsd** [comment]
The pub2rmd was another experiment there are more than 2^96 publickeys that can match a address or hash rmd160.

Yes you can specify range or bit range for tha mode too.

Btw find a needle in an ocean is more easy, the correct way to see this is looking an atom in the visible universe.

**Comment by sezginyildirim91** [comment]
Understood thanks.
