### ISSUE TITLE
xpoint mode & KEYFOUNDKEYFOUND.txt

### ISSUE THREAD

**Issue by dolaor** [albertobsd/keyhunt#49]
Hi Alberto,

I have made a file "40_xpoints.txt" with 1000000 values of the puzzle 40. 
After running the xpoint mode with this command: ./keyhunt -m xpoint -f 40_xpoints.txt -n 65536 -t 8 -b 40 -q -R
I get a strange output for the pubkeys on the screen and in KEYFOUNDKEYFOUND.txt.

PrivKey: 6afe8390d6
pubkey: 303237373430313264653064656231376535643837363333303461623039366463
PrivKey: 75ea480456
pubkey: 303262326534306438646334386535303533356432313535346161323666653839
PrivKey: 79e7570856
pubkey: 303336373332653635636336386438323236303832366238323337646135646433
PrivKey: 781bac6bd6
pubkey: 303264336632393866343966663763373766646239363466633466343966396430
PrivKey: 7587523a56
pubkey: 303338633166363239343461383263313730643462303865616432633166386664
PrivKey: 7f2052e956
pubkey: 303361323236396137643365333536636337633762353266316266326566336638
...

**Comment by albertobsd** [comment]
Is not strange the puzzle 40 is always found in a second with subtracted keya what is your question?

**Comment by dolaor** [comment]
With the previous version it is working correctly.
I get the right pubkeys in KEYFOUNDKEYFOUND.txt.

PrivKey: 00000000000000000000000000000000000000000000000000000080128a4bd6
pubkey: 0324a1f378e2bc51f4ab8223fb91cd6a9f02c756db098ddd11792aa765293aada5
PrivKey: 000000000000000000000000000000000000000000000000000000a1b578fad6
pubkey: 03a816d3ad74454aa0062acff8fa06e2122fc0193945b045cc964f539e54cc9804
PrivKey: 000000000000000000000000000000000000000000000000000000a5c60593d6
pubkey: 031e89013dfac0dcc93b3f2a8f53bf67d0fc1ee6b2f2672cbc1f62eb3c04bd20ef
PrivKey: 000000000000000000000000000000000000000000000000000000ca3b9951d6
pubkey: 0312221a9acbe2af6cb16bf163b1e64af9879e6bbd9c10d506474f4fc3e3128315
PrivKey: 0000000000000000000000000000000000000000000000000000008de50a0fd6
pubkey: 030bf40cba9bd6458fc8a7528f0d5e3ed58e9601a460ec7db452277db8e94fd40e
PrivKey: 000000000000000000000000000000000000000000000000000000d76b2ff6d6
pubkey: 0319db22563eb3c10926901e7e68ea0825f8cc4dd0c2ad87c9f3a2c7023f6c9f77
PrivKey: 000000000000000000000000000000000000000000000000000000f5fda42a56
pubkey: 0367f1d8b72d927acef0930eca8734a986d4bc1cc33c775c214faa8f2634090b14
PrivKey: 0000000000000000000000000000000000000000000000000000009a36036cd6
pubkey: 03706930562787770599d06da11da643eda67a3ce32b64cacd9ca24962e9a85777
PrivKey: 0000000000000000000000000000000000000000000000000000009a36036cd6
pubkey: 03706930562787770599d06da11da643eda67a3ce32b64cacd9ca24962e9a85777
PrivKey: 000000000000000000000000000000000000000000000000000000a41539ad56
pubkey: 0308d975f3689b35aad76003050b88d2f8c1a45dc3bbf4c6890a607691d2631078
PrivKey: 00000000000000000000000000000000000000000000000000000088299e3c56
pubkey: 022eb63f3873da964bd785c50d5da4708c437d8f07825681c53e861bcaa037eda0

**Comment by dolaor** [comment]
> 
> 
> Is not strange the puzzle 40 is always found in a second with subtracted keya what is your question?

The pubkeys in the KEYFOUNDKEYFOUND.txt are not correct in the last version. Therefore we can't get the index to make the operation to get the PrivKey.

**Comment by albertobsd** [comment]
Ohh yes i didn't notice the bug in the publickey, Is alredy solved in this commit 10609584377e29836ea686692c745fa43cdff2ca,

Can you update your code to check if this fix solve your issue?, BTW don't forget backup your custom file `40_xpoints.txt`

please letme know if it solve the problem for you.

**Comment by dolaor** [comment]
> 
> 
> Ohh yes i didn't notice the bug in the publickey, Is alredy solved in this commit [1060958](https://github.com/albertobsd/keyhunt/commit/10609584377e29836ea686692c745fa43cdff2ca),
> 
> Can you update your code to check if this fix solve your issue?, BTW don't forget backup your custom file `40_xpoints.txt`
> 
> please letme know if it solve the problem for you.

Yeah it is working now! The pubkeys are correct and I can find the index to do the math operation. I get the right PrivKey at the end!

Thank for the fix!
