### ISSUE TITLE
weird speed key/s???

### ISSUE THREAD

**Issue by johngalt13** [albertobsd/keyhunt#5]
Hi there,
thank you for your app. It looks interesting. But why it displays incorrect speed? 
I'm running it on Debian
Screenshot - https://drive.google.com/file/d/1Edr1Cl1XwyOOf20k2M9gx-JIbkIR0YsG/view?usp=sharing

**Comment by albertobsd** [comment]
Hi, thanks for use my code.

I need to find another work around to show the speed, BTW you set show the speed every 5 seconds but for your threads the time of the full cycle is around 145 - 150 seconds.

The speed counter only is update or count the keys every time that one thread complete a full cycle of N keys.
You use the same command that you use before but with -s 150 to show the speed only every 150 seconds. This will give time to the thread to finish his cycle and update the speed counter.

Please show your results and comment if this work for you. 

Kind regards!

**Comment by johngalt13** [comment]
> Hi, thanks for use my code.
> 
> I need to find another work around to show the speed, BTW you set show the speed every 5 seconds but for your threads the time of the full cycle is around 145 - 150 seconds.
> 
> The speed counter only is updated or count the keys every time that one thread complete a full cycle of N keys.
> You use the same command that you use before but with -s 150 to show the speed only every 150 seconds. This will give time to the thread to finish his cycle and update the speed counter.
> 
> Please show your results and comment if this work for you.
> 
> Kind regards!

Hi,
thank you for your reply. I did -s 150
screenshot - https://drive.google.com/file/d/1HMPeQLIcdUrPzVB3LMhnOVdb95ZA0SIr/view?usp=sharing
looks like nothing changed. still displays weird speed.

I have a few questions. Just wondering why you implemented the BSGS algorithm instead of Kangaroo? as I understand for BSGS needs around sqrt(n) memory while for Kangaroo it will 0.

**Comment by albertobsd** [comment]
Yes something change, you change the thread number in the firts case there are two threads and I sugested and wait time of 150, but now you are using six threads, now i can sugest to you a time of 450 for the value of -s

Remember the speed coun only is updated every time that one thread finish his cicle.

About the Pollard's rho algorimth i will implement latter today im working in a pool version for keyhunt and also in an android native version.

**Comment by johngalt13** [comment]
> Yes something change, you change the thread number in the firts case there are two threads and I sugested and wait time of 150, but now you are using six threads, now i can sugest to you a time of 450 for the value of -s
> 
> Remember the speed coun only is updated every time that one thread finish his cicle.
> 
> About the Pollard's rho algorimth i will implement latter today im working in a pool version for keyhunt and also in an android native version.

Wow. sounds good.
I did 2 cores/2 threads -s 150 - https://drive.google.com/file/d/1ZN62svvoC1YRx54N0R5mEVYWNWgbr8z-/view?usp=sharing is this correct?

**Comment by albertobsd** [comment]
Yes that speed is correct, 1.3 Terakeys/s
