### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Chesterfield007** [albertobsd/keyhunt#50]
Hi 
what are the warnings bro?
keyhunt.c: In function ‘int main(int, char**)’:                                                                         keyhunt.c:668:47: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]                                                                                          668 |     fprintf(stderr,"[E] error bloom_init for %u elements.\n",N);                                                      |                                              ~^              ~                                                        |                                               |              |                                                        |                                               unsigned int   uint64_t {aka long unsigned int}                         |                                              %lu

**Comment by albertobsd** [comment]
is about format printing is OK work with that warning, i will solve it later.

**Comment by Chesterfield007** [comment]
thx bro!!!!

**Comment by albertobsd** [comment]
Solved in last commit in Development Branch   7fdf0d62393114dc5cf684549e998ff80b7a758a

Plese update your code:
- Save all your files (substracted, bPTables, your own txt)
- delete the current folder
- Clone the respository with 
  `git clone https://github.com/albertobsd/keyhunt.git`
- Change to the development version with
  `git checkout development`
- Compile and test
