### ISSUE TITLE
Base Key out of range values

### ISSUE THREAD

**Issue by vhanghiuc** [albertobsd/keyhunt#51]
Hello,

When I run the program in _-m rmd160_ mode, with the -R flag, the base key is not in the desired range :
![image](https://user-images.githubusercontent.com/11025914/115023098-fcfbb680-9ec6-11eb-8df7-ed68c4d7f54f.png)

Without the  -R flag, is working normal

**Comment by dem10** [comment]
But why do you have the input file extension RMD? Nothing confuses you?-f test/64.rmd?

**Comment by albertobsd** [comment]
> But why do you have the input file extension RMD? Nothing confuses you?-f test/64.rmd?Perhaps extension .txt is better?

Hi is using the samples in the README, I use that extensions

> Without the -R flag, is working normal

@vhanghiuc Letme test and debug that error. Thank you for report it.

Regards!

**Comment by albertobsd** [comment]
Solved in last commit in Development Branch   7fdf0d62393114dc5cf684549e998ff80b7a758a

Plese update your code:
- Save all your files (substracted, bPTables, your own txt)
- delete the current folder
- Clone the respository with 
  `git clone https://github.com/albertobsd/keyhunt.git`
- Change to the development version with
  `git checkout development`
- Compile and test

**Comment by vhanghiuc** [comment]
Hi Alberto,

Looks good, the random values are inside the selected range! 

Thanks :)

**Comment by sezginyildirim91** [comment]
https://github.com/albertobsd/keyhunt/issues/53
