### ISSUE TITLE
-R Mode

### ISSUE THREAD

**Issue by sezginyildirim91** [albertobsd/keyhunt#53]
`-M RMD160 -R` mode is progressing in the same order.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/J35RY5H/Ekran-g-r-nt-s-2021-04-16-193708.png" alt="Ekran-g-r-nt-s-2021-04-16-193708" border="0"></a>

**Comment by vhanghiuc** [comment]
Hello,

Actually, is checking the keys sequentially, until the default threshold is reached (I forgot what was it....but is big).
If you add for ex the _-n 1000000_ argument , it will search also sequentially until it reaches 1 mil, but then it will switch to a random base key from the range that you specified.

**Comment by sezginyildirim91** [comment]
> Hello,
> 
> Actually, is checking the keys sequentially, until the default threshold is reached (I forgot what was it....but is big).
> If you add for ex the _-n 1000000_ argument , it will search also sequentially until it reaches 1 mil, but then it will switch to a random base key from the range that you specified.

I forgot to try this out, it wasn't like that in the other version. Thank you so much.
