### ISSUE TITLE
BSGS mode

### ISSUE THREAD

**Issue by Chesterfield007** [albertobsd/keyhunt#56]
I waited, about 3 hours there is no reaction, I think it does not work normally!!!!!

./keyhunt -t 24 -r 1:fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141 -m bsgs -f pubadd.txt -k 800050 -R -n 655360000 -s 1 -q                                                                  [+] Version 0.1.20210412 secp256k1                                                                                      [+] Setting 24 threads                                                                                                  [+] Setting mode BSGS                                                                                                   [+] Setting k factor to 800050                                                                                          [+] Setting random mode.                                                                                                [+] Stats output every 1 seconds                                                                                        [+] Set quiet thread output                                                                                             [+] Opening file pubadd.txt                                                                                             [+] Added 22 points from file                                                                                           [+] Setting N up to 0.                                                                                                  [+] Init 1st bloom filter for 20481280000 elements : 70207.00 MB                                                        [+] Init 2nd bloom filter for 1024064000 elements : 3510.37 MB                                                          [+] Allocating 0.0 MB for 0 aMP Points                                                                                  [+] Precalculating 0 aMP points                                                                                         [+] Allocating 15625.98 MB for 1024064000 bP Points                                                                     [+] processing 20481269760/20481280000 bP points^C 99%[[C0/20481280000 bP points : 99%

**Comment by vanrzuf** [comment]
The same on wsl ubuntu. But with 1 thread it worked

**Comment by albertobsd** [comment]
Thanks for report this, I solved this, is already in the main code, commit :  a75a7bbe23e3dd281628508dc7710ad39fc72665

**Comment by Chesterfield007** [comment]
> Спасибо за сообщение об этом, я решил это, уже в основном коде, совершить : [ a75a7bb ](https://github.com/albertobsd/keyhunt/commit/a75a7bbe23e3dd281628508dc7710ad39fc72665)

thx bro!!!!
