### ISSUE TITLE
BSGS

### ISSUE THREAD

**Issue by voltaxvoltax** [albertobsd/keyhunt#58]
Hey guys, I would like to use the fastest method ( BSGS) but I can't find a way to convert a list of Bitcoin addresses to PubKey ( compressed or uncompressed), can you guys give a me a little help?
Thank you!

**Comment by dem10** [comment]
Addresses cannot be converted into public keys. The public key is opened if there was at least one outgoing transaction from the address or these are solo mining addresses.

**Comment by voltaxvoltax** [comment]
Ahh, I see, thanks! Do you know any tool/method to get those in bulk?

**Comment by dem10** [comment]
here is a link to the topic you are interested in. it seems there is even a link to the tool. study.
https://bitcoin.stackexchange.com/questions/37291/all-bitcoin-public-keys-with-non-zero-balance

**Comment by voltaxvoltax** [comment]
Awesome, thanks! :)
