### ISSUE TITLE
buil error

### ISSUE THREAD

**Issue by Xh0st** [albertobsd/keyhunt#59]
g++ -m64 -mssse3 -Wno-unused-result -Wno-write-strings -O2 -c secp256k1/Int.cpp -o Int.o
g++: error: unrecognized command line option ‘-m64’
g++: error: unrecognized command line option ‘-mssse3’
make: *** [Makefile:9: default] Error 1

**Comment by albertobsd** [comment]
What are your linux system?, What kind of processor or machine are you using.

regards!

**Comment by Xh0st** [comment]
sorry I forgot to mention I try to build on Ubuntu 20.04 ARM device. I have try to replace -m64 with - march=armv8-a

**Comment by Xh0st** [comment]
root@localhost:~# lscpu
Architecture:        aarch64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           2
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         2189.0000
CPU min MHz:         480.0000
BogoMIPS:            3.84
Flags:               fp asimd evtstrm aes pmull
                     sha1 sha2 crc32 cpuid

**Comment by amiwrcd** [comment]
@Xh0st  most likely you need to install packages: 
`sudo apt-get install libgmp3-dev libmpfr-dev`

**Comment by dem10** [comment]
No, this is most likely due to the architecture of the ARM processor. These processors are not very good at computing.

**Comment by Sadoharu** [comment]
@albertobsd, can add arm support for keyhunt? Or its no possible?

**Comment by albertobsd** [comment]
> @albertobsd, can add arm support for keyhunt? Or its no possible?

Some funtions in keyhunt are made with the code of the secp256k1 librery and it only is optimized for Intel and AMD, but not for ARM,

For that processor you only can use the libgmp version but that is some outdated to use that you need to do a checkout to a previous version:

git checkout 05482850ed246ce759c77db948dda28f8c570eb9
And the try to make it again.

Regards!

**Comment by albertobsd** [comment]
try to compile with 

```make legacy```
