### ISSUE TITLE
How to change the search range for keys in xpoint mode?

### ISSUE THREAD

**Issue by amiwrcd** [albertobsd/keyhunt#60]
Hello Albertobsd! In xpoint mode, how can the search range for keys be changed? Let's say for example from `7000000000` to `FFFFFFFFFF`? I noticed you set the decimal number` -n 65536` this is fine for me too, but the search goes from `1` to `65536` and I would like to select a specific range, is it possible to do this? I tried running `-n 481036337152:1099511627775` but something didn't work. What am I doing wrong?

**Comment by dem10** [comment]
you need flaf -r(range).example -r 81036337152:1099511627775 but then don't use the -b flag.

**Comment by amiwrcd** [comment]
@dem10 Excellent thanks for the advice. I applied the `-r` (range) flag and everything works! I was wondering what advantage does the `-b` flag have? Why do we remove the `-b` flag when specifying a range of keys?

**Comment by dem10** [comment]
the -b(bits) flag is the range in bits. that is, by specifying -b 120, the program will search only in the full range of 120 bits. and with the -r flag, you yourself can choose in which space to search for the key (decrease or increase the space). if you set the flags - b and -r at the same time, then the program will only work with the -b flag.

**Comment by albertobsd** [comment]
@dem10 thanks a lot for reply.

@amiwrcd your doubt was solved?

**Comment by amiwrcd** [comment]
@albertobsd Everything works perfectly! Thank you!
