### ISSUE TITLE
Pub2rmd error or norm?

### ISSUE THREAD

**Issue by Chesterfield007** [albertobsd/keyhunt#62]
Hi bro!
range 64 should be 8000000000000000: ffffffffffffffff
Pub2rmd mode shows 
Thread 020000000000000000000000000000000000000000000000008000000700000000
is it a error or should it be so?
![pub2rmd](https://user-images.githubusercontent.com/62137126/116814336-df3e7a80-ab71-11eb-8986-fcf5d661da29.png)

**Comment by dem10** [comment]
wrong. max range 64 is FFFFFFFFFFFFFFFF. and what is divide by zero?

**Comment by albertobsd** [comment]
Isn't an error, becuase that opcion `pub2rmd` works with compress publickeys it test alwas 02 and 03 at the begging of the byte-string. That option was just a test.

best regards!
