### ISSUE TITLE
new readme for the new addon's.

### ISSUE THREAD

**Issue by dextronomous** [albertobsd/keyhunt#63]
hi there, wanted to ask, could you maybe add the changes you made to your programs, 
to the main page, or in the readme, or a bit with the changed version numbers or the latest you have,
thanks again for the nice progs.

**Comment by albertobsd** [comment]
Hi, nice to see you here, the file that are you looking for is the [CHANGELOG](https://github.com/albertobsd/keyhunt/blob/main/CHANGELOG.md).

**Comment by dextronomous** [comment]
oh that fast, what i wantedto know is, the difference between the next versions V0.1.20210420 - V0.1.20210328 , example 
-m rmd160 in given space -r or -R mode in diff.  between these versions from uint32_t to uint64_t i saw this in changelog
 328 version slow , but the second one 420 is faast, -R or -r, but example and question is about the new version
if i do -r d200000000000000 it starts/goes like d2000***00****** boom it goes all  *=random the two *00*'s change but it keeps there, without changing d2000 showing counts every 30 seconds 13434910 keys/s with -R all *************** work a bit faster and great, now 
my question is actually could you make it go faster while in sequential search cause i did not use -n at all, to go trough 
d****000**000000 also instead of the above cause my range would have been dfffffffffffffff

when make from latest git version shows 412, no probs btw.

**Comment by dem10** [comment]
-r is the search range specified in hex. this is similar to the -b flag where you specify the range in bits. And the -R flag is a random search in the specified range. That is, with the -R flag, the search will not be performed from the smallest to the largest key, but will be selected randomly The version of the program is not changed in the file keyhunt.c
![Безымянный125](https://user-images.githubusercontent.com/24973894/116961138-2da36480-acab-11eb-976f-b05e874f6023.png)
