### ISSUE TITLE
Ethereum

### ISSUE THREAD

**Issue by deathbreakfast77** [albertobsd/keyhunt#64]
Когда появится KeyHunt для Ethereum?

**Comment by albertobsd** [comment]
In some weeks, sorry i been some busy this days.

**Comment by OceanGW** [comment]
works for ethereum now？

**Comment by albertobsd** [comment]
sorry guys not yet but i'm finishing an update that will work for ethereum.

please follow the next issue: https://github.com/albertobsd/keyhunt/issues/89
