### ISSUE TITLE
How to remove print in keyhunt?

### ISSUE THREAD

**Issue by amiwrcd** [albertobsd/keyhunt#65]
@albertobsd  please tell me how to remove the print in the "keyhunt" code itself. So that the terminal does not show the result of the brute-force. Can I do this by changing the code myself?

**Comment by Mafiasource** [comment]
Hi,
Yes! Sorry I'm not albertobsd but know a thing or two about code.
If you wish you can remove or comment out all line instances of printf(); in the ./keyhunt.c file before compiling / (re-)make
Good luck!

**Comment by amiwrcd** [comment]
@Mafiasource Thanks!

**Comment by albertobsd** [comment]
hi, that is true you can edit all the printf and fprintf add them some double slash `// `to comment it.

Another opcion is add the nex param `-s 0 -q` to quiet the speed counter and the threads output.

best regards!
