### ISSUE TITLE
pub2rmd

### ISSUE THREAD

**Issue by ender79** [albertobsd/keyhunt#67]
-m pub2rmd -f file.txt -R -l compress

example Output
Thread 022c3aaeb94e8ab2d1ae69d40ac876bb96ea6874118e20c5fc7cb0891700000000
Thread 029ad40a2c23ac6b9a5acaaf8ca788a199eb4992e06e73ba8d5a90b02500000000
Thread 025de820cb511b0e55107f35e406f205f7af0f239b90885d9b849282c300000000

 -m pub2rmd -f file.txt -r 1:ffffff -l compress

example Output
 Thread 020000000000000000000000000000000000000000000000000000000000000000

Searched key start is the same '02'
Can you help with the bug? 

Thanks

**Comment by albertobsd** [comment]
is not a bug, publickeys compress always start with 02 and 03, only the remained string is random,

¿Did you know what pub2rmd do?

**Comment by ender79** [comment]
now i understand how it works. Thanks.
