### ISSUE TITLE
Execute a option thousand or million public key execute once a time

### ISSUE THREAD

**Issue by ashraful1980** [albertobsd/keyhunt#69]
Dear Sir,
I would like to let you know that the tool of keyhunt is execute to check public key from tests/test120.txt; could you please execute a option thousand or million public key check once a time. It will be more specific tool to crack private key from bit range....

Thanks & Regards,
Md. Ashraful Alam

**Comment by Mafiasource** [comment]
I think that's possible with the current version.
Maybe you need to fill the file 120.txt or any other file for that matter with multiple public keys of wallet addresses you wish to hunt for.

**Comment by albertobsd** [comment]
The input file can have any number of keys that fit in your physical RAM. ANY.

But the process for BGSG takes more time by each additional publickey, if you want to load a Billion of publickeys you need to use the xpoint mode.

Regards!

**Comment by ashraful1980** [comment]
Dear Sir,
Thank you for your valuable response; Please let me know about bellow commands:
./keyhunt -m xpoint -f tests/120.txt -b 120 -R -k 1024 -q -p ./bPfile.bin -t 48
So please confirm it is right way.

Thanks & Regards,
Md. Ashraful Alam

**Comment by ashraful1980** [comment]
Dear Sir,
Thank you for your amazing keyhunt tool; it was 183.5 Petakeys/s.

![keyhunt](https://user-images.githubusercontent.com/52574658/120594827-4d24dd00-c463-11eb-97bb-a3302d2a6b16.jpg)

Kindly execute the GPU option it will 1000 time faster to scan private key.

Regards,
Md. Ashraful Alam

**Comment by websonder** [comment]
@ashraful1980 what is your Computer specification ? ram and Processor?

**Comment by ashraful1980** [comment]
AMD Ryzen 3rd Gen 24 Core 48 Thread, 256 GB RAM, Geeforce RTX 2X 3080 GPU

**Comment by websonder** [comment]
but this keyhunt not Using Gpu, then how u use it?
