### ISSUE TITLE
Search by coordinates in parentheses with commas (Gx, Gy)?

### ISSUE THREAD

**Issue by amiwrcd** [albertobsd/keyhunt#70]
Hello @albertobsd  I use the `"xpoint"` mode for search, but my entire list of public keys is in the coordinates brackets` (Gx, Gy)`

Here's an example of my list:

```
(0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 , 0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8)
(0xc6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5 , 0x1ae168fea63dc339a3c58419466ceaeef7f632653266d0e1236431a950cfe52a)
(0xf9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9 , 0x388f7b0f632de8140fe337e62a37f3566500a99934c2231b6cb9fd7584b8e672)
(0xe493dbf1c10d80f3581e4904930b1404cc6c13900ee0758474fa94abe8c4cd13 , 0x51ed993ea0d455b75642e2098ea51448d967ae33bfbdfe40cfe97bdc47739922)
(0x2f8bde4d1a07209355b4a7250a5c5128e88b84bddc619ab7cba8d569b240efe4 , 0xd8ac222636e5e3d6d4dba9dda6c9c426f788271bab0d6840dca87d3aa6ac62d6)
(0xfff97bd5755eeea420453a14355235d382f6472f8568a18b2f057a1460297556 , 0xae12777aacfbb620f3be96017f45c560de80f0f6518fe4a03c870c36b075f297)
(0x5cbdf0646e5db4eaa398f365f2ea7a0e3d419b7e0330e39ce92bddedcac4f9bc , 0x6aebca40ba255960a3178d6d861a54dba813d0b813fde7b5a5082628087264da)
(0x2f01e5e15cca351daff3843fb70f3c2f0a1bdd05e5af888a67784ef3e10a2a01 , 0x5c4da8a741539949293d082a132d13b4c2e213d6ba5b7617b5da2cb76cbde904)
(0xacd484e2f0c7f65309ad178a9f559abde09796974c57e714c35f110dfc27ccbe , 0xcc338921b0a7d9fd64380971763b61e9add888a4375f8e0f05cc262ac64f9c37)
(0xa0434d9e47f3c86235477c7b1ae6ae5d3442d49b1943c2b752a68e2a47e247c7 , 0x893aba425419bc27a3b6c7e693a24c696f794c2ed877a1593cbee53b037368d7)


```

I would really like to change the code for the `"xpoint"` mode myself so that` keyhunt` does a search by coordinates in parentheses with commas `(Gx, Gy)`, is it possible to do this and how can I change the code?

Thank you in advance for your help!

**Comment by dem10** [comment]
Why do you need points x and y? Dot x are compressed addresses and points x and y are uncompressed addresses but the private key will be the same for compressed and uncompressed addresses.

**Comment by amiwrcd** [comment]
@dem10 The fact is that the list of coordinates of public keys I have is very huge, about `400 GB`, and I see no reason to convert the entire list completely into a compressed format. It would be better for me to change  code  `"keyhunt"`.

**Comment by dem10** [comment]
I think the program will simply not work with a file of this size, or the speed will be 100 keys per second. Well, good luck.

**Comment by amiwrcd** [comment]
@dem10 i split the list into multiple files and want to run on separate remote virtual machines

**Comment by dem10** [comment]
It was possible to extract public keys from the blockchain in the usual form. I am sure that the program would recognize uncompressed public key and the X coordinate.

**Comment by albertobsd** [comment]
in xpoint mode when the program read a publickey compress or uncompress, the program only extract the X value of the publickey.

The Y value is omitted.

why you want to work with that format?

If you want to change the code of keyhunt to do that you can do it.

I'm not going to add that format because is not common.

Regards!
