### ISSUE TITLE
How to increase speed rmd160 mode

### ISSUE THREAD

**Issue by luckyalab** [albertobsd/keyhunt#71]
Hi @albertobsd .

Good Morning, 

In BSGG mode I am able get 23 terakeys/s. 

Whereas I am getting only 7,000,000 keys/s in rmd160 mode.

Is there way to get BSGS speed of 23 terakeys/s in rmd160 mode?

Thanks in advance

**Comment by dem10** [comment]
Since in BSGS mode you do not convert the pubkey to a hash160.And BSGS algorithm can only search by the pubkey.

**Comment by luckyalab** [comment]
> 
> 
> In rmd160 mode, you search by hash160..And BSGS algorithm can only search by the pubkey.

I am aware of it.  what I am interested is can rmd160 mode can run at the same speed as BSGS speed?

**Comment by dem10** [comment]
BSGS algorithm is much faster than searching by hash160. In searching for hash160, the program has to additionally convert the pubkey to hash160, that is, to perform +1 mathematical operation.I think that the search for hash160 cannot be as fast as BSGS mode.

**Comment by albertobsd** [comment]
those both algorithms are completely different, the speed that you say are correct and can't be increase

**Comment by luckyalab** [comment]
thank you @albertobsd
