### ISSUE TITLE
how the -R switch works in bsgs mode

### ISSUE THREAD

**Issue by Noname400** [albertobsd/keyhunt#72]
how the -R switch works in bsgs mode

**Comment by Noname400** [comment]
hi. can you explain how random mode works in BSGS mode

**Comment by albertobsd** [comment]
It select a random value in the given range, and then  it use as basekey for the search in the bsgs mode, from that value to the same value plus N

example:

```
[+] Min range: 800000000000000000000000000000
[+] Max range: 1000000000000000000000000000000
[+] Setting random mode.
[+] Setting N up to 17592186044416.
...
[+] Thread b521656305ca32547ac29f567793ee
[+] Thread 9af90da21dc807ac91977a4430c3cd
[+] Thread c2d10f360a2c06150876e5bad364e0
...
```
ever thread set his own base key, N = 17592186044416 this is 0x100000000000 (hexadecimal)  (2^25), so every thread search from - to:

```
[+] Thread b521656305ca32547ac29f567793ee to b521656305ca32547ad29f567793ee
[+] Thread 9af90da21dc807ac91977a4430c3cd to 9af90da21dc807ac91a77a4430c3cd
[+] Thread c2d10f360a2c06150876e5bad364e0 to c2d10f360a2c06150886e5bad364e0
```

Sorry for not explain this before.

Regards

**Comment by Noname400** [comment]
how to increase N

**Comment by albertobsd** [comment]
`-n value`

I recoment one of the next values:

```
70368744177664
281474976710656
1125899906842624
4503599627370496
18014398509481984
72057594037927936
288230376151711744
1152921504606846976
4611686018427387904
```

**Comment by Noname400** [comment]
keyhunt -m bsgs -f 120.txt -b 120 -R -k 20 -n 17592186044416
error
![image](https://user-images.githubusercontent.com/74019756/135889926-d77354e5-847c-4fe7-9883-89f73c7f43e1.png)

**Comment by albertobsd** [comment]
yes i have some bug,  i will solve it in the next update

**Comment by Noname400** [comment]
thx. 
when to wait for the update?

**Comment by albertobsd** [comment]
it fixed now!

**Comment by SMF-contact** [comment]
Thank you so much 😊
________________________________
