### ISSUE TITLE
Function in a time interval

### ISSUE THREAD

**Issue by amiwrcd** [albertobsd/keyhunt#74]
Hello everybody! Is it possible to run keyhunt within a certain time period and then shutdown the process. I would really like to set the search interval to 4 hours and after the elapsed time, the process turned off on its own.

**Comment by Noname400** [comment]
TaskKill + bat file + планировщик виндовс.

**Comment by amiwrcd** [comment]
@Noname400 I am a Linux user do you have Bash scripts to temporarily run "[keyhunt](https://github.com/albertobsd/keyhunt/)"?

**Comment by Noname400** [comment]
Crontab

**Comment by Noname400** [comment]
Crontab - e
Запускать сценарий каждый день, каждый час, каждый час, с 8:00 до 16:00:
00 08-16 * * * /path/to/script.sh
