### ISSUE TITLE
Your take on the Intel Xeon Phi (72510,72550) performance..

### ISSUE THREAD

**Issue by gitxmax** [albertobsd/keyhunt#76]
Came across this animal by accident, 68 cores, 272 threads, built in 16gb fast ram. They are very task specific and mostly used on super computers. Not sure, how well it will perform for puzzle solving..
My plan/fun project is to build a dedicated, solar powered machine..

**Comment by albertobsd** [comment]
Sorrry what is your question?

The program can work on any Linux system with any number of threads only limited by physical CPU's and RAM

Regards!
