### ISSUE TITLE
Does RIPEMD mode work only with HASH160 of pubkeys and not work with HASH160 of bitcoin addresses directly ?

### ISSUE THREAD

**Issue by Manosuper** [albertobsd/keyhunt#78]
Does RIPEMD mode word only with HASH160 of pubkeys and not work with bitcoin addresses directly ?

Then I try use RIPEMD of addresses I get this:

[+] Sorting data ... done! 310497 values were loaded and sorted
Base key: fffffffffffffffffffffffff649cafe
Base key: fffffffffffffffffffffffffeaf5533 s
Base key: fffffffffffffffffffffffff6586bd5 /s
Base key: ffffffffffffffffffffffffff3bc381 /s
...
...
...
Base key: fffffffffffffffffffffffffacbd7cc s/s
Base key: fffffffffffffffffffffffff7c72198 s/s
Base key: fffffffffffffffffffffffffd7c9d67 s/s
Base key: fffffffffffffffffffffffff36c7836 s/s

exit....

NOTHING FIND :(

Br

**Comment by dem10** [comment]
A Bitcoin address is created by hashing the public key with SHA-256, then hash that with RIPEMD-160.No two hash160.
![public-key-hash160](https://user-images.githubusercontent.com/24973894/120205880-26805f80-c233-11eb-8160-296f5aa7de4c.png)
