### ISSUE TITLE
Does keyhunt work with such ranges ?

### ISSUE THREAD

**Issue by Manosuper** [albertobsd/keyhunt#79]
start:0000000000000000000000000000000000800000000000000000000000000000
end:0000000000000000000000000000000000ffffffffffffffffffffffffffffff

p.s. I think I was making a mistake but restart and waiting 4 hours for calculate base points do not thant.  f*k. ((

???

Thank you !

**Comment by albertobsd** [comment]
If you want to use a specific range user `-r AAAA:FFFFF` instead the -b option.

Please check the examples in the readme.
