### ISSUE TITLE
120 Puzzle example

### ISSUE THREAD

**Issue by oguzdelioglu** [albertobsd/keyhunt#8]
What do I have to write to the txt file to solve 120 puzzles?

I saved it in my file like this.
Did I add it correctly?

`04ceb6cbbcdbdf5ef7150682150f4ce2c6f4807b349827dcdbdd1f2efa885a26302b195386bea3f5f002dc033b92cfc2c9e71b586302b09cfe535e1ff290b1b5ac # Compressed Address : 17s2b9ksz5y7abUm92cHwG8jEPCzK3dLnT`

**Comment by albertobsd** [comment]
Thanks for using my code.

Yes that is correct, any word after the 130 character publickey is ignored.

with that file the command to search the privatekey is:

```
./keyhunt -m bsgs -f 120.txt -r 800000000000000000000000000000:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF -R
```

where 120.txt is you file

Best regards good luck!
