### ISSUE TITLE
Public keys mode

### ISSUE THREAD

**Issue by marissia** [albertobsd/keyhunt#80]
Dear Albert! 
I need your help please tell me why I see zero in end  Total 0 keys 
./keyhunt -m bsgs -f pub.txt -b 225 -R
[+] Version 0.1.20210412 secp256k1
[+] Setting mode BSGS
[+] Min range: 100000000000000000000000000000000000000000000000000000000
[+] Max range: 200000000000000000000000000000000000000000000000000000000
[+] Setting random mode.
[+] Opening file pub.txt
[+] Added 153 points from file
[+] Bit Range 225
[+] Setting N up to 17592186044416.
[+] Init 1st bloom filter for 4194304 elements : 14.00 MB
[+] Init 2nd bloom filter for 209716 elements : 0.72 MB
[+] Allocating 480.0 MB for 4194304 aMP Points
[+] Precalculating 4194304 aMP points
[+] Allocating 3.20 MB for 209716 bP Points
[+] processing 4194304/4194304 bP points : 100%
[+] Sorting 209716 elements... Done!
[+] Thread 10e1a5c665081dab9d60ef203ce9b8a372b3d9642a06e326a621657a6
Total 0 keys in 30 seconds: 0 keys/s
What wrong I do. I try different range and only 120 works but I dont need 120 , I
Can I use my own range example  as we use on address mode 
aca0c00c35bc21de83941c6912b129d6649b9dfb4eef9dff4bc6173000000000:aca0c00c35bc21de83941c6912b129d6649b9dfb4eef9dff4bc6173fffffffff    ????
in address mode I see exactly which keys scanning now, here I want understand how it works, program choose it own parameters to scan? how I can add my own range and use public key mode??
please dont ignore my asking, I crush my head from thinking

**Comment by marissia** [comment]
now I try 120 range and same pic 
./keyhunt -m bsgs -f pub.txt -b 120 -R
[+] Version 0.1.20210412 secp256k1
[+] Setting mode BSGS
[+] Min range: 800000000000000000000000000000
[+] Max range: 1000000000000000000000000000000
[+] Setting random mode.
[+] Opening file pub.txt
[+] Added 153 points from file
[+] Bit Range 120
[+] Setting N up to 17592186044416.
[+] Init 1st bloom filter for 4194304 elements : 14.00 MB
[+] Init 2nd bloom filter for 209716 elements : 0.72 MB
[+] Allocating 480.0 MB for 4194304 aMP Points
[+] Precalculating 4194304 aMP points
[+] Allocating 3.20 MB for 209716 bP Points
[+] processing 4194304/4194304 bP points : 100%
[+] Sorting 209716 elements... Done!
[+] Thread b691ca126b293a259443e4c3ac1db1
Total 0 keys in 390 seconds: 0 keys/s
why it doesnt work?

**Comment by albertobsd** [comment]
if you want to use a specific range use `-r AAAA:FFFFF` instead of -`b <bit number>`.

About the time to complete one cicle and show the correct speed please let it run some time, its working. But before please test it with the following number of publickeys in the input file, 1,10,20,50,100 etc, just to know the speed of your machine.

Regards!

**Comment by marissia** [comment]
thanks too much,!!  it work after 5 min I see progress,
