### ISSUE TITLE
Alberto, can you implement a work with password list ?

### ISSUE THREAD

**Issue by Manosuper** [albertobsd/keyhunt#81]
Hi ;)

I try crack with 256 MB memory and speed is beast ofcause, but try crack 256 Bitc unreal get any privatekeys. 120 is to long too.

1) Alberto, can you impement keyhunt work not only with ranges, but with password-list too ? Ex - password->privakey key->check->result ? I get 44 Petakeys  with -k 16000. :) but this is not enoth for find something unfortnately :(

2) Implement please for rundom mode make range of randomnes more big then now. For example in -r 1111:999999999 not work with 1111,2222,33333 etc but 1111, 99999999,7777777,3333333 ,22222 etc. ???

**Comment by albertobsd** [comment]
No, that is not the goal of the program. For password use the brainflayer program
