### ISSUE TITLE
Param -a is ignored

### ISSUE THREAD

**Issue by xsoft** [albertobsd/keyhunt#83]
When using -a parameter, it seems that it's completely ignored.

```
./keyhunt -a a.bin -m bsgs -f btc.txt -b 120 -R -k 128
[+] Version 0.1.20210412 secp256k1
./keyhunt: invalid option -- 'a'
[E] Unknow opcion ?
[+] Setting mode BSGS
[+] Min range: 800000000000000000000000000000
[+] Max range: 1000000000000000000000000000000
[+] Setting random mode.
[+] Setting k factor to 128
[+] Opening file btc.txt
[E] There is no valid data in the file

```

Is is possible to create a bloom filer by keyhunt? To create it just once and then use multiple times?

**Comment by albertobsd** [comment]
The aM Points vary from one range to another, so, i will disable that option, also in the next update whe only need 512 aMP for any range, so those values can be calculated fast, so there is not need to store it in a file.

Regards!
