### ISSUE TITLE
Luis ?

### ISSUE THREAD

**Issue by Manosuper** [albertobsd/keyhunt#84]
Good day.

Luis, then you will make a GPU version ? I'm very interested because is hard for me  get many CPU memory PC. 

Luis, make a GPU version as soon is possible ?

Big Thank You.
BR !

**Comment by albertobsd** [comment]
No, sorry i don't have GPU

**Comment by Manosuper** [comment]
> No, sorry i don't have GPU

Hi, Bro !

Luis, is it posible use SSD vs RAM ? Fast SSD is not so expensive then RAM. 

What you thin about work with SSD option ?

Regard.

**Comment by albertobsd** [comment]
No it will not work directly the swapping process is very slow and it will damage your SSD. I already try it

**Comment by albertobsd** [comment]
No it will not work directly the swapping process is very slow and it will damage your SSD. I already try it

**Comment by Manosuper** [comment]
> No it will not work directly the swapping process is very slow and it will damage your SSD. I already try it

Ok.

Thank You Luis.

Regard ;)
