### ISSUE TITLE
I run keyhunt 12 hours - and got this results with rmd command

### ISSUE THREAD

**Issue by albertvps2021** [albertobsd/keyhunt#85]
Base key:   84ed240a277e0f55e5############    0   keys/s

Base key:   84ed240a277e0f55e5############     9   keys/s

what does it mean - i replace the value with # for privacy here on comment..

**Comment by albertobsd** [comment]
Good, but what is your problem?

The Thread output is overlaping the speed output.

Use  `-q` to avoid thread output
