### ISSUE TITLE
How to get the output if we found any key after running keyhunt for a long time on ubantu

### ISSUE THREAD

**Issue by albertvps2021** [albertobsd/keyhunt#86]
Tell us any command to save cracked key in txt file on ubantu

with command example for ubantu machine with 5g ram

**Comment by we-akri** [comment]
by default the found key is saved in the file  KEYFOUNDKEYFOUND.txt in the program folder

**Comment by albertobsd** [comment]
Thanks @we-akri that is right the file is saved automatically if something is found.

So please make sure that you have the privilege to write files in the current directory

Regards!
