### ISSUE TITLE
is it possible bloom filter on ssd?

### ISSUE THREAD

**Issue by we-akri** [albertobsd/keyhunt#88]
is it possible to use a bloom filter with fast ssd but without ram or use part of ram?
i tried to create a virtual ram in linux using a 1tb swap file on fast ssd.
but unfortunately the creation in mode BSGS of such a file took almost 4 days and the program came up 99% and stuck.
maybe it was necessary to wait one more day.....
I do not understand why this does not work if the speed of my ram 4500mb/s and ssd 3420mb/s 
it seems that the difference is not at all big, but the this approach doesn't work  :(

**Comment by albertobsd** [comment]
The main problem is the swap process, it's not done to do that with large large amount of memory.

To achieve that goal we need to skip the RAM usage this is made the bloom filter directly in disk instead of ram, to do that we need to write a lot of changes in code.

Regards.

**Comment by we-akri** [comment]
Wow it turns out it is still possible and the idea itself can be successful. if take a high-speed ssd for 2 terabytes, perhaps the processing speed itself will be slightly slower, however, the final speed will clearly be better than 128 GB of RAM.
it is possible to reach 1 zetalion per second

**Comment by fankoo** [comment]
I think its not good point to use ssd swap. the speed is slow.

**Comment by albertobsd** [comment]
> it is possible to reach 1 zetalion per second

No is not possible , maybe we can reach some Exakeys/s but not more.

> I think its not good point to use ssd swap. the speed is slow.

With swap process is slow yes. but if we omit that step ( RAM Process  and swap process ) and work directly with the SSD as a file is possible gain some little speed more. Not much because the SSD NVram disk are some tens of magnitud more slow than RAM but also it have some tents more space. 

So its complicated to know if the extra capacity compensate the NVram letancy.

**Comment by dem10** [comment]
> Wow it turns out it is still possible and the idea itself can be successful. if take a high-speed ssd for 2 terabytes, perhaps the processing speed itself will be slightly slower, however, the final speed will clearly be better than 128 GB of RAM.
> it is possible to reach 1 zetalion per second

For a 2TB disk, you will need about 300-400 GB of RAM. Even if the program uses a bPfile with dots, it still uses RAM. And the larger the bPfile, the more RAM you need.

**Comment by albertobsd** [comment]
That is right, for each item in the bloom filter, we still need some 20 bytes for binary search.

Each bloom filter item is about 28 bits (~4 bytes).

So we can put only one of those in disk and the other in RAM to mix up the process.

Data for binary search is less accessed than the data for bloom filter. So viewing this now, is better store the bloom filter in RAM and the Data for binary search in Disk.

Disk space need to be 5 times  greater than RAM space. This will fit all the speeds (fast access to bloom filter and slow access for Binary Data)

**Comment by gitxmax** [comment]
albertobsd, how does threads number corelates with the ram, I mean will you get better speeds, by using double cpu motherboard or my using double amount of ram ang increasing K. Also, can the script utilize the multi lanes advantage, if say a motherboard has 8 ram slots?
Thanks

**Comment by albertobsd** [comment]
I don't know bro.

It depends of the BUS between each CPU and the RAM but it is totally outside of my knowledge.

Regards!
