### ISSUE TITLE
Windows release

### ISSUE THREAD

**Issue by dem10** [albertobsd/keyhunt#9]
Hello @albertobsd . Is it possible to compile the release for Windows?Tnx...kanhavishva version for windows has a very low speed.And do not have a parameter - bsgs.Speed 8 threads
![KeyHunt](https://user-images.githubusercontent.com/24973894/108364373-0dfdb380-7207-11eb-893b-d5e55df91bdd.png)

**Comment by albertobsd** [comment]
That is the speed for Address. And yes that version is from an old copy, i need to see what changes I need to do to make this program run on windows native  that changes are alot, btw for now you can use the Ubuntu terminal for windows 10 avaible in the windows store.

**Comment by dem10** [comment]
> That is the speed for Address. And yes that version is from an old copy, i need to see what changes I need to do to make this program run on windows native that changes are alot, btw for now you can use the Ubuntu terminal for windows 10 avaible in the windows store.

Yes, in this version there is only the -m xpoint flag. I ran the tool with it. Using the -R flag really leads to a fast filling of the RAM. Unfortunately, I can't use the terminal. But the virtual machine does not want to be installed from a disk image, although virtualization is enabled. Probably some kind of bug with Windows 20h2.

**Comment by dem10** [comment]
Only windows release

**Comment by dem10** [comment]
Hi @albertobsd. What does the new update give? 
Keyhunt updated with k factor, remove unused files about keccak 
bPfile.c updated.

**Comment by dem10** [comment]
Hi  @albertobsd, what does update 0.1.20210306 do?

**Comment by iceland2k14** [comment]
update 0.1.20210306 mainly introduces kfactor in the BSGS search mode. It breaks the dependency of loop with the items in the bPtable. Which basically means you will get more speed but more usage of RAM.

**Comment by dem10** [comment]
It seems to me that the keys are counted in a decimal segment. Us need to translate the program into hexadecimal counting and so that each core counts a combination of 15 characters in each line at the same time. The first number is given by the range.

**Comment by albertobsd** [comment]
For those who wants Windows version try to compile with mingw 64 bits. @chawyehsu already compiled it for windows using this mingw Enviroment.

I just download it i will try to compile it, and maybe i will do a guide.

best regards!

**Comment by dem10** [comment]
> For those who wants Windows version try to compile with mingw 64 bits. @chawyehsu already compiled it for windows using this mingw Enviroment.
> 
> I just download it i will try to compile it, and maybe i will do a guide.
> 
> best regards!

Yes, I sort of managed to compile the program using msys2. I'll try to test it on a 60 bit solved key 0000000000000000000000000000000000000000000000000fc07a1825367bbe.

**Comment by dem10** [comment]
> For those who wants Windows version try to compile with mingw 64 bits. @chawyehsu already compiled it for windows using this mingw Enviroment.
> 
> I just download it i will try to compile it, and maybe i will do a guide.
> 
> best regards!

I conducted a test on key 60. The program works on Windows and finds the key, but for some reason the speed indicator does not appear. More precisely, it appears for a second and disappears. The same problem was on the Ubuntu virtual machine.
![123](https://user-images.githubusercontent.com/24973894/113131374-cca8ec80-9225-11eb-8ee6-5a0af7a24589.png)

**Comment by albertobsd** [comment]
My recomendation for that problem is that you use one of those options:

`-q`
`-s 0`

I need to find another work around for the threadout and the speed output, right now is a total mess but for now you can solve using only one of those option, one `-q` is for quiet the thread output and  `-s 0` is for quiet the speed counter.

best regards.
