### ISSUE TITLE
 pub2rmd mode issue

### ISSUE THREAD

**Issue by nft30001** [albertobsd/keyhunt#91]
```
./keyhunt -c btc -m pub2rmd -f 160 -q -R -n 10000000 -t 3 -r 20000000000000:ffffffffffffffffffffffffffffff 
or
./keyhunt -c btc -m pub2rmd -f 160 -q -R -n 10000000 -t 3 -r 20000000000000:ffffffffffffffffffffffffffffff -s 1
```

2 questions 

1.  why range is not working in this mode , i guess i should see "Setting up base key". but no information 
2. in Random mode after every 10m scan CLI should display like new base key info within range , or even range is not working in this mode, still this should print new base key always.

**Comment by studyroom1** [comment]
same question

**Comment by albertobsd** [comment]
Try it without the `-R` option, that option overwrite the `-r 20000000000000:ffffffffffffffffffffffffffffff`

example:

```
albertobsd $ ./keyhunt -m pub2rmd -f tests/puzzleswopublickey.txt -r 20000000000000:ffffffffffffffffffffffffffffff
[+] Version 0.1.20210420 secp256k1
[+] Setting mode pub2rmd
[+] Opening file tests/puzzleswopublickey.txt
[+] Allocating memory for 29 elements: 0.00 MB
[+] Initializing bloom filter for 29 elements.
[+] Loading data to the bloomfilter total: 0.00 MB
[+] Bloomfilter completed
[+] Sorting data ... done! 29 values were loaded and sorted
[+] Thread 020000000000000000000000000000000000000000000000000020000000000000
Total 51380224 keys in 60 seconds: 856337 keys/s
```
if you add the -R option the output change:

```
albertobsd $ ./keyhunt -m pub2rmd -f tests/puzzleswopublickey.txt -r 20000000000000:ffffffffffffffffffffffffffffff -R
[+] Version 0.1.20210420 secp256k1
[+] Setting mode pub2rmd
[+] Setting random mode.
[+] Opening file tests/puzzleswopublickey.txt
[+] Allocating memory for 29 elements: 0.00 MB
[+] Initializing bloom filter for 29 elements.
[+] Loading data to the bloomfilter total: 0.00 MB
[+] Bloomfilter completed
[+] Sorting data ... done! 29 values were loaded and sorted
[+] Thread 020000000000000000000000000000000000f6dc2b8c96c4530d55e1de00000000
```
Idk what are you trying to do, the pub2rmd was a test, it is only try to find the publickey of a unknow RMD160 hash but the odds are worse than than the odd of find the privatekey.

Regards

**Comment by nft30001** [comment]
i think in BSGS -R is not over writing -r. Right? so why this one overwrite in  pub2rmd?

**Comment by albertobsd** [comment]
> i think in BSGS -R is not over writing -r. Right? so why this one overwrite in pub2rmd?

Let me check this with calm, maybe i have some mistake in the code, this mode pub2rmd was a experiment and i write it in some hour while i was drunk so maybe i mess it

**Comment by sigkill** [comment]
Do you have a fix or a version where pub2rmd works? I keep getting 0 keys per second in this mode, with the test files and files I've created.

**Comment by albertobsd** [comment]
Sorry for that but this experimental mode will be removed in a few days

**Comment by ghost** [comment]
why its removed?

**Comment by albertobsd** [comment]
> why its removed?

because find a public key is twice difficult than find a 256 private key

**Comment by ZEVLOUS** [comment]
Ohh now I understood
Thanks

**Comment by babybatrick** [comment]
> > why its removed?
> 
> because find a public key is twice difficult than find a 256 private key

Is doing EC Multiplication to get the public key cheaper than doing RIPEMD160(SHA256()) to get the public key hash, for a given 32 byte hex?

**Comment by babybatrick** [comment]
I dont know what numbers you had, but ChatGPT told me this:

SHA-256 compute time:
> The average time to compute a SHA-256 hash of a 32-byte input is typically in the range of:
>
>~100 to 500 nanoseconds on modern CPUs.
>
>More precise benchmarks (approximate):
>Intel x86-64 (with SHA extensions):
>~100–200 ns (due to hardware acceleration)
>
>Intel/AMD x86-64 (no SHA extensions):
>~300–500 ns
>
>ARM Cortex-A series (with cryptographic extensions):
>~150–300 ns
>
>ARM (without hardware acceleration):
>~500–1000 ns

RIPEMD-160 compute time
> The average time to compute a RIPEMD-160 hash of a 32-byte input is generally:
>
>~400 to 800 nanoseconds on modern CPUs.
>
>Approximate breakdown:
>Intel x86-64 (no hardware acceleration for RIPEMD):
>~500–700 ns (pure software implementation)
>
>ARM Cortex-A series:
>~600–900 ns (software only)
>
>RIPEMD-160 is slower than SHA-256
>because it's older, less optimized in compilers/libraries, and has no hardware acceleration on typical platforms.

EC Multiplication compute time:
>Computing elliptic curve scalar multiplication (i.e., Q = k·G, where k is a 32-byte scalar and G is the secp256k1 base point) is significantly slower than hashing:
>
>Average compute time for Q = k·G on secp256k1:
>Optimized C libraries (e.g., libsecp256k1 by Bitcoin Core):
>~2 to 10 microseconds (μs) → 2000–10,000 nanoseconds
>
>Platform-dependent examples:
>Intel x86-64 (libsecp256k1) 
>~2–5 μs (2000–5000 ns)
>
>ARM Cortex-A (e.g. mobile CPU)
>~5–15 μs
>
>Go btcd/btcec (unoptimized)
>~15–25 μs
>
>Rust (with k256 crate)
>~3–10 μs
