### ISSUE TITLE
115 Bytes not fond then I use  BSGS and xpoint mode. Luis help please ?

### ISSUE THREAD

**Issue by Manosuper** [albertobsd/keyhunt#92]
Luis good day !

I was test this range:

Q = 021a86d51f261971b92118f6956b93bb6c7515698eaaa2a7097f3ec920ac3d50ec
range: 60f4d11574f5deee49960d9609ac6 : 60f4d11574f5deee4996fd9609ac6

xpoint nothing founded !!!

How to solve this ?
Regard !

**Comment by albertobsd** [comment]
- 115 bits, no bytes.
- Please always add full command that you use and the output.
- Your 115 bit publickey is no the puzzle 115.

I test with the puzzle 115 publickey:  `0248D313B0398D4923CDCA73B8CFA6532B91B96703902FC8B32FD438A3B7CD7F55`

Range: `60F4D11574F5DEEE49951D9609AC6:60F4D11574F5DEEE49971D9609AC6`

Output:

```
albertobsd $ ./keyhunt -r 60F4D11574F5DEEE49951D9609AC6:60F4D11574F5DEEE49971D9609AC6 -f ./puzzle115.txt -m bsgs -k 20
[+] Version 0.1.20210312 K*BSGS
[+] Setting mode BSGS
[+] Setting k factor to 20
[+] Opening file ./puzzle115.txt
[+] Added 1 points from file
[+] Setting N up to 137443698720.
[+] Init 1st bloom filter for 7414560 elements : 25.00 MB
[+] Init 2nd bloom filter for 1089200 elements : 3823.00 KB
[+] Allocating 0.0 MB for aMP Points
[+] Precalculating 18537 aMP points
[+] Precalculating 2523756 aMP points (2nd)
[+] Allocating 17018.00 KB for 1089200 bP Points
[+] precalculating 7414560 bP points
[+] Sorting 1089200 elements
[+] Thread 0: 0000000000000000000000000000000000060f4d11574f5deee49951d9609ac6
[+] Thread 0 Key found privkey 0000000000000000000000000000000000060f4d11574f5deee49961d9609ac6
[+] Publickey 0448d313b0398d4923cdca73b8cfa6532b91b96703902fc8b32fd438a3b7cd7f5566f0742c24f5ff80c799d691d756ad8e5aa7f6d8f986abd9eeef45514637c0d4
All points were found
```
also i use your range:

```
albertobsd $ ./keyhunt -r 60f4d11574f5deee49960d9609ac6:60f4d11574f5deee4996fd9609ac6 -f ./puzzle115.txt -m bsgs -k 20
[+] Version 0.1.20210312 K*BSGS
[+] Setting mode BSGS
[+] Setting k factor to 20
[+] Opening file ./puzzle115.txt
[+] Added 1 points from file
[+] Setting N up to 64424592400.
[+] Init 1st bloom filter for 5076400 elements : 17.00 MB
[+] Init 2nd bloom filter for 901600 elements : 3164.00 KB
[+] Allocating 0.0 MB for aMP Points
[+] Precalculating 12691 aMP points
[+] Precalculating 1429117 aMP points (2nd)
[+] Allocating 14087.00 KB for 901600 bP Points
[+] precalculating 5076400 bP points
[+] Sorting 901600 elements
[+] Thread 0: 0000000000000000000000000000000000060f4d11574f5deee49960d9609ac6
[+] Thread 0 Key found privkey 0000000000000000000000000000000000060f4d11574f5deee49961d9609ac6
[+] Publickey 0448d313b0398d4923cdca73b8cfa6532b91b96703902fc8b32fd438a3b7cd7f5566f0742c24f5ff80c799d691d756ad8e5aa7f6d8f986abd9eeef45514637c0d4
All points were found
```

**Comment by Manosuper** [comment]
Hello, Luis. Yes it worked then 1 pubkey but then 1000 000 pubkeys bloom filter shutdown and not worked, so, I was try use xpoint option -  I was run keysubtracter with param 115 bytes and n 1000000. Then I run keyhunt xpoin mode and nothing found. unfortunately is hard find a 115 withount know ranges, if brute 115 not from  60f4d11574f5deee49960d9609ac6 : 60f4d11574f5deee4996fd9609ac6 but from 1:70f4d11574f5deee4996fd9609ac6 this not found any privkeys. 

Can you please  try my 115 file with 115 mode **xpoint** ? maiby yo will be find a privkey ?

Link to my files with publick keys https://anonfiles.com/X6N5I07fu1/115-final2_txt
Regards

**Comment by albertobsd** [comment]
i dont want to try your file, may be you dont  have idea of what are you doing.

Sorry.
