### ISSUE TITLE
Jacoby coordinates with Endomorphism ?

### ISSUE THREAD

**Issue by Manosuper** [albertobsd/keyhunt#93]
Gooda Day Luis !!!

Can you add this methods to keyhunt ? In the article info how to implement endomorphism with Jacoby coordinates to pubkeys for speed up computations.

https://paulmillr.com/posts/noble-secp256k1-fast-ecc/#unsafe-multiplication-for-key-recovery

Regard.

**Comment by amiwrcd** [comment]
@Manosuper  I have already raised this issue. Unfortunately it will not be able to.
https://github.com/albertobsd/keysubtracter/issues/13
