### ISSUE TITLE
Server Functionality

### ISSUE THREAD

**Issue by yoyodapro** [albertobsd/keyhunt#94]
Hey Luis, has there been any progress towards including a server for Keyhunt?

**Comment by dem10** [comment]
Do you want the server to record progress? If you have bsgs search installed in random mode, then recording progress is pointless, since the server will have to save all the generated keys. Can you imagine how many terabytes the database will be in a day of work if one key takes about 64 bytes ? 64,000,000,000,000,000 keys will occupy approximately 58207 TByte.

**Comment by yoyodapro** [comment]
I want it to distribute work and record baby steps completed in sequential mode. if a key is found by one of the clients then it will be reported to the server. every individual key does not need to be recorded.

**Comment by yoyodapro** [comment]
if the server keeps track of the ranges issued to the workers and records completed ranges only that would be better.

**Comment by dem10** [comment]
There are 664613997892457936451903530140172287 keys in the 120 range.There will be too many subranges.
   664,613,997,892,457,936,451,903,530,140,172,287 keys 120bit range
                                        1,000,000,000,000,000,000 keys/s(1 ExaKeys) For example, the speed of your pool.
You need 664,613,997,892,457,936 seconds to scan the full 120 range. People hope for luck in a random search.

**Comment by yoyodapro** [comment]
im currently getting in the range of ~900 Exakeys/s across my threadrippers using 90% of all their cores, wanted to link them together somehow.

**Comment by dem10** [comment]
The speed is great, but it won't make much of a difference in time, and it will take you ~21074771 years to get through the full 120 range.

**Comment by albertobsd** [comment]
I am about to finish some BSGS server that work on  demand.

Check my dashboard or pendings

https://trello.com/b/GXBPiBCM/keyhunt

**Comment by yoyodapro** [comment]
Sounds good! if you need any testing done let me know

**Comment by albertobsd** [comment]
test if you want

https://github.com/albertobsd/keyhunt/blob/main/BSGSD.md
