### ISSUE TITLE
Do threads affect speed?

### ISSUE THREAD

**Issue by sberlinux** [albertobsd/keyhunt#95]
Hi Luis Alberto! I want to increase the threads to 1000. The question is whether the speed of brute-force and random private keys generation will be preserved if I set the threads -t 1000 -R? Do threads affect speed?

That is, the command for Ubuntu in the terminal will be like this:

`./keyhunt -m xpoint -f basefile.txt -r 1:EEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF -t 1000 -R`

**Comment by dem10** [comment]
Run and see. Set the -q flag so that the threads outputs do not clog the statistics and see.
./keyhunt -m xpoint -f basefile.txt -r 1:EEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF -t 1000 -R -q

**Comment by sberlinux** [comment]
@dem10 What is the function of the **-q** flag?

**Comment by dem10** [comment]
-q set quiet the thread output

**Comment by sberlinux** [comment]
@dem10 I have long ago drowned out the statistics by adding a double slash to them, **//** to all **printf**
My question is, will the speed be affected by increasing the **-t** thread, and will the speed be affected if I use the **-R** flag (that is, randomly generating keys)?
