### ISSUE TITLE
How to choose N ?

### ISSUE THREAD

**Issue by MajMcCloud** [albertobsd/keyhunt#97]
Hey!,
I'm using your tool for some time ago, on one hand to understand how it works and on the other hand for the structure and security of Bitcoin.

I tried multiple times to choose a parameter N (multiples of 1024), also tried the "default" number of 17592186044416 which is used in BSGS. Even with the "default" I received error messages, that it doesn't fit.

Can you tell how to choose a higher or different number and what to take care of ?
Cause that error messages seems to be irritating.

Thank you so much!
Warm regards
Florian

**Comment by MajMcCloud** [comment]
I'm receiving the following error:

_[E] M value is not divisible by 1024_

**Comment by studyroom1** [comment]
1048576, 1073741824, 1099511627776, 1125899906842624
you can try these values one by one and see the speed, one of above mentioned value should work. if still u got error do tell me full command which you are using.

**Comment by MajMcCloud** [comment]
Thanks for your feedback. I tried the first ones and they are working (1048576, 1073741824)
But for the last ones im getting the same error (1099511627776, 1125899906842624)

I have the following command to try the puzzle 120

.\keyhunt-msvc.exe -m bsgs -r 800000000000000000000000000000:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF -f .\puzzle120.txt -q -l compress -R -n 1125899906842624

**Comment by MajMcCloud** [comment]
I found another way to just change it in code and recompiled it. Works for now under windows. (linux as well)

But did not have any clue how to choose that number by parameter.

**Comment by albertobsd** [comment]
> I found another way to just change it in code and recompiled it. Works for now under windows. (linux as well)

Don't do that please

> But did not have any clue how to choose that number by parameter.

`-n <number>`

It need s to be a exact power of 2, it need to have exact square root

**Comment by MajMcCloud** [comment]
> Don't do that please

Ok, what could happen?

> -n <number>

Ok, I new "n" already but the choice of number was unclear

Ah power of 2... so this means, any number pow 2 is fine ?

So i tried 2^40 which doesnt worked. 
When trying 65536 doesn't work either...
when trying 1024*8=8192^2 = 67108864 works again...im confused

**Comment by studyroom1** [comment]
define the -K value as per your ram capacity and try again one by one above mentioned values (1048576, 1073741824, 1099511627776, 1125899906842624)

**Comment by MajMcCloud** [comment]
Ok I will try it that way. Thank you!

**Comment by Noname400** [comment]
NOT WORK. pls help
