### ISSUE TITLE
120 puzle. Share 1.2 BTC 50/50 !!! ASAP Please !!!

### ISSUE THREAD

**Issue by Manosuper** [albertobsd/keyhunt#98]
If someone find a privkey for this pubkey in a range:

1:1124bff742a76f92fa3a76f8f6552f (decimal only 89014422443240977657631574972585263 !!! ) Range is mach less then origginal 120 Puzle range !!!

pubkey:

03c95ba9e6a637e739d13a6d036507ecc37a70c26e68ac7e5f157268311c6c3938
02c95ba9e6a637e739d13a6d036507ecc37a70c26e68ac7e5f157268311c6c3938

**search in publey what start with 02 some faster than 03.**

you can try any of this pubkeys.

Proof of my succes tests with another ranges and same pubkeys one what start with 03, and anower start with 02:

Working on Pubkey: 049fa3ea651e72c5f0a660c7ae509ad180860477283f539c918a2e43514c29da92237c8751b32e5 90883aa8bd617c60aa6b388aa78381cc7adb10046a33b038598
Using [Number of CPU Threads: 3] [DP size: 10] [MaxStep: 1]
............................................
Scanning Range 0x1 : 0x100000000000000
[55.22 TeraKeys/s][Kang 3072][Count 2^27.92/2^29.06][Elapsed 48s][Dead 0][RAM 25.8MB/44.7MB]
============== KEYFOUND ==============
Kangaroo FOUND PrivateKey : 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbf59aefd71d64b15

Working on Pubkey: 049fa3ea651e72c5f0a660c7ae509ad180860477283f539c918a2e43514c29da92dc8378ae4cd1a 6f77c557429e839f5594c775587c7e338524effb95bc4fc7697
Using [Number of CPU Threads: 3] [DP size: 10] [MaxStep: 1]
............................................
Scanning Range 0x1 : 0x100000000000000
[42.05 TeraKeys/s][Kang 3072][Count 2^28.68/2^29.06][Elapsed 01:26][Dead 0][RAM 37.7MB/44.7MB]
============== KEYFOUND ==============
Kangaroo FOUND PrivateKey : 0x0000000000000000000000000000000000000000000000000078af8f5e5ff62c
We are spit 1.2 btc 50/50 after with someone who publication in this thread privkey first, all others member sorry... !!!

Lets DO IT ???

Oficila thread - https://bitcointalk.org/index.php?topic=5358408.0

**Comment by albertobsd** [comment]
please don't use this section to post bullshit
